// The Infernal skill system: authentic dark-fantasy skill trees, data-as-code. This
// layer is the DATA + display foundation (a D2-styled skill-tree viewer reads
// it). A later layer wires selected skills to castable ClaudeCraft abilities
// with real elemental VFX. English source strings, like the rest of the realm
// presentation content; no i18n/DOM/engine imports here.
//
// req is the skill level requirement (the tree tier). element/kind
// tag each skill so the future castable layer can pick the right VFX and effect.

export type SkillElement = 'fire' | 'cold' | 'lightning' | 'poison' | 'magic' | 'physical' | 'holy';

export type SkillKind =
  | 'attack'
  | 'passive'
  | 'aura'
  | 'summon'
  | 'curse'
  | 'buff'
  | 'trap'
  | 'shift';

export interface InfernalSkill {
  id: string;
  name: string;
  /** skill-level requirement (1/6/12/18/24/30 tiers). */
  req: number;
  element?: SkillElement;
  kind: SkillKind;
  desc: string;
}

export interface InfernalSkillTree {
  name: string;
  skills: readonly InfernalSkill[];
}

export interface InfernalClassSkillset {
  /** Canonical hero name (matches infernal_classes / the create roster). */
  className: string;
  source: string;
  trees: readonly InfernalSkillTree[];
}

const s = (
  id: string,
  name: string,
  req: number,
  kind: SkillKind,
  element: SkillElement | undefined,
  desc: string,
): InfernalSkill => ({ id, name, req, kind, ...(element ? { element } : {}), desc });

export const INFERNAL_SKILLSETS: readonly InfernalClassSkillset[] = [
  {
    className: 'Amazon',
    source: 'The Dark Exile',
    trees: [
      {
        name: 'Javelin and Spear',
        skills: [
          s('jab', 'Jab', 1, 'attack', 'physical', 'A rapid series of spear thrusts at one foe.'),
          s(
            'power_strike',
            'Power Strike',
            6,
            'attack',
            'lightning',
            'A melee strike charged with lightning.',
          ),
          s(
            'poison_javelin',
            'Poison Javelin',
            6,
            'attack',
            'poison',
            'Throws a javelin trailing a cloud of venom.',
          ),
          s(
            'impale',
            'Impale',
            12,
            'attack',
            'physical',
            'A savage thrust that ignores much of the target armor.',
          ),
          s(
            'lightning_bolt',
            'Lightning Bolt',
            18,
            'attack',
            'lightning',
            'Turns a thrown javelin into a bolt of lightning.',
          ),
          s(
            'charged_strike',
            'Charged Strike',
            18,
            'attack',
            'lightning',
            'A melee stab that releases charged bolts on hit.',
          ),
          s(
            'plague_javelin',
            'Plague Javelin',
            24,
            'attack',
            'poison',
            'A javelin that erupts into a spreading plague.',
          ),
          s(
            'fend',
            'Fend',
            24,
            'attack',
            'physical',
            'Strikes every enemy in reach in one motion.',
          ),
          s(
            'lightning_strike',
            'Lightning Strike',
            30,
            'attack',
            'lightning',
            'A melee hit that arcs lightning between foes.',
          ),
          s(
            'lightning_fury',
            'Lightning Fury',
            30,
            'attack',
            'lightning',
            'Throws a javelin that splits into forking lightning.',
          ),
        ],
      },
      {
        name: 'Passive and Magic',
        skills: [
          s(
            'inner_sight',
            'Inner Sight',
            1,
            'buff',
            'magic',
            'Illuminates nearby enemies, lowering their defense.',
          ),
          s(
            'critical_strike',
            'Critical Strike',
            1,
            'passive',
            'physical',
            'A chance to deal double physical damage.',
          ),
          s(
            'dodge',
            'Dodge',
            6,
            'passive',
            'physical',
            'A chance to avoid melee attacks while standing.',
          ),
          s(
            'slow_missiles',
            'Slow Missiles',
            12,
            'buff',
            'magic',
            'Slows the speed of enemy projectiles.',
          ),
          s(
            'avoid',
            'Avoid',
            12,
            'passive',
            'physical',
            'A chance to avoid ranged attacks while standing.',
          ),
          s(
            'penetrate',
            'Penetrate',
            18,
            'passive',
            'physical',
            'Increases attack rating against all foes.',
          ),
          s('decoy', 'Decoy', 24, 'summon', 'magic', 'Summons a mirror image to draw enemy fire.'),
          s(
            'evade',
            'Evade',
            24,
            'passive',
            'physical',
            'A chance to avoid attacks while running.',
          ),
          s(
            'valkyrie',
            'Valkyrie',
            30,
            'summon',
            'holy',
            'Summons a spectral warrior-maiden to fight beside you.',
          ),
          s(
            'pierce',
            'Pierce',
            30,
            'passive',
            'physical',
            'A chance for missiles to pass through and hit again.',
          ),
        ],
      },
      {
        name: 'Bow and Crossbow',
        skills: [
          s(
            'magic_arrow',
            'Magic Arrow',
            1,
            'attack',
            'magic',
            'Converts part of an arrow into magic damage.',
          ),
          s(
            'fire_arrow',
            'Fire Arrow',
            1,
            'attack',
            'fire',
            'Ignites an arrow to add fire damage.',
          ),
          s(
            'cold_arrow',
            'Cold Arrow',
            6,
            'attack',
            'cold',
            'Chills the target with a frost-tipped arrow.',
          ),
          s(
            'multiple_shot',
            'Multiple Shot',
            6,
            'attack',
            'physical',
            'Fires a fan of arrows across a wide arc.',
          ),
          s(
            'exploding_arrow',
            'Exploding Arrow',
            12,
            'attack',
            'fire',
            'An arrow that detonates on impact.',
          ),
          s('ice_arrow', 'Ice Arrow', 18, 'attack', 'cold', 'Freezes the target solid on a hit.'),
          s(
            'guided_arrow',
            'Guided Arrow',
            18,
            'attack',
            'magic',
            'An arrow that seeks its target relentlessly.',
          ),
          s(
            'strafe',
            'Strafe',
            24,
            'attack',
            'physical',
            'Looses arrows at many targets in quick succession.',
          ),
          s(
            'immolation_arrow',
            'Immolation Arrow',
            30,
            'attack',
            'fire',
            'An arrow that leaves a pool of fire behind.',
          ),
          s(
            'freezing_arrow',
            'Freezing Arrow',
            30,
            'attack',
            'cold',
            'Bursts into a chilling blast that freezes a group.',
          ),
        ],
      },
    ],
  },
  {
    className: 'Assassin',
    source: 'The Dark Exile',
    trees: [
      {
        name: 'Martial Arts',
        skills: [
          s(
            'tiger_strike',
            'Tiger Strike',
            1,
            'attack',
            'physical',
            'Charges up a devastating physical finisher.',
          ),
          s(
            'dragon_talon',
            'Dragon Talon',
            1,
            'attack',
            'physical',
            'A rising chain of martial kicks.',
          ),
          s(
            'fists_of_fire',
            'Fists of Fire',
            6,
            'attack',
            'fire',
            'Charges strikes with searing flame.',
          ),
          s(
            'dragon_claw',
            'Dragon Claw',
            6,
            'attack',
            'physical',
            'A two-clawed strike that unleashes charges.',
          ),
          s(
            'cobra_strike',
            'Cobra Strike',
            12,
            'attack',
            'physical',
            'Charges that steal life and mana on release.',
          ),
          s(
            'claws_of_thunder',
            'Claws of Thunder',
            18,
            'attack',
            'lightning',
            'Charges strikes with crackling lightning.',
          ),
          s(
            'dragon_tail',
            'Dragon Tail',
            18,
            'attack',
            'fire',
            'A kick that explodes in fire around the target.',
          ),
          s(
            'blades_of_ice',
            'Blades of Ice',
            24,
            'attack',
            'cold',
            'Charges strikes with freezing cold.',
          ),
          s(
            'dragon_flight',
            'Dragon Flight',
            24,
            'attack',
            'physical',
            'Teleport-kicks to a distant enemy.',
          ),
          s(
            'phoenix_strike',
            'Phoenix Strike',
            30,
            'attack',
            'fire',
            'Charges that release fire, ice, and lightning.',
          ),
        ],
      },
      {
        name: 'Shadow Disciplines',
        skills: [
          s(
            'claw_mastery',
            'Claw Mastery',
            1,
            'passive',
            'physical',
            'Improves damage and accuracy with claws.',
          ),
          s(
            'psychic_hammer',
            'Psychic Hammer',
            1,
            'attack',
            'magic',
            'A telekinetic hammer that knocks foes back.',
          ),
          s(
            'burst_of_speed',
            'Burst of Speed',
            6,
            'buff',
            'magic',
            'Greatly increases attack and run speed.',
          ),
          s(
            'weapon_block',
            'Weapon Block',
            12,
            'passive',
            'physical',
            'A chance to block melee and missile attacks.',
          ),
          s(
            'cloak_of_shadows',
            'Cloak of Shadows',
            18,
            'curse',
            'magic',
            'Blinds and lowers the defense of nearby foes.',
          ),
          s('fade', 'Fade', 18, 'buff', 'magic', 'Raises resistances and curse resistance.'),
          s(
            'shadow_warrior',
            'Shadow Warrior',
            24,
            'summon',
            'magic',
            'Summons a shadow that mimics your recent skills.',
          ),
          s(
            'mind_blast',
            'Mind Blast',
            24,
            'attack',
            'magic',
            'Stuns and converts nearby enemies.',
          ),
          s('venom', 'Venom', 30, 'buff', 'poison', 'Coats your attacks in fast-acting poison.'),
          s(
            'shadow_master',
            'Shadow Master',
            30,
            'summon',
            'magic',
            'Summons a mirror-self that uses your full kit.',
          ),
        ],
      },
      {
        name: 'Traps',
        skills: [
          s(
            'fire_blast',
            'Fire Blast',
            1,
            'trap',
            'fire',
            'Hurls a small charge that bursts in fire.',
          ),
          s(
            'shock_web',
            'Shock Web',
            6,
            'trap',
            'lightning',
            'A trap that sprays crawling bolts of lightning.',
          ),
          s(
            'blade_sentinel',
            'Blade Sentinel',
            6,
            'trap',
            'physical',
            'A spinning blade that patrols and cuts foes.',
          ),
          s(
            'charged_bolt_sentry',
            'Charged Bolt Sentry',
            12,
            'trap',
            'lightning',
            'A turret that fires charged bolts.',
          ),
          s(
            'wake_of_fire',
            'Wake of Fire',
            18,
            'trap',
            'fire',
            'A trap that sends waves of fire forward.',
          ),
          s(
            'blade_fury',
            'Blade Fury',
            18,
            'attack',
            'physical',
            'Flings whirling blades at range.',
          ),
          s(
            'lightning_sentry',
            'Lightning Sentry',
            24,
            'trap',
            'lightning',
            'A turret that arcs lightning at enemies.',
          ),
          s(
            'wake_of_inferno',
            'Wake of Inferno',
            30,
            'trap',
            'fire',
            'A trap that jets a stream of inferno.',
          ),
          s(
            'death_sentry',
            'Death Sentry',
            30,
            'trap',
            'lightning',
            'A turret that detonates corpses and fires bolts.',
          ),
          s(
            'blade_shield',
            'Blade Shield',
            30,
            'buff',
            'physical',
            'Orbiting blades cut any foe that draws near.',
          ),
        ],
      },
    ],
  },
  {
    className: 'Barbarian',
    source: 'The Dark Exile',
    trees: [
      {
        name: 'Warcries',
        skills: [
          s('howl', 'Howl', 1, 'curse', 'magic', 'A terrifying roar that sends foes fleeing.'),
          s(
            'find_potion',
            'Find Potion',
            1,
            'passive',
            'physical',
            'A chance to find potions on slain corpses.',
          ),
          s('taunt', 'Taunt', 6, 'curse', 'magic', 'Goads an enemy into a reckless charge.'),
          s('shout', 'Shout', 6, 'buff', 'magic', 'A war shout that raises party defense.'),
          s(
            'battle_cry',
            'Battle Cry',
            12,
            'curse',
            'magic',
            'A cry that lowers enemy defense and damage.',
          ),
          s(
            'battle_orders',
            'Battle Orders',
            24,
            'buff',
            'magic',
            'Raises the party maximum life, mana, and stamina.',
          ),
          s(
            'grim_ward',
            'Grim Ward',
            24,
            'curse',
            'magic',
            'A corpse totem that frightens nearby enemies.',
          ),
          s(
            'war_cry',
            'War Cry',
            30,
            'attack',
            'magic',
            'A stunning shockwave shout that damages all around.',
          ),
          s(
            'battle_command',
            'Battle Command',
            30,
            'buff',
            'magic',
            'Grants the party an extra skill level for a time.',
          ),
        ],
      },
      {
        name: 'Combat Masteries',
        skills: [
          s(
            'sword_mastery',
            'Sword Mastery',
            1,
            'passive',
            'physical',
            'Improves damage and critical hits with swords.',
          ),
          s(
            'axe_mastery',
            'Axe Mastery',
            1,
            'passive',
            'physical',
            'Improves damage and critical hits with axes.',
          ),
          s(
            'mace_mastery',
            'Mace Mastery',
            1,
            'passive',
            'physical',
            'Improves damage and critical hits with maces.',
          ),
          s(
            'polearm_mastery',
            'Polearm Mastery',
            6,
            'passive',
            'physical',
            'Improves damage and critical hits with polearms.',
          ),
          s(
            'throwing_mastery',
            'Throwing Mastery',
            6,
            'passive',
            'physical',
            'Improves thrown-weapon damage and accuracy.',
          ),
          s(
            'spear_mastery',
            'Spear Mastery',
            6,
            'passive',
            'physical',
            'Improves damage and critical hits with spears.',
          ),
          s(
            'increased_stamina',
            'Increased Stamina',
            6,
            'passive',
            'physical',
            'Raises maximum stamina.',
          ),
          s(
            'iron_skin',
            'Iron Skin',
            12,
            'passive',
            'physical',
            'Toughens the skin, raising defense.',
          ),
          s(
            'increased_speed',
            'Increased Speed',
            18,
            'passive',
            'physical',
            'Increases running and walking speed.',
          ),
          s(
            'natural_resistance',
            'Natural Resistance',
            30,
            'passive',
            'physical',
            'Raises resistance to all elements.',
          ),
        ],
      },
      {
        name: 'Combat Skills',
        skills: [
          s('bash', 'Bash', 1, 'attack', 'physical', 'A heavy blow that knocks the target back.'),
          s(
            'leap',
            'Leap',
            6,
            'attack',
            'physical',
            'Vaults across the battlefield, knocking foes down.',
          ),
          s(
            'double_swing',
            'Double Swing',
            6,
            'attack',
            'physical',
            'Strikes with both weapons in one motion.',
          ),
          s('stun', 'Stun', 12, 'attack', 'physical', 'A blow that leaves the target dazed.'),
          s(
            'double_throw',
            'Double Throw',
            12,
            'attack',
            'physical',
            'Hurls two throwing weapons at once.',
          ),
          s(
            'leap_attack',
            'Leap Attack',
            18,
            'attack',
            'physical',
            'Leaps onto a target with a crushing strike.',
          ),
          s(
            'concentrate',
            'Concentrate',
            18,
            'attack',
            'physical',
            'A focused blow that cannot be interrupted.',
          ),
          s('frenzy', 'Frenzy', 24, 'attack', 'physical', 'Each hit builds attack and run speed.'),
          s(
            'whirlwind',
            'Whirlwind',
            30,
            'attack',
            'physical',
            'Spins through a crowd, striking every foe in reach.',
          ),
          s(
            'berserk',
            'Berserk',
            30,
            'attack',
            'magic',
            'Trades defense for a devastating magic-damage blow.',
          ),
        ],
      },
    ],
  },
  {
    className: 'Druid',
    source: 'The Dark Exile',
    trees: [
      {
        name: 'Elemental',
        skills: [
          s(
            'firestorm',
            'Firestorm',
            1,
            'attack',
            'fire',
            'Sends waves of writhing flame across the ground.',
          ),
          s(
            'molten_boulder',
            'Molten Boulder',
            6,
            'attack',
            'fire',
            'Rolls a burning boulder that crushes and ignites.',
          ),
          s(
            'arctic_blast',
            'Arctic Blast',
            6,
            'attack',
            'cold',
            'Breathes a cone of freezing air.',
          ),
          s('fissure', 'Fissure', 12, 'attack', 'fire', 'Cracks the earth open with jets of lava.'),
          s(
            'cyclone_armor',
            'Cyclone Armor',
            12,
            'buff',
            'magic',
            'A wind shield that absorbs elemental damage.',
          ),
          s(
            'twister',
            'Twister',
            18,
            'attack',
            'physical',
            'Sends spinning cyclones that stun on contact.',
          ),
          s('volcano', 'Volcano', 24, 'attack', 'fire', 'Erupts a volcano that rains molten rock.'),
          s(
            'tornado',
            'Tornado',
            24,
            'attack',
            'physical',
            'Unleashes a wandering cyclone that shreds foes.',
          ),
          s(
            'armageddon',
            'Armageddon',
            30,
            'attack',
            'fire',
            'Calls down a storm of flaming meteors.',
          ),
          s(
            'hurricane',
            'Hurricane',
            30,
            'attack',
            'cold',
            'Wraps you in a freezing gale that chills all nearby.',
          ),
        ],
      },
      {
        name: 'Shape Shifting',
        skills: [
          s(
            'werewolf',
            'Werewolf',
            1,
            'shift',
            'physical',
            'Transforms into a swift, savage wolf-beast.',
          ),
          s(
            'lycanthropy',
            'Lycanthropy',
            1,
            'passive',
            'physical',
            'Extends shapeshift duration and raises life.',
          ),
          s(
            'werebear',
            'Werebear',
            6,
            'shift',
            'physical',
            'Transforms into a towering, brutal bear.',
          ),
          s(
            'feral_rage',
            'Feral Rage',
            12,
            'attack',
            'physical',
            'A werewolf strike that builds speed and leech.',
          ),
          s(
            'maul',
            'Maul',
            12,
            'attack',
            'physical',
            'A werebear blow that stuns with stacking force.',
          ),
          s(
            'rabies',
            'Rabies',
            18,
            'attack',
            'poison',
            'A bite that spreads deadly disease between foes.',
          ),
          s('fire_claws', 'Fire Claws', 18, 'attack', 'fire', 'Beast claws wreathed in flame.'),
          s(
            'hunger',
            'Hunger',
            24,
            'attack',
            'physical',
            'A ravenous strike that drains life and mana.',
          ),
          s(
            'shock_wave',
            'Shock Wave',
            24,
            'attack',
            'physical',
            'A werebear stomp that stuns everything ahead.',
          ),
          s('fury', 'Fury', 30, 'attack', 'physical', 'A werewolf flurry of relentless strikes.'),
        ],
      },
      {
        name: 'Summoning',
        skills: [
          s(
            'raven',
            'Raven',
            1,
            'summon',
            'physical',
            'Summons ravens that peck and blind enemies.',
          ),
          s(
            'poison_creeper',
            'Poison Creeper',
            1,
            'summon',
            'poison',
            'A burrowing vine that poisons foes it touches.',
          ),
          s(
            'oak_sage',
            'Oak Sage',
            6,
            'summon',
            'magic',
            'A spirit that raises the party maximum life.',
          ),
          s(
            'summon_spirit_wolf',
            'Summon Spirit Wolf',
            12,
            'summon',
            'magic',
            'Calls spectral wolves to hunt at your side.',
          ),
          s(
            'carrion_vine',
            'Carrion Vine',
            12,
            'summon',
            'poison',
            'A vine that devours corpses to heal you.',
          ),
          s(
            'heart_of_wolverine',
            'Heart of Wolverine',
            18,
            'summon',
            'magic',
            'A spirit that raises party damage and accuracy.',
          ),
          s(
            'summon_dire_wolf',
            'Summon Dire Wolf',
            18,
            'summon',
            'physical',
            'Calls fierce dire wolves that devour corpses.',
          ),
          s(
            'spirit_of_barbs',
            'Spirit of Barbs',
            24,
            'summon',
            'magic',
            'A spirit that reflects damage back at attackers.',
          ),
          s(
            'summon_grizzly',
            'Summon Grizzly',
            30,
            'summon',
            'physical',
            'Calls a great spirit bear to maul your foes.',
          ),
        ],
      },
    ],
  },
  {
    className: 'Necromancer',
    source: 'The Dark Exile',
    trees: [
      {
        name: 'Summoning',
        skills: [
          s(
            'skeleton_mastery',
            'Skeleton Mastery',
            1,
            'passive',
            'magic',
            'Raises the life and damage of your undead.',
          ),
          s(
            'raise_skeleton',
            'Raise Skeleton',
            1,
            'summon',
            'magic',
            'Raises the fallen as skeletal warriors.',
          ),
          s(
            'clay_golem',
            'Clay Golem',
            6,
            'summon',
            'magic',
            'Molds a clay golem that slows what it strikes.',
          ),
          s(
            'golem_mastery',
            'Golem Mastery',
            12,
            'passive',
            'magic',
            'Raises golem life and speed.',
          ),
          s(
            'raise_skeletal_mage',
            'Raise Skeletal Mage',
            12,
            'summon',
            'magic',
            'Raises skeletal mages that hurl elemental bolts.',
          ),
          s(
            'blood_golem',
            'Blood Golem',
            18,
            'summon',
            'magic',
            'A golem that shares its life-steal with you.',
          ),
          s(
            'iron_golem',
            'Iron Golem',
            24,
            'summon',
            'magic',
            'Forges a golem from a chosen item.',
          ),
          s(
            'fire_golem',
            'Fire Golem',
            30,
            'summon',
            'fire',
            'A golem of living fire that burns nearby foes.',
          ),
          s('revive', 'Revive', 30, 'summon', 'magic', 'Raises slain monsters to fight for you.'),
        ],
      },
      {
        name: 'Poison and Bone',
        skills: [
          s('teeth', 'Teeth', 1, 'attack', 'magic', 'Fires a spread of gnashing bone teeth.'),
          s(
            'bone_armor',
            'Bone Armor',
            1,
            'buff',
            'magic',
            'A shield of bone that absorbs damage.',
          ),
          s('poison_dagger', 'Poison Dagger', 6, 'attack', 'poison', 'Envenoms a dagger strike.'),
          s(
            'corpse_explosion',
            'Corpse Explosion',
            6,
            'attack',
            'fire',
            'Detonates a corpse for area damage.',
          ),
          s(
            'bone_wall',
            'Bone Wall',
            12,
            'summon',
            'magic',
            'Raises a wall of bone to block a path.',
          ),
          s(
            'poison_explosion',
            'Poison Explosion',
            18,
            'attack',
            'poison',
            'Bursts a corpse into a cloud of venom.',
          ),
          s(
            'bone_spear',
            'Bone Spear',
            18,
            'attack',
            'magic',
            'A piercing shard of bone that runs foes through.',
          ),
          s(
            'bone_prison',
            'Bone Prison',
            24,
            'summon',
            'magic',
            'Traps a target inside a cage of bone.',
          ),
          s(
            'poison_nova',
            'Poison Nova',
            30,
            'attack',
            'poison',
            'A ring of venom that poisons everything around.',
          ),
          s(
            'bone_spirit',
            'Bone Spirit',
            30,
            'attack',
            'magic',
            'A homing skull of bone that seeks a distant foe.',
          ),
        ],
      },
      {
        name: 'Curses',
        skills: [
          s(
            'amplify_damage',
            'Amplify Damage',
            1,
            'curse',
            'magic',
            'Halves the physical resistance of cursed foes.',
          ),
          s(
            'dim_vision',
            'Dim Vision',
            6,
            'curse',
            'magic',
            'Blinds enemies so they cannot see you.',
          ),
          s('weaken', 'Weaken', 6, 'curse', 'magic', 'Lowers the damage of cursed enemies.'),
          s(
            'iron_maiden',
            'Iron Maiden',
            12,
            'curse',
            'magic',
            'Reflects a share of enemy attacks back at them.',
          ),
          s('terror', 'Terror', 12, 'curse', 'magic', 'Sends a cursed enemy fleeing in fear.'),
          s('confuse', 'Confuse', 18, 'curse', 'magic', 'Turns cursed enemies against each other.'),
          s(
            'life_tap',
            'Life Tap',
            18,
            'curse',
            'magic',
            'Attackers of the cursed foe steal its life.',
          ),
          s(
            'attract',
            'Attract',
            24,
            'curse',
            'magic',
            'Forces every nearby foe to attack one target.',
          ),
          s('decrepify', 'Decrepify', 24, 'curse', 'magic', 'Slows and weakens the cursed enemy.'),
          s(
            'lower_resist',
            'Lower Resist',
            30,
            'curse',
            'magic',
            'Lowers the elemental resistance of cursed foes.',
          ),
        ],
      },
    ],
  },
  {
    className: 'Paladin',
    source: 'The Dark Exile',
    trees: [
      {
        name: 'Defensive Auras',
        skills: [
          s(
            'prayer',
            'Prayer',
            1,
            'aura',
            'holy',
            'An aura that heals you and nearby allies over time.',
          ),
          s(
            'resist_fire',
            'Resist Fire',
            1,
            'aura',
            'fire',
            'An aura that raises party fire resistance.',
          ),
          s('defiance', 'Defiance', 6, 'aura', 'holy', 'An aura that raises party defense.'),
          s(
            'resist_cold',
            'Resist Cold',
            6,
            'aura',
            'cold',
            'An aura that raises party cold resistance.',
          ),
          s(
            'cleansing',
            'Cleansing',
            12,
            'aura',
            'holy',
            'An aura that shortens curses and poison.',
          ),
          s(
            'resist_lightning',
            'Resist Lightning',
            12,
            'aura',
            'lightning',
            'An aura that raises party lightning resistance.',
          ),
          s('vigor', 'Vigor', 18, 'aura', 'holy', 'An aura that raises run speed and stamina.'),
          s(
            'meditation',
            'Meditation',
            24,
            'aura',
            'holy',
            'An aura that greatly speeds mana recovery.',
          ),
          s(
            'redemption',
            'Redemption',
            30,
            'aura',
            'holy',
            'An aura that consumes corpses to restore life and mana.',
          ),
          s(
            'salvation',
            'Salvation',
            30,
            'aura',
            'holy',
            'An aura that raises all elemental resistances.',
          ),
        ],
      },
      {
        name: 'Offensive Auras',
        skills: [
          s('might', 'Might', 1, 'aura', 'holy', 'An aura that raises party physical damage.'),
          s(
            'holy_fire',
            'Holy Fire',
            6,
            'aura',
            'fire',
            'An aura that burns nearby enemies with holy flame.',
          ),
          s('thorns', 'Thorns', 6, 'aura', 'holy', 'An aura that returns damage to attackers.'),
          s(
            'blessed_aim',
            'Blessed Aim',
            12,
            'aura',
            'holy',
            'An aura that raises party attack rating.',
          ),
          s(
            'concentration',
            'Concentration',
            18,
            'aura',
            'holy',
            'An aura that raises damage and resists interruption.',
          ),
          s(
            'holy_freeze',
            'Holy Freeze',
            18,
            'aura',
            'cold',
            'An aura that chills and slows nearby enemies.',
          ),
          s(
            'holy_shock',
            'Holy Shock',
            24,
            'aura',
            'lightning',
            'An aura that shocks nearby enemies with lightning.',
          ),
          s(
            'sanctuary',
            'Sanctuary',
            24,
            'aura',
            'holy',
            'An aura that damages and repels the undead.',
          ),
          s(
            'fanaticism',
            'Fanaticism',
            30,
            'aura',
            'holy',
            'An aura that boosts attack speed and damage.',
          ),
          s(
            'conviction',
            'Conviction',
            30,
            'aura',
            'holy',
            'An aura that lowers enemy defense and resistances.',
          ),
        ],
      },
      {
        name: 'Combat Skills',
        skills: [
          s(
            'sacrifice',
            'Sacrifice',
            1,
            'attack',
            'physical',
            'A reckless strike that hurts you but hits harder.',
          ),
          s('smite', 'Smite', 1, 'attack', 'physical', 'A shield bash that stuns the target.'),
          s(
            'holy_bolt',
            'Holy Bolt',
            6,
            'attack',
            'holy',
            'A bolt of light that harms undead and heals allies.',
          ),
          s(
            'zeal',
            'Zeal',
            12,
            'attack',
            'physical',
            'A rapid chain of holy strikes across nearby foes.',
          ),
          s(
            'charge',
            'Charge',
            12,
            'attack',
            'physical',
            'Rushes a distant enemy with a lance strike.',
          ),
          s(
            'vengeance',
            'Vengeance',
            18,
            'attack',
            'fire',
            'A strike that adds fire, cold, and lightning.',
          ),
          s(
            'blessed_hammer',
            'Blessed Hammer',
            18,
            'attack',
            'holy',
            'Spiraling hammers of light that scythe the undead.',
          ),
          s(
            'conversion',
            'Conversion',
            24,
            'attack',
            'holy',
            'A chance to convert a struck enemy to your side.',
          ),
          s(
            'holy_shield',
            'Holy Shield',
            24,
            'buff',
            'holy',
            'Blesses the shield, raising block and smite damage.',
          ),
          s(
            'fist_of_the_heavens',
            'Fist of the Heavens',
            30,
            'attack',
            'holy',
            'Calls down a bolt of holy lightning and light.',
          ),
        ],
      },
    ],
  },
  {
    className: 'Sorcerer / Sorceress',
    source: 'The Dark Exile',
    trees: [
      {
        name: 'Cold Spells',
        skills: [
          s('ice_bolt', 'Ice Bolt', 1, 'attack', 'cold', 'A shard of ice that slows and chills.'),
          s(
            'frozen_armor',
            'Frozen Armor',
            1,
            'buff',
            'cold',
            'Freezes melee attackers that strike you.',
          ),
          s(
            'frost_nova',
            'Frost Nova',
            6,
            'attack',
            'cold',
            'A ring of frost that chills everything around.',
          ),
          s(
            'ice_blast',
            'Ice Blast',
            6,
            'attack',
            'cold',
            'A blast that freezes the target solid.',
          ),
          s(
            'shiver_armor',
            'Shiver Armor',
            12,
            'buff',
            'cold',
            'A frost shield that damages attackers.',
          ),
          s(
            'glacial_spike',
            'Glacial Spike',
            18,
            'attack',
            'cold',
            'A shard that freezes a target and those near it.',
          ),
          s(
            'blizzard',
            'Blizzard',
            24,
            'attack',
            'cold',
            'Calls down a storm of icy shards over an area.',
          ),
          s(
            'chilling_armor',
            'Chilling Armor',
            24,
            'buff',
            'cold',
            'A shield that fires ice bolts at ranged attackers.',
          ),
          s(
            'frozen_orb',
            'Frozen Orb',
            30,
            'attack',
            'cold',
            'A slow-drifting orb that sprays a ring of shards.',
          ),
          s(
            'cold_mastery',
            'Cold Mastery',
            30,
            'passive',
            'cold',
            'Lowers the cold resistance of your targets.',
          ),
        ],
      },
      {
        name: 'Lightning Spells',
        skills: [
          s(
            'charged_bolt',
            'Charged Bolt',
            1,
            'attack',
            'lightning',
            'Releases a spray of erratic charged bolts.',
          ),
          s(
            'static_field',
            'Static Field',
            6,
            'attack',
            'lightning',
            'Strips a share of life from all nearby foes.',
          ),
          s(
            'telekinesis',
            'Telekinesis',
            6,
            'attack',
            'magic',
            'A telekinetic push that knocks foes back.',
          ),
          s('nova', 'Nova', 12, 'attack', 'lightning', 'A ring of lightning that expands outward.'),
          s(
            'lightning',
            'Lightning',
            12,
            'attack',
            'lightning',
            'A bolt of lightning that pierces a line of foes.',
          ),
          s(
            'chain_lightning',
            'Chain Lightning',
            18,
            'attack',
            'lightning',
            'A bolt that leaps between clustered enemies.',
          ),
          s('teleport', 'Teleport', 18, 'buff', 'magic', 'Blinks instantly to a chosen point.'),
          s(
            'thunder_storm',
            'Thunder Storm',
            24,
            'attack',
            'lightning',
            'Bolts strike random nearby enemies over time.',
          ),
          s(
            'energy_shield',
            'Energy Shield',
            24,
            'buff',
            'magic',
            'Diverts damage to your mana pool.',
          ),
          s(
            'lightning_mastery',
            'Lightning Mastery',
            30,
            'passive',
            'lightning',
            'Raises lightning damage and lowers cast delay.',
          ),
        ],
      },
      {
        name: 'Fire Spells',
        skills: [
          s('fire_bolt', 'Fire Bolt', 1, 'attack', 'fire', 'A bolt of fire that bursts on impact.'),
          s('warmth', 'Warmth', 1, 'passive', 'fire', 'Greatly speeds mana recovery.'),
          s('inferno', 'Inferno', 6, 'attack', 'fire', 'Breathes a continuous stream of fire.'),
          s('blaze', 'Blaze', 12, 'attack', 'fire', 'Leaves a trail of fire in your wake.'),
          s(
            'fire_ball',
            'Fire Ball',
            12,
            'attack',
            'fire',
            'Hurls a bolt of fire that explodes on impact.',
          ),
          s(
            'fire_wall',
            'Fire Wall',
            18,
            'attack',
            'fire',
            'Raises a wall of flame across the ground.',
          ),
          s('enchant', 'Enchant', 18, 'buff', 'fire', 'Adds fire damage to a weapon.'),
          s(
            'meteor',
            'Meteor',
            24,
            'attack',
            'fire',
            'Calls a meteor that erupts in a fiery blast.',
          ),
          s(
            'fire_mastery',
            'Fire Mastery',
            30,
            'passive',
            'fire',
            'Raises fire damage of all your spells.',
          ),
          s(
            'hydra',
            'Hydra',
            30,
            'summon',
            'fire',
            'Summons a fire hydra that spits at your foes.',
          ),
        ],
      },
    ],
  },
];

const BY_NAME: Record<string, InfernalClassSkillset> = Object.fromEntries(
  INFERNAL_SKILLSETS.map((set) => [set.className, set]),
);

/** The full skill tree set for a canonical hero name, or null. */
export function infernalSkillsetFor(className: string): InfernalClassSkillset | null {
  return BY_NAME[className] ?? null;
}
