// GENERATED FILE - DO NOT EDIT BY HAND.
// Produced by scripts/realm_assets/gen_rosters.mjs.
//
// Per-realm faction rosters in the shape infernal_classes.ts proved out:
// a name, the upstream class it plays as, a faction, and a body. Every entry is
// bound to a REAL body from that realm's generated pool, so all of them are
// already rigged, animated and weapon-socketed - adding a character costs a table
// row, not an asset run.
//
// Names are original. Genre targets are honoured without lifting protected names.

import type { PlayerClass } from '../types';

export interface RealmRosterEntry {
  id: string;
  name: string;
  /** Upstream class this character actually plays as. */
  engineClass: PlayerClass;
  faction: string;
  /** Key into VISUALS / GENERATED_VISUALS. */
  visualKey: string;
}

export const REALM_ROSTERS: Record<string, readonly RealmRosterEntry[]> = {
  classic: [
    { id: 'ironbrand_champion', name: "Ironbrand Champion", engineClass: 'warrior', faction: "Covenant", visualKey: 'realm_classic_goblin_warlord_characters_fantas_019899f1' },
    { id: 'silverwatch_templar', name: "Silverwatch Templar", engineClass: 'paladin', faction: "Covenant", visualKey: 'realm_classic_warrior_goblin_characters_weapon_01969227' },
    { id: 'highglade_marksman', name: "Highglade Marksman", engineClass: 'hunter', faction: "Covenant", visualKey: 'realm_classic_barbarian_warrior_low_poly_019aa1d7' },
    { id: 'duskveil_cutthroat', name: "Duskveil Cutthroat", engineClass: 'rogue', faction: "Covenant", visualKey: 'realm_classic_ogre_warlord_ogre_warlord_019b99a5' },
    { id: 'dawnkeeper', name: "Dawnkeeper", engineClass: 'priest', faction: "Covenant", visualKey: 'realm_classic_goblin_warlord_characters_01976a00' },
    { id: 'runespire_adept', name: "Runespire Adept", engineClass: 'mage', faction: "Covenant", visualKey: 'realm_classic_orc_warrior_characters_weaponsmi_0196f86d' },
    { id: 'pactbinder', name: "Pactbinder", engineClass: 'warlock', faction: "Covenant", visualKey: 'realm_classic_warlord_braids_fantasy_character_019d9ea7' },
    { id: 'greenmantle_warden', name: "Greenmantle Warden", engineClass: 'druid', faction: "Covenant", visualKey: 'realm_classic_warrior_ancients_characters_0196497f' },
    { id: 'stonehelm_vanguard', name: "Stonehelm Vanguard", engineClass: 'warrior', faction: "Covenant", visualKey: 'realm_classic_cyber_troll_sentinel_characters_019736e5' },
    { id: 'lightforge_sentinel', name: "Lightforge Sentinel", engineClass: 'paladin', faction: "Covenant", visualKey: 'realm_classic_orc_warlord_orc_warlord_019899f2' },
    { id: 'wyrmscout', name: "Wyrmscout", engineClass: 'hunter', faction: "Covenant", visualKey: 'realm_infernal_creature_hunched_humanoid_form_0194f5be' },
    { id: 'gloamblade', name: "Gloamblade", engineClass: 'rogue', faction: "Covenant", visualKey: 'realm_classic_cyber_guardian_characters_scienc_0196975d' },
    { id: 'oathspeaker', name: "Oathspeaker", engineClass: 'priest', faction: "Covenant", visualKey: 'realm_classic_humanoid_form_muscular_geometry_0193daa5' },
    { id: 'frostquill_savant', name: "Frostquill Savant", engineClass: 'mage', faction: "Covenant", visualKey: 'realm_classic_game_figure_most_muscular_0195b597' },
    { id: 'bloodtusk_berserker', name: "Bloodtusk Berserker", engineClass: 'warrior', faction: "Warhost", visualKey: 'realm_classic_orc_warrior_chief_characters_0196591a' },
    { id: 'emberfang_bulwark', name: "Emberfang Bulwark", engineClass: 'paladin', faction: "Warhost", visualKey: 'realm_classic_dwarf_t_pose_chain_01938388' },
    { id: 'ashbow_stalker', name: "Ashbow Stalker", engineClass: 'hunter', faction: "Warhost", visualKey: 'realm_infernal_warrior_damned_characters_0196ca26' },
    { id: 'nightfang_reaver', name: "Nightfang Reaver", engineClass: 'rogue', faction: "Warhost", visualKey: 'realm_classic_ethereal_guardian_characters_01964e9c' },
    { id: 'spiritmender', name: "Spiritmender", engineClass: 'priest', faction: "Warhost", visualKey: 'realm_classic_game_figure_orc_warhammer_0195b538' },
    { id: 'stormcaller', name: "Stormcaller", engineClass: 'mage', faction: "Warhost", visualKey: 'realm_infernal_malevolent_majesty_fantasy_creat_019bb848' },
    { id: 'souldrinker', name: "Souldrinker", engineClass: 'warlock', faction: "Warhost", visualKey: 'realm_classic_orc_sentinel_characters_0196873a' },
    { id: 'beastspeaker', name: "Beastspeaker", engineClass: 'druid', faction: "Warhost", visualKey: 'realm_infernal_demonic_warrior_fantasy_demon_019b7108' },
    { id: 'ironjaw_warlord', name: "Ironjaw Warlord", engineClass: 'warrior', faction: "Warhost", visualKey: 'realm_classic_bionic_ogre_mutation_sciencetech_0197790f' },
    { id: 'sunscar_zealot', name: "Sunscar Zealot", engineClass: 'paladin', faction: "Warhost", visualKey: 'realm_infernal_cyber_skull_warrior_skull_019bbd57' },
    { id: 'boneshot_tracker', name: "Boneshot Tracker", engineClass: 'hunter', faction: "Warhost", visualKey: 'realm_classic_ogre_sentinel_creature_fantasy_019a8830' },
    { id: 'shadowtooth', name: "Shadowtooth", engineClass: 'rogue', faction: "Warhost", visualKey: 'realm_classic_cyberpunk_orc_adventurer_charact_019427db' },
    { id: 'ancestor_voice', name: "Ancestor Voice", engineClass: 'priest', faction: "Warhost", visualKey: 'realm_classic_goblin_boss_head_warhammer_01956cfa' },
    { id: 'cindermage', name: "Cindermage", engineClass: 'mage', faction: "Warhost", visualKey: 'realm_classic_elder_goblin_mystic_characters_0196eb8f' },
  ],
  infernal: [
    { id: 'fallen_inquisitor', name: "Fallen Inquisitor", engineClass: 'paladin', faction: "The Damned", visualKey: 'realm_infernal_rusted_infernal_golem_evil_019910d6' },
    { id: 'blood_cardinal', name: "Blood Cardinal", engineClass: 'priest', faction: "The Damned", visualKey: 'realm_infernal_titan_skulls_characters_019823a2' },
    { id: 'flesh_baron', name: "Flesh Baron", engineClass: 'warrior', faction: "The Damned", visualKey: 'realm_infernal_infernal_sentinel_characters_01974be2' },
    { id: 'plaguewright', name: "Plaguewright", engineClass: 'warlock', faction: "The Damned", visualKey: 'realm_infernal_black_myth_wukong_demon_0194b9b6' },
    { id: 'gallows_marshal', name: "Gallows Marshal", engineClass: 'hunter', faction: "The Damned", visualKey: 'realm_infernal_infernal_guardian_villain_guardi_019a8b3b' },
    { id: 'skinbinder', name: "Skinbinder", engineClass: 'rogue', faction: "The Damned", visualKey: 'realm_infernal_nosferatu_shadow_sketchto3d_mons_019834ac' },
    { id: 'horned_tyrant', name: "Horned Tyrant", engineClass: 'warrior', faction: "Ashen Court", visualKey: 'realm_infernal_infernal_grin_characters_01974ae8' },
    { id: 'emberlord', name: "Emberlord", engineClass: 'mage', faction: "Ashen Court", visualKey: 'realm_infernal_steel_guardian_robot_armor_0193fba1' },
    { id: 'soulflayer', name: "Soulflayer", engineClass: 'warlock', faction: "Ashen Court", visualKey: 'realm_infernal_hunched_creature_elongated_lumpy_01955cec' },
    { id: 'pit_stalker', name: "Pit Stalker", engineClass: 'rogue', faction: "Ashen Court", visualKey: 'realm_infernal_cyberpunk_demon_stands_t_0194371d' },
    { id: 'brimstone_herald', name: "Brimstone Herald", engineClass: 'priest', faction: "Ashen Court", visualKey: 'realm_infernal_highly_muscular_albino_devil_0193e9d4' },
    { id: 'abyssal_warden', name: "Abyssal Warden", engineClass: 'paladin', faction: "Ashen Court", visualKey: 'realm_infernal_warrior_shadows_characters_01963a09' },
    { id: 'bone_legionnaire', name: "Bone Legionnaire", engineClass: 'warrior', faction: "The Damned", visualKey: 'realm_infernal_cyber_skullbot_robot_skull_019bbd65' },
    { id: 'grave_archer', name: "Grave Archer", engineClass: 'hunter', faction: "The Damned", visualKey: 'realm_infernal_malevolent_majesty_fantasy_creat_019bb848' },
    { id: 'crypt_sovereign', name: "Crypt Sovereign", engineClass: 'warlock', faction: "The Damned", visualKey: 'realm_infernal_infernal_warlord_villain_charact_0199b160' },
    { id: 'rotcaller', name: "Rotcaller", engineClass: 'druid', faction: "The Damned", visualKey: 'realm_infernal_inferno_guardian_villain_villain_0199b560' },
    { id: 'wight_sentinel', name: "Wight Sentinel", engineClass: 'paladin', faction: "The Damned", visualKey: 'realm_infernal_demon_colossus_demon_monster_019924f9' },
    { id: 'shroud_assassin', name: "Shroud Assassin", engineClass: 'rogue', faction: "The Damned", visualKey: 'realm_infernal_infernal_warrior_characters_019659a3' },
    { id: 'radiant_exarch', name: "Radiant Exarch", engineClass: 'paladin', faction: "Heavenly Host", visualKey: 'realm_infernal_infernal_majesty_villain_fantasy_019a51bf' },
    { id: 'seraph_lancer', name: "Seraph Lancer", engineClass: 'warrior', faction: "Heavenly Host", visualKey: 'realm_infernal_cyberpunk_demon_stands_t_019434c8' },
    { id: 'choir_warden', name: "Choir Warden", engineClass: 'priest', faction: "Heavenly Host", visualKey: 'realm_infernal_muscular_humanoid_creature_pale_01943940' },
    { id: 'aureate_magus', name: "Aureate Magus", engineClass: 'mage', faction: "Heavenly Host", visualKey: 'realm_infernal_skull_warrior_characters_weapons_01965e6d' },
    { id: 'judgement_bow', name: "Judgement Bow", engineClass: 'hunter', faction: "Heavenly Host", visualKey: 'realm_infernal_highly_muscular_albino_devil_0193e9bc' },
    { id: 'silent_blade', name: "Silent Blade", engineClass: 'rogue', faction: "Heavenly Host", visualKey: 'realm_infernal_infernal_majesty_characters_0196444c' },
  ],
  fps: [
    { id: 'breacher', name: "Breacher", engineClass: 'warrior', faction: "Vanguard Company", visualKey: 'realm_classic_goblin_grin_characters_01974b44' },
    { id: 'point_man', name: "Point Man", engineClass: 'warrior', faction: "Vanguard Company", visualKey: 'realm_classic_warrior_realm_characters_0196b62c' },
    { id: 'designated_marksman', name: "Designated Marksman", engineClass: 'hunter', faction: "Vanguard Company", visualKey: 'realm_fps_game_figure_trap_jaw_0195beb7' },
    { id: 'overwatch', name: "Overwatch", engineClass: 'hunter', faction: "Vanguard Company", visualKey: 'realm_fps_he_man_toy_action_0194183a' },
    { id: 'combat_medic', name: "Combat Medic", engineClass: 'priest', faction: "Vanguard Company", visualKey: 'realm_classic_two_headed_warrior_characters_0196f30f' },
    { id: 'field_engineer', name: "Field Engineer", engineClass: 'hunter', faction: "Vanguard Company", visualKey: 'realm_classic_cybernetic_minotaur_warrior_char_0196e440' },
    { id: 'recon_scout', name: "Recon Scout", engineClass: 'rogue', faction: "Vanguard Company", visualKey: 'realm_classic_warrior_pose_pose_warrior_019badd8' },
    { id: 'demolitions', name: "Demolitions", engineClass: 'warrior', faction: "Vanguard Company", visualKey: 'realm_fps_dark_warlord_characters_weaponsm_0197c14c' },
    { id: 'shield_bearer', name: "Shield Bearer", engineClass: 'paladin', faction: "Vanguard Company", visualKey: 'realm_classic_goblin_warrior_characters_weapon_01965b74' },
    { id: 'comms_officer', name: "Comms Officer", engineClass: 'mage', faction: "Vanguard Company", visualKey: 'realm_dominion_neo_samurai_sentinel_characters_01968d05' },
    { id: 'enforcer', name: "Enforcer", engineClass: 'warrior', faction: "Iron Syndicate", visualKey: 'realm_dominion_alien_warlord_characters_01968d0f' },
    { id: 'ghost_operative', name: "Ghost Operative", engineClass: 'rogue', faction: "Iron Syndicate", visualKey: 'realm_classic_doberman_humanoid_warrior_charac_0195c669' },
    { id: 'longshot', name: "Longshot", engineClass: 'hunter', faction: "Iron Syndicate", visualKey: 'realm_classic_alien_guardian_characters_01967cc9' },
    { id: 'saboteur', name: "Saboteur", engineClass: 'rogue', faction: "Iron Syndicate", visualKey: 'realm_infernal_demonic_warrior_demon_characters_019674e0' },
    { id: 'chem_trooper', name: "Chem Trooper", engineClass: 'warlock', faction: "Iron Syndicate", visualKey: 'realm_infernal_most_bad_ass_goblin_01987255' },
    { id: 'heavy_gunner', name: "Heavy Gunner", engineClass: 'warrior', faction: "Iron Syndicate", visualKey: 'realm_classic_dwarf_t_pose_chain_01938385' },
    { id: 'drone_handler', name: "Drone Handler", engineClass: 'hunter', faction: "Iron Syndicate", visualKey: 'realm_infernal_demon_fire_rune_tattoos_0195d2f5' },
    { id: 'cutthroat', name: "Cutthroat", engineClass: 'rogue', faction: "Iron Syndicate", visualKey: 'realm_classic_leyendary_troll_boss_evil_01989498' },
    { id: 'warden', name: "Warden", engineClass: 'paladin', faction: "Iron Syndicate", visualKey: 'realm_classic_orc_warrior_queen_orc_019aad11' },
    { id: 'signal_jammer', name: "Signal Jammer", engineClass: 'mage', faction: "Iron Syndicate", visualKey: 'realm_fps_green_warlord_characters_019674e0' },
    { id: 'bounty_runner', name: "Bounty Runner", engineClass: 'rogue', faction: "Freelancers", visualKey: 'realm_classic_warrior_goblin_characters_weapon_01969220' },
    { id: 'scrapjack', name: "Scrapjack", engineClass: 'hunter', faction: "Freelancers", visualKey: 'realm_classic_alien_warrior_characters_weapons_01948189' },
    { id: 'street_doc', name: "Street Doc", engineClass: 'priest', faction: "Freelancers", visualKey: 'realm_fps_batman_overweight_halloween2025__019a2655' },
    { id: 'pit_brawler', name: "Pit Brawler", engineClass: 'warrior', faction: "Freelancers", visualKey: 'realm_infernal_goblin_mischief_goblin_fantasy_019b848b' },
    { id: 'wildcard', name: "Wildcard", engineClass: 'rogue', faction: "Freelancers", visualKey: 'realm_classic_long_nose_goblin_wizard_01967d90' },
    { id: 'gunsmith', name: "Gunsmith", engineClass: 'hunter', faction: "Freelancers", visualKey: 'realm_classic_cyclopean_warrior_characters_war_019ac698' },
    { id: 'juggernaut', name: "Juggernaut", engineClass: 'warrior', faction: "Freelancers", visualKey: 'realm_classic_goblin_warrior_characters_weapon_01965423' },
    { id: 'trickshot', name: "Trickshot", engineClass: 'hunter', faction: "Freelancers", visualKey: 'realm_classic_armored_beastlord_characters_0196c014' },
  ],
  arcane: [
    { id: 'aegis_templar', name: "Aegis Templar", engineClass: 'paladin', faction: "The Aegis", visualKey: 'realm_classic_rune_warrior_characters_0196c728' },
    { id: 'bulwark_sergeant', name: "Bulwark Sergeant", engineClass: 'warrior', faction: "The Aegis", visualKey: 'realm_classic_goblin_shaman_elder_pbr_01991782' },
    { id: 'purgation_marshal', name: "Purgation Marshal", engineClass: 'hunter', faction: "The Aegis", visualKey: 'realm_classic_game_figure_satanic_beast_0195be1a' },
    { id: 'confessor', name: "Confessor", engineClass: 'priest', faction: "The Aegis", visualKey: 'realm_arcane_shaman_s_spirit_keeper_01963bb3' },
    { id: 'sanctioned_warpseer', name: "Sanctioned Warpseer", engineClass: 'mage', faction: "The Aegis", visualKey: 'realm_classic_mystic_goblin_mage_characters_0196f84f' },
    { id: 'vigil_sister', name: "Vigil Sister", engineClass: 'paladin', faction: "The Aegis", visualKey: 'realm_infernal_black_dark_skin_demon_01938399' },
    { id: 'interdictor', name: "Interdictor", engineClass: 'rogue', faction: "The Aegis", visualKey: 'realm_classic_game_figure_satanic_beast_0195b9a5' },
    { id: 'relic_bearer', name: "Relic Bearer", engineClass: 'priest', faction: "The Aegis", visualKey: 'realm_infernal_cyberpunk_demon_stands_t_0194371d' },
    { id: 'warp_herald', name: "Warp Herald", engineClass: 'warlock', faction: "Warpborn", visualKey: 'realm_infernal_goblin_rough_leathery_green_01953dd0' },
    { id: 'riftblade', name: "Riftblade", engineClass: 'rogue', faction: "Warpborn", visualKey: 'realm_classic_game_figure_humanoid_form_0195be5b' },
    { id: 'chaos_anointed', name: "Chaos Anointed", engineClass: 'warrior', faction: "Warpborn", visualKey: 'realm_classic_game_figure_satanic_beast_0195be54' },
    { id: 'rot_prophet', name: "Rot Prophet", engineClass: 'druid', faction: "Warpborn", visualKey: 'realm_arcane_all_seeing_sage_sage_019e1733' },
    { id: 'mind_render', name: "Mind Render", engineClass: 'mage', faction: "Warpborn", visualKey: 'realm_infernal_game_figure_albino_giant_0195be0e' },
    { id: 'plagueknight', name: "Plagueknight", engineClass: 'paladin', faction: "Warpborn", visualKey: 'realm_classic_mystic_elder_character_mystic_01983812' },
    { id: 'forge_adept', name: "Forge-Adept", engineClass: 'hunter', faction: "Forge Conclave", visualKey: 'realm_arcane_emberblade_crusader_crusader_emb_019f5e78' },
    { id: 'servo_warden', name: "Servo Warden", engineClass: 'warrior', faction: "Forge Conclave", visualKey: 'realm_arcane_eldritch_sentinel_characters_019737a4' },
    { id: 'arc_magus', name: "Arc Magus", engineClass: 'mage', faction: "Forge Conclave", visualKey: 'realm_classic_ethereal_guardian_fantasy_charac_01964ea8' },
    { id: 'cogpriest', name: "Cogpriest", engineClass: 'priest', faction: "Forge Conclave", visualKey: 'realm_classic_ethereal_warrior_characters_01972c65' },
    { id: 'void_purgator', name: "Void Purgator", engineClass: 'hunter', faction: "Forge Conclave", visualKey: 'realm_classic_game_figure_satanic_beast_0195b9a4' },
    { id: 'iron_ascetic', name: "Iron Ascetic", engineClass: 'rogue', faction: "Forge Conclave", visualKey: 'realm_arcane_weapon_glove_claws_similar_0194ad37' },
  ],
  dominion: [
    { id: 'marshal_warden', name: "Marshal Warden", engineClass: 'paladin', faction: "Crown Marshals", visualKey: 'realm_dominion_darth_vader_inspired_giger_01965dc9' },
    { id: 'pistol_duelist', name: "Pistol Duelist", engineClass: 'rogue', faction: "Crown Marshals", visualKey: 'realm_classic_bionic_ogre_mutation_sciencetech_0197790f' },
    { id: 'line_musketeer', name: "Line Musketeer", engineClass: 'hunter', faction: "Crown Marshals", visualKey: 'realm_dominion_urban_cyberpunk_explorer_charact_01942e81' },
    { id: 'court_physician', name: "Court Physician", engineClass: 'priest', faction: "Crown Marshals", visualKey: 'realm_infernal_elder_iron_skull_legion_0196872b' },
    { id: 'arcane_envoy', name: "Arcane Envoy", engineClass: 'mage', faction: "Crown Marshals", visualKey: 'realm_dominion_space_marine_characters_weaponsm_0193fb93' },
    { id: 'bastion_guard', name: "Bastion Guard", engineClass: 'warrior', faction: "Crown Marshals", visualKey: 'realm_infernal_bloodspike_behemoth_behemoth_blo_019f1b66' },
    { id: 'godcaller', name: "Godcaller", engineClass: 'mage', faction: "The Verdant", visualKey: 'realm_classic_cyborg_gorilla_warrior_cyborg_019ba55c' },
    { id: 'thornspeaker', name: "Thornspeaker", engineClass: 'druid', faction: "The Verdant", visualKey: 'realm_dominion_techno_goliath_sciencetechnology_01972cca' },
    { id: 'riven', name: "Riven", engineClass: 'warrior', faction: "The Verdant", visualKey: 'realm_classic_steel_guardian_characters_0193fbbb' },
    { id: 'grove_warden', name: "Grove Warden", engineClass: 'paladin', faction: "The Verdant", visualKey: 'realm_classic_cyborg_warrior_sciencetechnology_0196c06a' },
    { id: 'hollow_seer', name: "Hollow Seer", engineClass: 'priest', faction: "The Verdant", visualKey: 'realm_dominion_ork_mechanic_characters_0196014e' },
    { id: 'beast_marshal', name: "Beast Marshal", engineClass: 'hunter', faction: "The Verdant", visualKey: 'realm_dominion_titanous_fury_sciencetechnology_01967cc1' },
    { id: 'ranger_marshal', name: "Ranger-Marshal", engineClass: 'hunter', faction: "Freeholds", visualKey: 'realm_infernal_undead_rotten_machine_demon_0196c4f8' },
    { id: 'fieldwright', name: "Fieldwright", engineClass: 'hunter', faction: "Freeholds", visualKey: 'realm_infernal_demon_made_chrome_metal_0193da0a' },
    { id: 'blackpowder_rogue', name: "Blackpowder Rogue", engineClass: 'rogue', faction: "Freeholds", visualKey: 'realm_classic_cyberpunk_orc_adventurer_charact_019427db' },
    { id: 'hedge_binder', name: "Hedge Binder", engineClass: 'warlock', faction: "Freeholds", visualKey: 'realm_infernal_evil_warlord_armor_made_0196a11d' },
    { id: 'freehold_bravo', name: "Freehold Bravo", engineClass: 'warrior', faction: "Freeholds", visualKey: 'realm_classic_barbarian_iron_blade_barbarian_019f57b7' },
    { id: 'salt_preacher', name: "Salt Preacher", engineClass: 'priest', faction: "Freeholds", visualKey: 'realm_classic_troll_warrior_troll_warrior_019b705a' },
  ],
  arcadevoid: [
    { id: 'void_marine', name: "Void Marine", engineClass: 'warrior', faction: "Terran Compact", visualKey: 'realm_classic_ork_wizard_mage_dark_01967d8f' },
    { id: 'ghost_pilot', name: "Ghost Pilot", engineClass: 'rogue', faction: "Terran Compact", visualKey: 'realm_arcane_all_seeing_sage_sage_019e1733' },
    { id: 'turretwright', name: "Turretwright", engineClass: 'hunter', faction: "Terran Compact", visualKey: 'realm_infernal_infernal_sentinel_characters_01965e5c' },
    { id: 'firebrand', name: "Firebrand", engineClass: 'warrior', faction: "Terran Compact", visualKey: 'realm_classic_minotaur_warrior_minotaur_warrio_01987fdf' },
    { id: 'field_corpsman', name: "Field Corpsman", engineClass: 'priest', faction: "Terran Compact", visualKey: 'realm_classic_warrior_goblin_characters_weapon_01969227' },
    { id: 'siege_marshal', name: "Siege Marshal", engineClass: 'hunter', faction: "Terran Compact", visualKey: 'realm_infernal_black_dark_skin_demon_01938379' },
    { id: 'brood_render', name: "Brood Render", engineClass: 'rogue', faction: "Hive Swarm", visualKey: 'realm_classic_leyendary_troll_boss_evil_01989492' },
    { id: 'carapace_tyrant', name: "Carapace Tyrant", engineClass: 'warrior', faction: "Hive Swarm", visualKey: 'realm_infernal_nightmare_revenant_fantasy_skele_019498fe' },
    { id: 'spore_caller', name: "Spore Caller", engineClass: 'warlock', faction: "Hive Swarm", visualKey: 'realm_classic_twin_headed_guardian_characters_0196ee0a' },
    { id: 'hive_mender', name: "Hive Mender", engineClass: 'druid', faction: "Hive Swarm", visualKey: 'realm_infernal_legendary_demon_boss_evil_019894ab' },
    { id: 'zealot_ascendant', name: "Zealot Ascendant", engineClass: 'paladin', faction: "Luminate", visualKey: 'realm_classic_ethereal_guardian_characters_019691b3' },
    { id: 'high_seer', name: "High Seer", engineClass: 'mage', faction: "Luminate", visualKey: 'realm_classic_game_figure_humanoid_pig_0195b43b' },
    { id: 'phase_stalker', name: "Phase Stalker", engineClass: 'rogue', faction: "Luminate", visualKey: 'realm_classic_eldritch_guardian_characters_01969c78' },
    { id: 'lightbinder', name: "Lightbinder", engineClass: 'priest', faction: "Luminate", visualKey: 'realm_arcane_ethereal_sentinel_characters_0197372a' },
  ],
  crypticrealm: [
    { id: 'the_hollow_one', name: "The Hollow One", engineClass: 'warlock', faction: "The Unnamed", visualKey: 'realm_classic_alien_guardian_characters_01967cc9' },
    { id: 'maskbearer', name: "Maskbearer", engineClass: 'rogue', faction: "The Unnamed", visualKey: 'realm_classic_armored_guardian_characters_weap_0193fba5' },
    { id: 'silent_choir', name: "Silent Choir", engineClass: 'priest', faction: "The Unnamed", visualKey: 'realm_infernal_infernal_warrior_characters_0196c009' },
    { id: 'thresholder', name: "Thresholder", engineClass: 'mage', faction: "The Unnamed", visualKey: 'realm_fps_pirate_claus_characters_pirate_019b5321' },
    { id: 'the_tall_stranger', name: "The Tall Stranger", engineClass: 'warrior', faction: "The Unnamed", visualKey: 'realm_dominion_boss_exosuit_019e6f47' },
    { id: 'keeper_of_doors', name: "Keeper of Doors", engineClass: 'paladin', faction: "The Unnamed", visualKey: 'realm_dominion_cyber_pirate_overlord_characters_0196e657' },
    { id: 'cipherblade', name: "Cipherblade", engineClass: 'rogue', faction: "Wanderers", visualKey: 'realm_infernal_beastlord_abyss_villain_fantasy_019a5067' },
    { id: 'gravecaller', name: "Gravecaller", engineClass: 'warlock', faction: "Wanderers", visualKey: 'realm_classic_goblin_sentinel_characters_01964475' },
    { id: 'runewarden', name: "Runewarden", engineClass: 'warrior', faction: "Wanderers", visualKey: 'realm_classic_spiked_guardian_characters_01968220' },
    { id: 'oracle', name: "Oracle", engineClass: 'priest', faction: "Wanderers", visualKey: 'realm_classic_draconic_guardian_characters_019aa428' },
    { id: 'voidseer', name: "Voidseer", engineClass: 'mage', faction: "Wanderers", visualKey: 'realm_infernal_demon_lord_pose_no_0194c860' },
    { id: 'lantern_scout', name: "Lantern Scout", engineClass: 'hunter', faction: "Wanderers", visualKey: 'realm_classic_aztec_warrior_characters_culture_0194c237' },
  ],
};

export const REALM_FACTIONS: Record<string, readonly string[]> = {
  classic: ["Covenant", "Warhost"],
  infernal: ["Ashen Court", "Heavenly Host", "The Damned"],
  fps: ["Vanguard Company", "Iron Syndicate", "Freelancers"],
  arcane: ["The Aegis", "Warpborn", "Forge Conclave"],
  dominion: ["Crown Marshals", "The Verdant", "Freeholds"],
  arcadevoid: ["Terran Compact", "Hive Swarm", "Luminate"],
  crypticrealm: ["The Unnamed", "Wanderers"],
};
