// GENERATED FILE - DO NOT EDIT BY HAND.
// Produced by scripts/realm_assets/gen_rosters.mjs.
//
// Per-realm faction rosters in the shape infernal_classes.ts proved out:
// a name, the upstream class it plays as, a faction, and a body. Every entry is
// bound to a REAL body from that realm's generated pool, so all of them are
// already rigged, animated and weapon-socketed - adding a character costs a table
// row, not an asset run.
//
// Names are original. Genre targets are honoured without lifting protected names.

import type { PlayerClass } from '../types';

export interface RealmRosterEntry {
  id: string;
  name: string;
  /** Upstream class this character actually plays as. */
  engineClass: PlayerClass;
  faction: string;
  /** Key into VISUALS / GENERATED_VISUALS. */
  visualKey: string;
}

export const REALM_ROSTERS: Record<string, readonly RealmRosterEntry[]> = {
  classic: [
    { id: 'ironbrand_champion', name: "Ironbrand Champion", engineClass: 'warrior', faction: "Covenant", visualKey: 'realm_classic_alien_warrior_characters_01948641' },
    { id: 'silverwatch_templar', name: "Silverwatch Templar", engineClass: 'paladin', faction: "Covenant", visualKey: 'realm_classic_ancient_sentinel_019ab757' },
    { id: 'highglade_marksman', name: "Highglade Marksman", engineClass: 'hunter', faction: "Covenant", visualKey: 'realm_classic_orc_warlord_tattered_armor_019f13ab' },
    { id: 'duskveil_cutthroat', name: "Duskveil Cutthroat", engineClass: 'rogue', faction: "Covenant", visualKey: 'realm_classic_satanic_sorcerer_characters_0193e9cc' },
    { id: 'dawnkeeper', name: "Dawnkeeper", engineClass: 'priest', faction: "Covenant", visualKey: 'realm_classic_spiky_ogre_warrior_characters_01968731' },
    { id: 'runespire_adept', name: "Runespire Adept", engineClass: 'mage', faction: "Covenant", visualKey: 'realm_classic_troll_courtesy_fantasy_troll_019a166a' },
    { id: 'pactbinder', name: "Pactbinder", engineClass: 'warlock', faction: "Covenant", visualKey: 'realm_classic_punk_beast_characters_01982df3' },
    { id: 'greenmantle_warden', name: "Greenmantle Warden", engineClass: 'druid', faction: "Covenant", visualKey: 'realm_classic_dark_knight_sentinel_characters_01982d9f' },
    { id: 'stonehelm_vanguard', name: "Stonehelm Vanguard", engineClass: 'warrior', faction: "Covenant", visualKey: 'realm_classic_goblin_king_characters_01974bc8' },
    { id: 'lightforge_sentinel', name: "Lightforge Sentinel", engineClass: 'paladin', faction: "Covenant", visualKey: 'realm_classic_cave_warrior_01987b32' },
    { id: 'wyrmscout', name: "Wyrmscout", engineClass: 'hunter', faction: "Covenant", visualKey: 'realm_classic_warrior_goblin_characters_weapon_01969227' },
    { id: 'gloamblade', name: "Gloamblade", engineClass: 'rogue', faction: "Covenant", visualKey: 'realm_classic_goblin_sentinel_goblin_sentinel_019a5054' },
    { id: 'oathspeaker', name: "Oathspeaker", engineClass: 'priest', faction: "Covenant", visualKey: 'realm_classic_dwarven_warbeard_019d4441' },
    { id: 'frostquill_savant', name: "Frostquill Savant", engineClass: 'mage', faction: "Covenant", visualKey: 'realm_classic_doberman_humanoid_warrior_gamefi_0195c66a' },
    { id: 'bloodtusk_berserker', name: "Bloodtusk Berserker", engineClass: 'warrior', faction: "Warhost", visualKey: 'realm_classic_warrior_titan_characters_0196976a' },
    { id: 'emberfang_bulwark', name: "Emberfang Bulwark", engineClass: 'paladin', faction: "Warhost", visualKey: 'realm_classic_mage_wizard_dynamic_holding_0193e9c7' },
    { id: 'ashbow_stalker', name: "Ashbow Stalker", engineClass: 'hunter', faction: "Warhost", visualKey: 'realm_classic_low_poly_female_goblin_019581a0' },
    { id: 'nightfang_reaver', name: "Nightfang Reaver", engineClass: 'rogue', faction: "Warhost", visualKey: 'realm_classic_bald_skinny_male_wearing_01944c9a' },
    { id: 'spiritmender', name: "Spiritmender", engineClass: 'priest', faction: "Warhost", visualKey: 'realm_classic_orc_warrior_characters_weaponsmi_0196f86d' },
    { id: 'stormcaller', name: "Stormcaller", engineClass: 'mage', faction: "Warhost", visualKey: 'realm_classic_cyber_troll_sentinel_characters_019736e5' },
    { id: 'souldrinker', name: "Souldrinker", engineClass: 'warlock', faction: "Warhost", visualKey: 'realm_classic_orc_sentinel_characters_01968737' },
    { id: 'beastspeaker', name: "Beastspeaker", engineClass: 'druid', faction: "Warhost", visualKey: 'realm_classic_goblin_boss_head_warhost_01956cfa' },
    { id: 'ironjaw_warlord', name: "Ironjaw Warlord", engineClass: 'warrior', faction: "Warhost", visualKey: 'realm_classic_game_figure_satanic_beast_0195be18' },
    { id: 'sunscar_zealot', name: "Sunscar Zealot", engineClass: 'paladin', faction: "Warhost", visualKey: 'realm_classic_skullbound_orc_warlord_019e772d' },
    { id: 'boneshot_tracker', name: "Boneshot Tracker", engineClass: 'hunter', faction: "Warhost", visualKey: 'realm_classic_soccer_savior_019b65fb' },
    { id: 'shadowtooth', name: "Shadowtooth", engineClass: 'rogue', faction: "Warhost", visualKey: 'realm_classic_crimson_warlord_orc_019f5c6b' },
    { id: 'ancestor_voice', name: "Ancestor Voice", engineClass: 'priest', faction: "Warhost", visualKey: 'realm_classic_cyclopean_warrior_characters_war_019ac698' },
    { id: 'cindermage', name: "Cindermage", engineClass: 'mage', faction: "Warhost", visualKey: 'realm_classic_crimson_skullbound_warrior_019f5cbd' },
  ],
  infernal: [
    { id: 'fallen_inquisitor', name: "Fallen Inquisitor", engineClass: 'paladin', faction: "The Damned", visualKey: 'realm_infernal_deathcaller_warlock_characters_f_019b9937' },
    { id: 'blood_cardinal', name: "Blood Cardinal", engineClass: 'priest', faction: "The Damned", visualKey: 'realm_infernal_infernal_warlord_01944c9a' },
    { id: 'flesh_baron', name: "Flesh Baron", engineClass: 'warrior', faction: "The Damned", visualKey: 'realm_infernal_infernal_guardian_characters_0196ee84' },
    { id: 'plaguewright', name: "Plaguewright", engineClass: 'warlock', faction: "The Damned", visualKey: 'realm_infernal_monster_virus_evil_coronavirus_01989c27' },
    { id: 'gallows_marshal', name: "Gallows Marshal", engineClass: 'hunter', faction: "The Damned", visualKey: 'realm_infernal_infernal_titan_characters_01967790' },
    { id: 'skinbinder', name: "Skinbinder", engineClass: 'rogue', faction: "The Damned", visualKey: 'realm_infernal_towering_demon_overlord_stands_019442488bbe' },
    { id: 'horned_tyrant', name: "Horned Tyrant", engineClass: 'warrior', faction: "Ashen Court", visualKey: 'realm_infernal_cyber_skullbot_robot_skull_019bbd65' },
    { id: 'emberlord', name: "Emberlord", engineClass: 'mage', faction: "Ashen Court", visualKey: 'realm_infernal_infernal_majesty_villain_fantasy_019a51bf' },
    { id: 'soulflayer', name: "Soulflayer", engineClass: 'warlock', faction: "Ashen Court", visualKey: 'realm_infernal_muscular_demon_stands_crimson_019434db' },
    { id: 'pit_stalker', name: "Pit Stalker", engineClass: 'rogue', faction: "Ashen Court", visualKey: 'realm_infernal_necromancer_s_horde_fantasy_019b8b0e' },
    { id: 'brimstone_herald', name: "Brimstone Herald", engineClass: 'priest', faction: "Ashen Court", visualKey: 'realm_infernal_shadow_warrior_characters_01942cfa' },
    { id: 'abyssal_warden', name: "Abyssal Warden", engineClass: 'paladin', faction: "Ashen Court", visualKey: 'realm_infernal_infernal_guardian_characters_0196ee97' },
    { id: 'bone_legionnaire', name: "Bone Legionnaire", engineClass: 'warrior', faction: "The Damned", visualKey: 'realm_infernal_infernal_colossus_019bb7ec' },
    { id: 'grave_archer', name: "Grave Archer", engineClass: 'hunter', faction: "The Damned", visualKey: 'realm_infernal_necrotic_sentinel_necrotic_senti_019c082b' },
    { id: 'crypt_sovereign', name: "Crypt Sovereign", engineClass: 'warlock', faction: "The Damned", visualKey: 'realm_infernal_toxic_demon_characters_01961ff3' },
    { id: 'rotcaller', name: "Rotcaller", engineClass: 'druid', faction: "The Damned", visualKey: 'realm_infernal_necromancer_wrath_01966ed7' },
    { id: 'wight_sentinel', name: "Wight Sentinel", engineClass: 'paladin', faction: "The Damned", visualKey: 'realm_infernal_skullbound_warlord_character_fan_019cba58' },
    { id: 'shroud_assassin', name: "Shroud Assassin", engineClass: 'rogue', faction: "The Damned", visualKey: 'realm_infernal_infernal_guardian_characters_01964974' },
    { id: 'radiant_exarch', name: "Radiant Exarch", engineClass: 'paladin', faction: "Heavenly Host", visualKey: 'realm_infernal_infernal_sovereign_fantasy_chara_019a5459' },
    { id: 'seraph_lancer', name: "Seraph Lancer", engineClass: 'warrior', faction: "Heavenly Host", visualKey: 'realm_infernal_large_muscular_one_eyed_0195be1b' },
    { id: 'choir_warden', name: "Choir Warden", engineClass: 'priest', faction: "Heavenly Host", visualKey: 'realm_infernal_infernal_sentinel_characters_01965e5c' },
    { id: 'aureate_magus', name: "Aureate Magus", engineClass: 'mage', faction: "Heavenly Host", visualKey: 'realm_infernal_infernal_guardian_characters_01973194' },
    { id: 'judgement_bow', name: "Judgement Bow", engineClass: 'hunter', faction: "Heavenly Host", visualKey: 'realm_infernal_highly_muscular_albino_devil_0193e9c5' },
    { id: 'silent_blade', name: "Silent Blade", engineClass: 'rogue', faction: "Heavenly Host", visualKey: 'realm_infernal_legendary_demon_boss_evil_019894af' },
  ],
  fps: [
    { id: 'breacher', name: "Breacher", engineClass: 'warrior', faction: "Vanguard Company", visualKey: 'realm_fps_viking_culturehistory_01963f92' },
    { id: 'point_man', name: "Point Man", engineClass: 'warrior', faction: "Vanguard Company", visualKey: 'realm_fps_near_future_soldier_robust_01948e95' },
    { id: 'designated_marksman', name: "Designated Marksman", engineClass: 'hunter', faction: "Vanguard Company", visualKey: 'realm_fps_obese_mortal_combat_019538cf' },
    { id: 'overwatch', name: "Overwatch", engineClass: 'hunter', faction: "Vanguard Company", visualKey: 'realm_fps_obese_mortal_combat_019538ff' },
    { id: 'combat_medic', name: "Combat Medic", engineClass: 'priest', faction: "Vanguard Company", visualKey: 'realm_fps_design_featuring_figure_black_0193fb82' },
    { id: 'field_engineer', name: "Field Engineer", engineClass: 'hunter', faction: "Vanguard Company", visualKey: 'realm_fps_size_executioner_no_shirt_0193fba7' },
    { id: 'recon_scout', name: "Recon Scout", engineClass: 'rogue', faction: "Vanguard Company", visualKey: 'realm_fps_average_man_pose_game_01940dd0' },
    { id: 'demolitions', name: "Demolitions", engineClass: 'warrior', faction: "Vanguard Company", visualKey: 'realm_fps_warlord_sentinel_characters_019740a9' },
    { id: 'shield_bearer', name: "Shield Bearer", engineClass: 'paladin', faction: "Vanguard Company", visualKey: 'realm_fps_ninja_gaiden_pose_characters_01946143' },
    { id: 'comms_officer', name: "Comms Officer", engineClass: 'mage', faction: "Vanguard Company", visualKey: 'realm_fps_cave_man_but_he_01949df8' },
    { id: 'enforcer', name: "Enforcer", engineClass: 'warrior', faction: "Iron Syndicate", visualKey: 'realm_fps_fairy_viking_fairy_characters_0195e7cd' },
    { id: 'ghost_operative', name: "Ghost Operative", engineClass: 'rogue', faction: "Iron Syndicate", visualKey: 'realm_fps_cave_man_but_he_01949df7' },
    { id: 'longshot', name: "Longshot", engineClass: 'hunter', faction: "Iron Syndicate", visualKey: 'realm_fps_pirate_claus_characters_pirate_019b5321' },
    { id: 'saboteur', name: "Saboteur", engineClass: 'rogue', faction: "Iron Syndicate", visualKey: 'realm_fps_dark_warlord_characters_0195ed53' },
    { id: 'chem_trooper', name: "Chem Trooper", engineClass: 'warlock', faction: "Iron Syndicate", visualKey: 'realm_fps_cave_troll_power_armor_01943c49e8c1' },
    { id: 'heavy_gunner', name: "Heavy Gunner", engineClass: 'warrior', faction: "Iron Syndicate", visualKey: 'realm_fps_cave_man_but_he_01949e5b' },
    { id: 'drone_handler', name: "Drone Handler", engineClass: 'hunter', faction: "Iron Syndicate", visualKey: 'realm_fps_game_figure_viking_pose_0195a9f0' },
    { id: 'cutthroat', name: "Cutthroat", engineClass: 'rogue', faction: "Iron Syndicate", visualKey: 'realm_fps_agent_training_character_agent_019bb8c5' },
    { id: 'warden', name: "Warden", engineClass: 'paladin', faction: "Iron Syndicate", visualKey: 'realm_fps_cave_man_but_he_01949e02' },
    { id: 'signal_jammer', name: "Signal Jammer", engineClass: 'mage', faction: "Iron Syndicate", visualKey: 'realm_fps_majestic_armored_dragon_01991345' },
    { id: 'bounty_runner', name: "Bounty Runner", engineClass: 'rogue', faction: "Freelancers", visualKey: 'realm_fps_battle_scarred_ogre_019aac86' },
    { id: 'scrapjack', name: "Scrapjack", engineClass: 'hunter', faction: "Freelancers", visualKey: 'realm_fps_game_figure_viking_pose_0195b121' },
    { id: 'street_doc', name: "Street Doc", engineClass: 'priest', faction: "Freelancers", visualKey: 'realm_fps_evil_goblin_warlord_armor_0196a156' },
    { id: 'pit_brawler', name: "Pit Brawler", engineClass: 'warrior', faction: "Freelancers", visualKey: 'realm_fps_average_man_pose_game_01940dea' },
    { id: 'wildcard', name: "Wildcard", engineClass: 'rogue', faction: "Freelancers", visualKey: 'realm_fps_beautiful_female_viking_characte_019412e9' },
    { id: 'gunsmith', name: "Gunsmith", engineClass: 'hunter', faction: "Freelancers", visualKey: 'realm_fps_dark_warlord_ork_characters_0195f1b9' },
    { id: 'juggernaut', name: "Juggernaut", engineClass: 'warrior', faction: "Freelancers", visualKey: 'realm_fps_dark_warlord_characters_weaponsm_0197c14c' },
    { id: 'trickshot', name: "Trickshot", engineClass: 'hunter', faction: "Freelancers", visualKey: 'realm_fps_warlord_sentinel_characters_019740c5' },
  ],
  arcane: [
    { id: 'aegis_templar', name: "Aegis Templar", engineClass: 'paladin', faction: "The Aegis", visualKey: 'realm_arcane_ethereal_guardian_01946222' },
    { id: 'bulwark_sergeant', name: "Bulwark Sergeant", engineClass: 'warrior', faction: "The Aegis", visualKey: 'realm_arcane_masterpiece_lowpoly_mysterious_mystical_019576c6' },
    { id: 'purgation_marshal', name: "Purgation Marshal", engineClass: 'hunter', faction: "The Aegis", visualKey: 'realm_arcane_game_figure_albino_giant_0195b9a2' },
    { id: 'confessor', name: "Confessor", engineClass: 'priest', faction: "The Aegis", visualKey: 'realm_arcane_emberblade_crusader_crusader_emb_019f5e78' },
    { id: 'sanctioned_warpseer', name: "Sanctioned Warpseer", engineClass: 'mage', faction: "The Aegis", visualKey: 'realm_arcane_mystic_goblin_elder_bright_01983812' },
    { id: 'vigil_sister', name: "Vigil Sister", engineClass: 'paladin', faction: "The Aegis", visualKey: 'realm_arcane_celestial_conjuror_019eb709' },
    { id: 'interdictor', name: "Interdictor", engineClass: 'rogue', faction: "The Aegis", visualKey: 'realm_arcane_game_figure_albino_giant_0195b9b1' },
    { id: 'relic_bearer', name: "Relic Bearer", engineClass: 'priest', faction: "The Aegis", visualKey: 'realm_arcane_crystal_titan_pbr_crystal_0198e7fd' },
    { id: 'warp_herald', name: "Warp Herald", engineClass: 'warlock', faction: "Warpborn", visualKey: 'realm_arcane_fantasy_old_dragon_mage_019542bf' },
    { id: 'riftblade', name: "Riftblade", engineClass: 'rogue', faction: "Warpborn", visualKey: 'realm_arcane_festive_christmas_gnome_albino_01939734' },
    { id: 'chaos_anointed', name: "Chaos Anointed", engineClass: 'warrior', faction: "Warpborn", visualKey: 'realm_arcane_fantasy_evil_wizard_visionary_019833b8' },
    { id: 'rot_prophet', name: "Rot Prophet", engineClass: 'druid', faction: "Warpborn", visualKey: 'realm_arcane_fantasy_evil_wizard_visionary_0198334a' },
    { id: 'mind_render', name: "Mind Render", engineClass: 'mage', faction: "Warpborn", visualKey: 'realm_arcane_ethereal_guardian_01946226' },
    { id: 'plagueknight', name: "Plagueknight", engineClass: 'paladin', faction: "Warpborn", visualKey: 'realm_arcane_festive_christmas_gnome_albino_01939752' },
    { id: 'forge_adept', name: "Forge-Adept", engineClass: 'hunter', faction: "Forge Conclave", visualKey: 'realm_arcane_ethereal_guardian_0194666a' },
    { id: 'servo_warden', name: "Servo Warden", engineClass: 'warrior', faction: "Forge Conclave", visualKey: 'realm_arcane_shaman_s_spirit_keeper_01963bb3' },
    { id: 'arc_magus', name: "Arc Magus", engineClass: 'mage', faction: "Forge Conclave", visualKey: 'realm_arcane_ethereal_sentinel_characters_0195fc71' },
    { id: 'cogpriest', name: "Cogpriest", engineClass: 'priest', faction: "Forge Conclave", visualKey: 'realm_arcane_ethereal_guardian_01946212' },
    { id: 'void_purgator', name: "Void Purgator", engineClass: 'hunter', faction: "Forge Conclave", visualKey: 'realm_arcane_mystic_sentinel_characters_01968757' },
    { id: 'iron_ascetic', name: "Iron Ascetic", engineClass: 'rogue', faction: "Forge Conclave", visualKey: 'realm_arcane_ethereal_guardian_0194622a' },
  ],
  dominion: [
    { id: 'marshal_warden', name: "Marshal Warden", engineClass: 'paladin', faction: "Crown Marshals", visualKey: 'realm_dominion_techno_goliath_sciencetechnology_01972cca' },
    { id: 'pistol_duelist', name: "Pistol Duelist", engineClass: 'rogue', faction: "Crown Marshals", visualKey: 'realm_dominion_golem_made_trash_characters_01945b7c' },
    { id: 'line_musketeer', name: "Line Musketeer", engineClass: 'hunter', faction: "Crown Marshals", visualKey: 'realm_dominion_alien_punk_rebel_characters_0195d98d' },
    { id: 'court_physician', name: "Court Physician", engineClass: 'priest', faction: "Crown Marshals", visualKey: 'realm_dominion_titanous_fury_sciencetechnology_01967cc1' },
    { id: 'arcane_envoy', name: "Arcane Envoy", engineClass: 'mage', faction: "Crown Marshals", visualKey: 'realm_dominion_dark_iron_sentinel_characters_01983fa1' },
    { id: 'bastion_guard', name: "Bastion Guard", engineClass: 'warrior', faction: "Crown Marshals", visualKey: 'realm_dominion_cyber_buccaneer_characters_01964459' },
    { id: 'godcaller', name: "Godcaller", engineClass: 'mage', faction: "The Verdant", visualKey: 'realm_dominion_empress_circuits_empress_circuit_019eacec' },
    { id: 'thornspeaker', name: "Thornspeaker", engineClass: 'druid', faction: "The Verdant", visualKey: 'realm_dominion_cyber_pirate_overlord_characters_0196e657' },
    { id: 'riven', name: "Riven", engineClass: 'warrior', faction: "The Verdant", visualKey: 'realm_dominion_titanium_sentinel_sciencetechnol_01965431' },
    { id: 'grove_warden', name: "Grove Warden", engineClass: 'paladin', faction: "The Verdant", visualKey: 'realm_dominion_cybernetic_sentinel_sciencetechn_01974bc6' },
    { id: 'hollow_seer', name: "Hollow Seer", engineClass: 'priest', faction: "The Verdant", visualKey: 'realm_dominion_urban_mech_drifter_characters_0196cf3f' },
    { id: 'beast_marshal', name: "Beast Marshal", engineClass: 'hunter', faction: "The Verdant", visualKey: 'realm_dominion_fantasy_underground_cyborg_monst_01968d4c' },
    { id: 'ranger_marshal', name: "Ranger-Marshal", engineClass: 'hunter', faction: "Freeholds", visualKey: 'realm_dominion_centient_robot_muscular_nano_01944875' },
    { id: 'fieldwright', name: "Fieldwright", engineClass: 'hunter', faction: "Freeholds", visualKey: 'realm_dominion_eternal_automaton_robot_automato_019bb8d9' },
    { id: 'blackpowder_rogue', name: "Blackpowder Rogue", engineClass: 'rogue', faction: "Freeholds", visualKey: 'realm_dominion_rusted_metal_golem_monster_01967d88' },
    { id: 'hedge_binder', name: "Hedge Binder", engineClass: 'warlock', faction: "Freeholds", visualKey: 'realm_dominion_alien_warlord_characters_019691b8' },
    { id: 'freehold_bravo', name: "Freehold Bravo", engineClass: 'warrior', faction: "Freeholds", visualKey: 'realm_dominion_cyber_skater_phantom_characters_0196de3c' },
    { id: 'salt_preacher', name: "Salt Preacher", engineClass: 'priest', faction: "Freeholds", visualKey: 'realm_dominion_iron_sentinel_characters_weapons_0194666f' },
  ],
  arcadevoid: [
    { id: 'void_marine', name: "Void Marine", engineClass: 'warrior', faction: "Terran Compact", visualKey: 'realm_dominion_cyber_wanderer_characters_scienc_0196e689' },
    { id: 'ghost_pilot', name: "Ghost Pilot", engineClass: 'rogue', faction: "Terran Compact", visualKey: 'realm_fps_hulking_ogre_towers_brutish_0193885f' },
    { id: 'turretwright', name: "Turretwright", engineClass: 'hunter', faction: "Terran Compact", visualKey: 'realm_classic_twin_headed_warbrute_fantasy_019c7bd6' },
    { id: 'firebrand', name: "Firebrand", engineClass: 'warrior', faction: "Terran Compact", visualKey: 'realm_infernal_hunched_creature_elongated_lumpy_01955cec' },
    { id: 'field_corpsman', name: "Field Corpsman", engineClass: 'priest', faction: "Terran Compact", visualKey: 'realm_infernal_infernal_majesty_characters_0196444c' },
    { id: 'siege_marshal', name: "Siege Marshal", engineClass: 'hunter', faction: "Terran Compact", visualKey: 'realm_classic_cyclopean_warrior_giant_warrior_019ac6ac' },
    { id: 'brood_render', name: "Brood Render", engineClass: 'rogue', faction: "Hive Swarm", visualKey: 'realm_classic_alien_empress_01945791' },
    { id: 'carapace_tyrant', name: "Carapace Tyrant", engineClass: 'warrior', faction: "Hive Swarm", visualKey: 'realm_classic_orc_sentinel_characters_0196873a' },
    { id: 'spore_caller', name: "Spore Caller", engineClass: 'warlock', faction: "Hive Swarm", visualKey: 'realm_infernal_infernal_sentinel_characters_0196d448' },
    { id: 'hive_mender', name: "Hive Mender", engineClass: 'druid', faction: "Hive Swarm", visualKey: 'realm_classic_perfect_rig_symmetrical_01945b0c' },
    { id: 'zealot_ascendant', name: "Zealot Ascendant", engineClass: 'paladin', faction: "Luminate", visualKey: 'realm_classic_old_kung_fu_master_0193e4a6' },
    { id: 'high_seer', name: "High Seer", engineClass: 'mage', faction: "Luminate", visualKey: 'realm_infernal_bifrost_beast_01983026' },
    { id: 'phase_stalker', name: "Phase Stalker", engineClass: 'rogue', faction: "Luminate", visualKey: 'realm_classic_ravenbound_goblin_019deb9b' },
    { id: 'lightbinder', name: "Lightbinder", engineClass: 'priest', faction: "Luminate", visualKey: 'realm_classic_skinny_mma_fighter_wearing_0193daaa' },
  ],
  crypticrealm: [
    { id: 'the_hollow_one', name: "The Hollow One", engineClass: 'warlock', faction: "The Unnamed", visualKey: 'realm_classic_middle_age_guy_beard_01942e82' },
    { id: 'maskbearer', name: "Maskbearer", engineClass: 'rogue', faction: "The Unnamed", visualKey: 'realm_classic_dark_wanderer_0196874d' },
    { id: 'silent_choir', name: "Silent Choir", engineClass: 'priest', faction: "The Unnamed", visualKey: 'realm_classic_dual_head_warrior_future_0196b630' },
    { id: 'thresholder', name: "Thresholder", engineClass: 'mage', faction: "The Unnamed", visualKey: 'realm_classic_black_skin_race_ogre_0194f7f5' },
    { id: 'the_tall_stranger', name: "The Tall Stranger", engineClass: 'warrior', faction: "The Unnamed", visualKey: 'realm_classic_game_figure_satanic_beast_0195be0a' },
    { id: 'keeper_of_doors', name: "Keeper of Doors", engineClass: 'paladin', faction: "The Unnamed", visualKey: 'realm_classic_cyborg_warrior_extra_arms_0196bcef' },
    { id: 'cipherblade', name: "Cipherblade", engineClass: 'rogue', faction: "Wanderers", visualKey: 'realm_infernal_infernal_sentinel_characters_01974be2' },
    { id: 'gravecaller', name: "Gravecaller", engineClass: 'warlock', faction: "Wanderers", visualKey: 'realm_dominion_cybernetic_heavyweight_sciencete_0196fd7f' },
    { id: 'runewarden', name: "Runewarden", engineClass: 'warrior', faction: "Wanderers", visualKey: 'realm_classic_cyclopean_warlord_fantasy_charac_019d5f16' },
    { id: 'oracle', name: "Oracle", engineClass: 'priest', faction: "Wanderers", visualKey: 'realm_classic_goblin_king_ogre_guardian_019ac153' },
    { id: 'voidseer', name: "Voidseer", engineClass: 'mage', faction: "Wanderers", visualKey: 'realm_classic_robust_humanoid_figure_stocky_01938331' },
    { id: 'lantern_scout', name: "Lantern Scout", engineClass: 'hunter', faction: "Wanderers", visualKey: 'realm_classic_golem_guardian_golem_guardian_019bb8dc' },
  ],
};

export const REALM_FACTIONS: Record<string, readonly string[]> = {
  classic: ["Covenant", "Warhost"],
  infernal: ["Ashen Court", "Heavenly Host", "The Damned"],
  fps: ["Vanguard Company", "Iron Syndicate", "Freelancers"],
  arcane: ["The Aegis", "Warpborn", "Forge Conclave"],
  dominion: ["Crown Marshals", "The Verdant", "Freeholds"],
  arcadevoid: ["Terran Compact", "Hive Swarm", "Luminate"],
  crypticrealm: ["The Unnamed", "Wanderers"],
};
