import type { MobTemplate } from '../../types';

export const DELVE_MOBS: Record<string, MobTemplate> = {
  // --- Trash ---
  reliquary_ledger_wraith: {
    id: 'reliquary_ledger_wraith',
    name: 'Ledger Wraith',
    minLevel: 7,
    maxLevel: 8,
    family: 'undead',
    hpBase: 30,
    hpPerLevel: 10,
    dmgBase: 4,
    dmgPerLevel: 1.3,
    attackSpeed: 1.9,
    armorPerLevel: 5,
    moveSpeed: 7.5,
    aggroRadius: 16,
    // Stacks corrode fast due to quick attacks; fragile once reached
    corrode: { chance: 0.45, armor: 6, maxStacks: 4, duration: 12, name: 'Ledger Rot' },
    loot: [{ copper: 6, chance: 1 }],
    scale: 0.85,
    color: 0x9ba8a0,
  },
  reliquary_funeral_ringer: {
    id: 'reliquary_funeral_ringer',
    name: 'Funeral Ringer',
    minLevel: 7,
    maxLevel: 8,
    family: 'undead',
    hpBase: 38,
    hpPerLevel: 13,
    dmgBase: 5,
    dmgPerLevel: 1.5,
    attackSpeed: 2.3,
    armorPerLevel: 8,
    moveSpeed: 6,
    aggroRadius: 11,
    // Periodic AoE chime; when killed it empowers nearby Ringers, mind kill order
    aoePulse: { min: 5, max: 9, radius: 6, every: 4, name: 'Funeral Chime' },
    packFrenzy: { radius: 10, hasteMult: 1.3, duration: 6 },
    loot: [{ copper: 8, chance: 1 }],
    scale: 1.0,
    color: 0x8a8070,
  },
  reliquary_gravecall_acolyte: {
    id: 'reliquary_gravecall_acolyte',
    name: 'Gravecall Acolyte',
    minLevel: 7,
    maxLevel: 8,
    family: 'humanoid',
    hpBase: 42,
    hpPerLevel: 14,
    dmgBase: 5,
    dmgPerLevel: 1.4,
    attackSpeed: 2.5,
    armorPerLevel: 7,
    moveSpeed: 7,
    aggroRadius: 10,
    // Healing received cut 35% per hit, kills Tessa's effectiveness if ignored
    mortalStrike: { chance: 0.4, healReduction: 0.35, duration: 8, name: 'Grave Hex' },
    loot: [{ copper: 10, chance: 1 }],
    scale: 1.0,
    color: 0x4a3828,
  },
  // Weak undead add summoned by the `restless_graves` Heroic affix a few seconds
  // after a piece of trash dies. Deliberately frail, it's bonus pressure, not a
  // planned pull. (Do not reuse the lvl-18 dungeon `raised_bonewalker`.)
  reliquary_bonewalker: {
    id: 'reliquary_bonewalker',
    name: 'Raised Bonewalker',
    minLevel: 7,
    maxLevel: 8,
    family: 'undead',
    hpBase: 20,
    hpPerLevel: 7,
    dmgBase: 3,
    dmgPerLevel: 1.1,
    attackSpeed: 2.2,
    armorPerLevel: 4,
    moveSpeed: 7,
    aggroRadius: 12,
    loot: [{ copper: 3, chance: 1 }],
    scale: 0.8,
    color: 0xb9b2a4,
  },
  reliquary_saintless_effigy: {
    id: 'reliquary_saintless_effigy',
    name: 'Saintless Effigy',
    minLevel: 8,
    maxLevel: 8,
    family: 'undead',
    elite: true,
    ccImmune: true,
    hpBase: 72,
    hpPerLevel: 24,
    dmgBase: 10,
    dmgPerLevel: 2.5,
    attackSpeed: 2.9,
    armorPerLevel: 18,
    moveSpeed: 5,
    aggroRadius: 9,
    // Slow, can't be CC'd, cleaves anyone standing adjacent, tank it solo
    cleave: { radius: 3.5, mult: 0.6, name: 'Stone Sweep' },
    loot: [{ copper: 60, chance: 1 }],
    scale: 1.25,
    color: 0xc8beb0,
  },

  // --- Boss ---
  deacon_varric: {
    id: 'deacon_varric',
    name: 'Deacon Varric',
    minLevel: 9,
    maxLevel: 9,
    family: 'undead',
    elite: true,
    boss: true,
    hpBase: 100,
    hpPerLevel: 22,
    dmgBase: 8,
    dmgPerLevel: 2.4,
    attackSpeed: 2.2,
    armorPerLevel: 20,
    moveSpeed: 7,
    aggroRadius: 14,
    stomp: { radius: 8, every: 12, duration: 1.5, min: 14, max: 22, name: 'Bell Toll' },
    summonAdds: { mobId: 'reliquary_funeral_ringer', count: 2, atHpPct: [0.6, 0.3] },
    enrage: { belowHpPct: 0.2, dmgMult: 1.4, hasteMult: 1.2 },
    loot: [{ copper: 320, chance: 1 }],
    scale: 1.6,
    color: 0x7b7d7d,
  },

  // --- Durance of Hate (Diabl0 Easter-egg delve) ---
  // Fast fragile rushers: swarm the descent, stack up on the tank quickly.
  durance_hateful_husk: {
    id: 'durance_hateful_husk',
    name: 'Hateful Husk',
    minLevel: 10,
    maxLevel: 11,
    family: 'undead',
    hpBase: 42,
    hpPerLevel: 12,
    dmgBase: 6,
    dmgPerLevel: 1.6,
    attackSpeed: 1.8,
    armorPerLevel: 6,
    moveSpeed: 8,
    aggroRadius: 17,
    corrode: { chance: 0.4, armor: 7, maxStacks: 4, duration: 12, name: 'Hate Rot' },
    loot: [{ copper: 8, chance: 1 }],
    scale: 0.9,
    color: 0x6e2c2c,
  },
  // Ranged brand-caster: sigil pulses hurt at range; close and kill first.
  durance_sigilbound_acolyte: {
    id: 'durance_sigilbound_acolyte',
    name: 'Sigil-Bound Acolyte',
    minLevel: 10,
    maxLevel: 11,
    family: 'humanoid',
    hpBase: 50,
    hpPerLevel: 15,
    dmgBase: 7,
    dmgPerLevel: 1.9,
    attackSpeed: 2.4,
    armorPerLevel: 9,
    moveSpeed: 6,
    aggroRadius: 13,
    aoePulse: { min: 6, max: 11, radius: 6, every: 4, name: 'Sigil Brand' },
    loot: [{ copper: 10, chance: 1 }],
    scale: 1.0,
    color: 0x8a1c2a,
  },
  // Mini-anchor: ccImmune cleaver that guards the deep gallery; tank alone.
  durance_blood_behemoth: {
    id: 'durance_blood_behemoth',
    name: 'Blood Behemoth',
    minLevel: 11,
    maxLevel: 12,
    family: 'demon',
    elite: true,
    hpBase: 90,
    hpPerLevel: 20,
    dmgBase: 9,
    dmgPerLevel: 2.2,
    attackSpeed: 2.6,
    armorPerLevel: 16,
    moveSpeed: 6.5,
    aggroRadius: 12,
    stomp: { radius: 7, every: 10, duration: 1.4, min: 12, max: 20, name: 'Crushing Wrath' },
    loot: [{ copper: 120, chance: 1 }],
    scale: 1.5,
    color: 0x4a1418,
  },
  // --- Boss ---
  durance_hatelord_baelgor: {
    id: 'durance_hatelord_baelgor',
    name: 'Baelgor, Hatelord of the Durance',
    minLevel: 12,
    maxLevel: 12,
    family: 'demon',
    elite: true,
    boss: true,
    hpBase: 140,
    hpPerLevel: 26,
    dmgBase: 11,
    dmgPerLevel: 2.8,
    attackSpeed: 2.2,
    armorPerLevel: 22,
    moveSpeed: 7,
    aggroRadius: 15,
    stomp: { radius: 9, every: 11, duration: 1.6, min: 18, max: 28, name: 'Wave of Hate' },
    summonAdds: { mobId: 'durance_hateful_husk', count: 3, atHpPct: [0.6, 0.3] },
    enrage: { belowHpPct: 0.2, dmgMult: 1.5, hasteMult: 1.25 },
    loot: [
      { copper: 800, chance: 1 },
      // One signature epic per archetype, exclusive roll — every clear has a
      // real shot at a Durance trophy.
      { itemId: 'baelgors_hateforged_cleaver', chance: 0.34, rollGroup: 'baelgor_epic' },
      { itemId: 'sigilbrand_of_the_durance', chance: 0.33, rollGroup: 'baelgor_epic' },
      { itemId: 'hollow_fang_of_hate', chance: 0.33, rollGroup: 'baelgor_epic' },
    ],
    scale: 1.8,
    color: 0x9a1f26,
  },

  // --- Companion (friendly, no loot) ---
  acolyte_tessa: {
    id: 'acolyte_tessa',
    name: 'Acolyte Tessa',
    minLevel: 8,
    maxLevel: 8,
    family: 'humanoid',
    hpBase: 55,
    hpPerLevel: 16,
    dmgBase: 4,
    dmgPerLevel: 1.2,
    attackSpeed: 2.6,
    armorPerLevel: 8,
    moveSpeed: 7,
    aggroRadius: 0,
    loot: [],
    scale: 1.0,
    color: 0xebedef,
  },
};
