#!/usr/bin/env python3
"""Resolve package.json and .gitattributes in the one-jump merge.

Both block every downstream tool: esbuild/vite read package.json, and a
conflicted .gitattributes makes git warn on every command.

.gitattributes: our deploy-critical `eol=lf` rules must survive (CRLF breaks
shebangs and systemd units on the Linux host). Upstream's comment rewording and
its new translation_keys.generated.ts linguist rule are taken on top.

package.json: fork name/version convention wins (`<upstream>-cr.N` -> 0.30.0-cr.1);
the build script is a union so upstream's sfx:manifest and our realm-asset step
both run; dependency versions follow upstream because package-lock is upstream's.
"""
import io
import sys

REPO = "/opt/cr-measure/"

GA_OLD = """<<<<<<< HEAD
# Deploy-critical files MUST stay LF — CRLF breaks shebangs and systemd units on
# the Linux host (`#!/usr/bin/env bash^M: no such file or directory`).
*.sh        text eol=lf
*.mjs       text eol=lf
*.service   text eol=lf
*.timer     text eol=lf
*.target    text eol=lf
scripts/**  text eol=lf
deploy/**   text eol=lf
*.mp3 binary
# Generated dense i18n resolved tables. These directories STAY committed (they are
# the tsc safety net + the runtime read source), but each is a large machine-emitted
# artifact regenerated by `npm run i18n:build` / `npm run i18n:admin`. Marking them
# `linguist-generated` makes GitHub collapse them in pull-request diffs and excludes
# them from language statistics. Display hygiene only - not removal, not gitignore.
src/ui/i18n.resolved.generated/** linguist-generated
src/admin/i18n.resolved.generated/** linguist-generated
.browserslistrc text eol=lf
=======
# Generated dense i18n resolved tables, plus the flat TranslationKey union emitted
# by the same build. These STAY committed (they are the tsc safety net + the runtime
# read source), but each is a machine-emitted artifact regenerated by
# `npm run i18n:build` / `npm run i18n:admin`. Marking them `linguist-generated`
# makes GitHub collapse them in pull-request diffs and excludes them from language
# statistics. Display hygiene only - not removal, not gitignore.
src/ui/i18n.resolved.generated/** linguist-generated
src/admin/i18n.resolved.generated/** linguist-generated
src/ui/i18n.catalog/translation_keys.generated.ts linguist-generated
>>>>>>> upstream/main
"""

GA_NEW = """# Deploy-critical files MUST stay LF — CRLF breaks shebangs and systemd units on
# the Linux host (`#!/usr/bin/env bash^M: no such file or directory`).
*.sh        text eol=lf
*.mjs       text eol=lf
*.service   text eol=lf
*.timer     text eol=lf
*.target    text eol=lf
scripts/**  text eol=lf
deploy/**   text eol=lf
*.mp3 binary
# Generated dense i18n resolved tables, plus the flat TranslationKey union emitted
# by the same build. These STAY committed (they are the tsc safety net + the runtime
# read source), but each is a machine-emitted artifact regenerated by
# `npm run i18n:build` / `npm run i18n:admin`. Marking them `linguist-generated`
# makes GitHub collapse them in pull-request diffs and excludes them from language
# statistics. Display hygiene only - not removal, not gitignore.
src/ui/i18n.resolved.generated/** linguist-generated
src/admin/i18n.resolved.generated/** linguist-generated
src/ui/i18n.catalog/translation_keys.generated.ts linguist-generated
.browserslistrc text eol=lf
"""

PJ = [
    (
        """<<<<<<< HEAD
  "name": "cryptic-realm",
  "version": "0.24.0-cr.1",
=======
  "name": "world-of-claudecraft",
  "version": "0.30.0",
>>>>>>> upstream/main
""",
        """  "name": "cryptic-realm",
  "version": "0.30.0-cr.1",
""",
    ),
    (
        """<<<<<<< HEAD
    "build": "npm run i18n:build && npm run i18n:admin && npm run i18n:scan && npm run wiki:content && npm run sitemap:build && npm run assets:realms -- --skip-api && node scripts/build_media_manifest.mjs generate && vite build && node scripts/check_backdrop_survival.mjs && node scripts/build_media_manifest.mjs emit",
    "assets:realms": "node scripts/build_realm_assets.mjs",
    "assets:infernal-rigs": "node scripts/build_infernal_human_rigs.mjs",
    "assets:infernal-waypoint": "node scripts/build_infernal_waypoint.mjs",
=======
    "build": "npm run i18n:build && npm run i18n:admin && npm run i18n:scan && npm run wiki:content && npm run sitemap:build && npm run sfx:manifest && node scripts/build_media_manifest.mjs generate && vite build && node scripts/check_backdrop_survival.mjs && node scripts/build_media_manifest.mjs emit",
>>>>>>> upstream/main
""",
        """    "build": "npm run i18n:build && npm run i18n:admin && npm run i18n:scan && npm run wiki:content && npm run sitemap:build && npm run sfx:manifest && npm run assets:realms -- --skip-api && node scripts/build_media_manifest.mjs generate && vite build && node scripts/check_backdrop_survival.mjs && node scripts/build_media_manifest.mjs emit",
    "assets:realms": "node scripts/build_realm_assets.mjs",
    "assets:infernal-rigs": "node scripts/build_infernal_human_rigs.mjs",
    "assets:infernal-waypoint": "node scripts/build_infernal_waypoint.mjs",
""",
    ),
    (
        """<<<<<<< HEAD
    "@vitejs/plugin-react": "^6.0.3",
    "@vitest/browser": "4.1.8",
    "@vitest/browser-playwright": "4.1.8",
=======
    "@typescript/native": "npm:typescript@^7.0.2",
    "@vitest/browser": "4.1.10",
    "@vitest/browser-playwright": "4.1.10",
>>>>>>> upstream/main
""",
        """    "@typescript/native": "npm:typescript@^7.0.2",
    "@vitejs/plugin-react": "^6.0.3",
    "@vitest/browser": "4.1.10",
    "@vitest/browser-playwright": "4.1.10",
""",
    ),
]

fails = []

p = REPO + ".gitattributes"
s = io.open(p, encoding="utf-8").read()
if GA_OLD in s:
    io.open(p, "w", encoding="utf-8", newline="\n").write(s.replace(GA_OLD, GA_NEW, 1))
    print(".gitattributes resolved")
else:
    fails.append(".gitattributes")

p = REPO + "package.json"
s = io.open(p, encoding="utf-8").read()
for old, new in PJ:
    if old in s:
        s = s.replace(old, new, 1)
    else:
        fails.append("package.json hunk")
io.open(p, "w", encoding="utf-8", newline="\n").write(s)
print("package.json remaining markers: %d" % s.count("<<<<<<<"))

if fails:
    print("FAILED: %s" % fails)
    sys.exit(1)
