// Server-owned mirror of src/render/props.ts. The parity test catches additions without
// importing browser/render code into the authoritative server bundle.
const NATIVE_PROP_KEYS = new Set([
  'Binary file (standard input) matches',
  'anvil',
  'barrel',
  'bellTower',
  'blacksmith',
  'bonfire',
  'cart',
  'column',
  'columnBroken',
  'courseArch',
  'crateWooden',
  'crystalAmethystCluster',
  'crystalMoundCave',
  'delveEntrance2',
  'dockPlatform',
  'farmCrate',
  'fence',
  'flowerBedRound',
  'flowerBedSquareA',
  'flowerBedSquareB',
  'flowerGlow',
  'gardenArch',
  'gardenIronFence',
  'gardenIronGate',
  'gardenIronPillar',
  'goldenHorseStatue',
  'graveBevel',
  'graveCross',
  'graveDecor',
  'graveRound',
  'hexAnchor',
  'hexBarracks',
  'hexBarrel',
  'hexBlacksmith',
  'hexBoat',
  'hexBoatrack',
  'hexCannon',
  'hexCannonTower',
  'hexCannonballs',
  'hexCastle',
  'hexChurch',
  'hexCrateBig',
  'hexCrateOpen',
  'hexFenceStone',
  'hexFlag',
  'hexFlagRed',
  'hexHaybale',
  'hexHomeA',
  'hexHomeB',
  'hexLumber',
  'hexMarket',
  'hexSack',
  'hexShipBlue',
  'hexShipGreen',
  'hexShipRed',
  'hexTarget',
  'hexTavern',
  'hexTower',
  'hexTrough',
  'hexWall',
  'hexWatchtower',
  'hexWeaponRack',
  'hexWheelbarrow',
  'hexWindmill',
  'hexbHomeA',
  'hexbHomeB',
  'hexbMarket',
  'hexbShipyard',
  'hexbStables',
  'hexbTavern',
  'hexbTowerA',
  'hexbTowerB',
  'hexbTowerBase',
  'hexbTownhall',
  'hexbWindmill',
  'hexbWorkshop',
  'hexnPalisade',
  'hexrArcheryrange',
  'hexrBarracks',
  'hexrBlacksmith',
  'hexrCastle',
  'hexrChurch',
  'hexrHomeA',
  'hexrHomeB',
  'hexrMarket',
  'hexrStables',
  'hexrTavern',
  'hexrTent',
  'hexrTowerA',
  'hexrTowerBase2',
  'hexrTowerCatapult',
  'hexrTownhall',
  'hexrWatchtower',
  'hexrWindmill',
  'house1',
  'house2',
  'house3',
  'inn',
  'jumpOxer',
  'jumpVertical',
  'kcasBannerRedA',
  'kcasBannerRedShield',
  'kcasBannerRedTriple',
  'kcasBarA',
  'kcasBarB',
  'kcasBarC',
  'kcasBarrel',
  'kcasBarrier',
  'kcasBarrierCorner',
  'kcasBarrierHalf',
  'kcasBartopMedium',
  'kcasBedBunk',
  'kcasBedCot',
  'kcasBedDouble',
  'kcasBedRoyal',
  'kcasBedSingle',
  'kcasBedroll',
  'kcasBench',
  'kcasBookcase',
  'kcasCandleTriple',
  'kcasChair',
  'kcasChestGold',
  'kcasColumn',
  'kcasCrateLarge',
  'kcasCrateSmall',
  'kcasCratesStacked',
  'kcasFloorLarge',
  'kcasFloorWeeds',
  'kcasFoundation',
  'kcasKeg',
  'kcasPillar',
  'kcasRocks',
  'kcasRubbleHalf',
  'kcasRubbleLarge',
  'kcasShelfBooks',
  'kcasShelfCandles',
  'kcasShelfLarge',
  'kcasShelfSmall',
  'kcasShrine',
  'kcasStairsWalled',
  'kcasStairsWide',
  'kcasStool',
  'kcasSwordShield',
  'kcasTableCloth',
  'kcasTableLong',
  'kcasTableRoundMedium',
  'kcasTableRoundSmall',
  'kcasTorch',
  'kcasTorchMounted',
  'kcasWall',
  'kcasWallBroken',
  'kcasWallCorner',
  'kcasWallCracked',
  'kcasWallDoorway',
  'kcasWallGated',
  'kcasWallHalf',
  'kcasWallPillar',
  'kcasWallWindow',
  'kkPillar',
  'kkWall',
  'kkWallCracked',
  'kmedBlacksmith',
  'kmedChurch',
  'kmedHomeA',
  'kmedHomeB',
  'kmedMarket',
  'kmedTavern',
  'lanternWall',
  'leafyFoxStatue',
  'marshReeds',
  'mushroomGiantPurple',
  'mushroomGlowCluster',
  'mushroomRed',
  'mushroomTan',
  'oakTree',
  'oreRocks',
  'pixieMushroomHouse',
  'rockLargeD',
  'rockLargeF',
  'rockTallA',
  'rockTallH',
  'rowboat',
  'shipMonument',
  'shrubFlowering',
  'stagShrine',
  'stand1',
  'stand2',
  'starHeartCrystal',
  'statueBlock',
  'statueHead',
  'tentOpen',
  'tentSmall',
  'timberPillar',
  'weaponStand',
  'well',
]);

const MAX_PROP_KEY_LENGTH = 128;
const MAX_FORGED_SEGMENT_LENGTH = 64;
const FORGED_SEGMENT_RE = /^[A-Za-z0-9_.-]+$/;
const LIBRARY_PROP_RE = /^library:[a-z0-9][a-z0-9_-]{0,31}\/[a-f0-9]{24}$/;
// Realm asset store props (src/render/remote_prop.ts REALM_RE). Read-only
// shipped GLBs served from CR_REALMS_DIR, so the only risk is traversal - the
// character class allows no slash or dot-dot inside the file segment.
const REALM_PROP_RE =
  /^realm:[a-z0-9][a-z0-9_-]{0,31}\/(?:props|buildings|vehicles|ships|mechs|turrets|melee|weapons)\/[A-Za-z0-9_.-]+$/;

function isSafeForgedSegment(segment: string): boolean {
  return (
    segment.length > 0 &&
    segment.length <= MAX_FORGED_SEGMENT_LENGTH &&
    FORGED_SEGMENT_RE.test(segment) &&
    segment !== '.' &&
    !segment.includes('..')
  );
}

/** Validate the complete set of asset references accepted from world-builder clients. */
export function isValidBuilderPropKey(value: unknown): value is string {
  if (typeof value !== 'string' || value.length === 0 || value.length > MAX_PROP_KEY_LENGTH) {
    return false;
  }
  if (NATIVE_PROP_KEYS.has(value)) return true;
  if (LIBRARY_PROP_RE.test(value)) return true;
  if (REALM_PROP_RE.test(value) && !value.includes('..')) return true;
  if (!value.startsWith('forged:')) return false;

  const segments = value.slice('forged:'.length).split('/');
  return segments.length >= 1 && segments.length <= 2 && segments.every(isSafeForgedSegment);
}
