// Forged assets — GLBs generated by the ArcForge pipeline (Hunyuan3D/upload),
// stored on the USB4 canonical store and served to the in-game world builder so
// admins can place them as props/characters.
//
// USB4 forged dir is bind-mounted into this container at FORGED_DIR. We serve
// it read-only at /forged/<name>.glb and list it at /api/forged-props. Uploads
// (admin/mod) land a .glb straight into FORGED_DIR so it appears immediately.

import http from 'node:http';
import fs from 'node:fs';
import fsp from 'node:fs/promises';
import path from 'node:path';
import { authorizeBuilder } from './arcforge_proxy';

// Canonical store path inside the container (USB4 bind mount). Overridable.
const FORGED_DIR = (process.env.ARCFORGE_FORGED_DIR
  ?? '/mnt/usb4/moveweight-assets/forged-glbs').replace(/\/$/, '');

const GLB_RE = /^[A-Za-z0-9_.-]+\.glb$/; // safe filename, .glb only

function send(res: http.ServerResponse, code: number, body: unknown): void {
  const s = JSON.stringify(body);
  res.writeHead(code, { 'content-type': 'application/json' });
  res.end(s);
}

/** Resolve a request name to a real file inside FORGED_DIR, or null if unsafe/missing. */
function safeForgedPath(name: string): string | null {
  if (!GLB_RE.test(name)) return null;
  const full = path.join(FORGED_DIR, name);
  // defense-in-depth: ensure it stays within FORGED_DIR
  if (!full.startsWith(FORGED_DIR + path.sep)) return null;
  return full;
}

/**
 * GET /forged/<name>.glb — stream a forged GLB from the USB4 store.
 * Public read (the renderer fetches it for everyone who sees a placed prop).
 */
export function handleForgedStatic(req: http.IncomingMessage, res: http.ServerResponse): boolean {
  const url = (req.url ?? '').split('?')[0];
  if (!url.startsWith('/forged/')) return false;
  const name = decodeURIComponent(url.slice('/forged/'.length));
  const full = safeForgedPath(name);
  if (!full || !fs.existsSync(full)) { res.writeHead(404); res.end('not found'); return true; }
  const stat = fs.statSync(full);
  res.writeHead(200, {
    'content-type': 'model/gltf-binary',
    'content-length': String(stat.size),
    'cache-control': 'public, max-age=300',
  });
  fs.createReadStream(full).pipe(res);
  return true;
}

/** GET /api/forged-props — list placeable forged GLBs as {key,name,url}[]. */
export async function handleForgedCatalog(req: http.IncomingMessage, res: http.ServerResponse): Promise<boolean> {
  const url = (req.url ?? '').split('?')[0];
  if (url !== '/api/forged-props') return false;
  try {
    const files = await fsp.readdir(FORGED_DIR).catch(() => [] as string[]);
    const items = files
      .filter((f) => GLB_RE.test(f))
      .map((f) => {
        const base = f.replace(/\.glb$/, '');
        return { key: base, name: base.replace(/[_-]+/g, ' '), url: `/forged/${encodeURIComponent(f)}` };
      });
    send(res, 200, { props: items });
  } catch (err) {
    send(res, 500, { error: String(err) });
  }
  return true;
}

/**
 * POST /me/api/arcforge/upload-glb — admin/mod upload a .glb into the forged store.
 * Query/body: filename via ?name=<x>.glb (sanitized). Body = raw GLB bytes.
 * Returns {ok, key, url}.
 */
export async function handleForgedUpload(req: http.IncomingMessage, res: http.ServerResponse): Promise<boolean> {
  const url = (req.url ?? '').split('?')[0];
  if (url !== '/me/api/arcforge/upload-glb' || req.method !== 'POST') return false;
  if (!(await authorizeBuilder(req))) { send(res, 403, { error: 'admin or moderator access required' }); return true; }

  const q = new URLSearchParams((req.url ?? '').split('?')[1] ?? '');
  let name = (q.get('name') ?? '').trim();
  if (!name.toLowerCase().endsWith('.glb')) name += '.glb';
  // sanitize to a safe base name
  name = path.basename(name).replace(/[^A-Za-z0-9_.-]/g, '_');
  const full = safeForgedPath(name);
  if (!full) { send(res, 400, { error: 'invalid filename' }); return true; }

  try {
    await fsp.mkdir(FORGED_DIR, { recursive: true });
    const chunks: Buffer[] = [];
    let total = 0;
    const MAX = 64 * 1024 * 1024; // 64MB cap
    await new Promise<void>((resolve, reject) => {
      req.on('data', (c: Buffer) => {
        total += c.length;
        if (total > MAX) { reject(new Error('file too large (>64MB)')); req.destroy(); return; }
        chunks.push(c);
      });
      req.on('end', () => resolve());
      req.on('error', reject);
    });
    const buf = Buffer.concat(chunks);
    // basic validity: GLB magic 'glTF'
    if (buf.length < 12 || buf.toString('ascii', 0, 4) !== 'glTF') {
      send(res, 400, { error: 'not a valid GLB (missing glTF magic)' });
      return true;
    }
    await fsp.writeFile(full, buf);
    const base = name.replace(/\.glb$/, '');
    send(res, 200, { ok: true, key: base, url: `/forged/${encodeURIComponent(name)}` });
  } catch (err) {
    send(res, 500, { error: String(err) });
  }
  return true;
}
