// Forged GLB assets generated by ArcForge/Meshy and uploaded by builders.
// They are served read-only at /forged/<name>.glb and listed for the in-game
// world builder at /api/forged-props.

import fs from 'node:fs';
import fsp from 'node:fs/promises';
import type http from 'node:http';
import path from 'node:path';

function trimTrailingSeparators(p: string): string {
  return p.replace(/[\\/]+$/, '');
}

export function defaultForgedDir(platform: NodeJS.Platform = process.platform): string {
  return platform === 'win32'
    ? path.win32.join('T:\\', 'moveweight-assets', 'forged-glbs')
    : '/mnt/usb4/moveweight-assets/forged-glbs';
}

export function configuredForgedDir(envValue = process.env.ARCFORGE_FORGED_DIR): string {
  const raw = envValue?.trim() || defaultForgedDir();
  return path.resolve(trimTrailingSeparators(raw));
}

export const FORGED_DIR = configuredForgedDir();

const GLB_RE = /^[A-Za-z0-9_.-]+\.glb$/;
const GLB_REF_RE = /^([A-Za-z0-9_.-]+\/)?[A-Za-z0-9_.-]+\.glb$/;

function send(res: http.ServerResponse, code: number, body: unknown): void {
  const s = JSON.stringify(body);
  res.writeHead(code, { 'content-type': 'application/json' });
  res.end(s);
}

export function safeForgedPath(ref: string, baseDir = FORGED_DIR): string | null {
  if (!GLB_REF_RE.test(ref) || ref.includes('..')) return null;
  const root = path.resolve(baseDir);
  const full = path.resolve(root, ref);
  if (full !== root && !full.startsWith(root + path.sep)) return null;
  return full;
}

/** One row of the world-builder catalog. `placeKey` is what the client stores in
 *  the world document and what isValidBuilderPropKey (server/builder_props.ts)
 *  and remotePropRef (src/render/remote_prop.ts) must both accept. */
export interface BuilderCatalogItem {
  key: string;
  name: string;
  url: string;
  group: string;
  placeKey: string;
}

export async function listForgedProps(baseDir = FORGED_DIR): Promise<BuilderCatalogItem[]> {
  const items: BuilderCatalogItem[] = [];
  const pretty = (s: string) =>
    s
      .replace(/^[a-z]+__/i, '')
      .replace(/[_-]+/g, ' ')
      .trim();
  const entries = await fsp.readdir(baseDir, { withFileTypes: true }).catch(() => []);
  for (const e of entries) {
    if (e.isFile() && GLB_RE.test(e.name)) {
      const base = e.name.replace(/\.glb$/, '');
      items.push({
        key: base,
        name: pretty(base),
        url: `/forged/${encodeURIComponent(e.name)}`,
        group: 'forged',
        placeKey: `forged:${base}`,
      });
    } else if (e.isDirectory() && /^[A-Za-z0-9_.-]+$/.test(e.name)) {
      const sub = await fsp.readdir(path.join(baseDir, e.name)).catch(() => [] as string[]);
      for (const f of sub) {
        if (!GLB_RE.test(f)) continue;
        const base = f.replace(/\.glb$/, '');
        items.push({
          key: `${e.name}/${base}`,
          name: pretty(base),
          url: `/forged/${encodeURIComponent(e.name)}/${encodeURIComponent(f)}`,
          group: e.name,
          placeKey: `forged:${e.name}/${base}`,
        });
      }
    }
  }
  return items.sort((a, b) => a.group.localeCompare(b.group) || a.key.localeCompare(b.key));
}

export function handleForgedStatic(req: http.IncomingMessage, res: http.ServerResponse): boolean {
  const url = (req.url ?? '').split('?')[0];
  if (!url.startsWith('/forged/')) return false;
  const name = decodeURIComponent(url.slice('/forged/'.length));
  const full = safeForgedPath(name);
  if (!full || !fs.existsSync(full)) {
    res.writeHead(404);
    res.end('not found');
    return true;
  }
  const stat = fs.statSync(full);
  res.writeHead(200, {
    'content-type': 'model/gltf-binary',
    'content-length': String(stat.size),
    'cache-control': 'public, max-age=300',
  });
  fs.createReadStream(full).pipe(res);
  return true;
}

// ── /cr-realms/* static store ────────────────────────────────────────────────
// The generated realm-asset bundles (index.json + per-realm manifest/art/GLBs,
// built by scripts/build_realm_assets.mjs) are too large for git; on the server
// they live in a SHARED directory next to the forged store so every realm-stage
// worktree serves the same files. CR_REALMS_DIR overrides; default is the
// `cr-realms` sibling of the forged dir. Local dev serves public/cr-realms via
// Vite, so this route only matters in production.
export function configuredCrRealmsDir(envValue = process.env.CR_REALMS_DIR): string {
  const raw = envValue?.trim() || path.join(path.dirname(FORGED_DIR), 'cr-realms');
  return path.resolve(trimTrailingSeparators(raw));
}
export const CR_REALMS_DIR = configuredCrRealmsDir();

const CR_REALMS_MIME: Record<string, string> = {
  '.json': 'application/json; charset=utf-8',
  '.glb': 'model/gltf-binary',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.webp': 'image/webp',
  '.mp3': 'audio/mpeg',
  '.ogg': 'audio/ogg',
  // The /cr-realms/review/ asset-review gallery page lives inside the store.
  '.html': 'text/html; charset=utf-8',
};
const CR_REALMS_REF_RE = /^[A-Za-z0-9_.-]+(?:\/[A-Za-z0-9 _.()-]+)*$/;

export function handleCrRealmsStatic(req: http.IncomingMessage, res: http.ServerResponse): boolean {
  const url = (req.url ?? '').split('?')[0];
  if (!url.startsWith('/cr-realms/')) return false;
  const name = decodeURIComponent(url.slice('/cr-realms/'.length));
  const ext = path.extname(name).toLowerCase();
  const mime = CR_REALMS_MIME[ext];
  // Traversal-safe: allowlisted characters only, then confirm the resolved path
  // stays inside the store (mirrors safeForgedPath).
  const full = path.resolve(CR_REALMS_DIR, name);
  if (!mime || !CR_REALMS_REF_RE.test(name) || !full.startsWith(CR_REALMS_DIR + path.sep)) {
    res.writeHead(404);
    res.end('not found');
    return true;
  }
  if (!fs.existsSync(full) || !fs.statSync(full).isFile()) {
    res.writeHead(404);
    res.end('not found');
    return true;
  }
  const stat = fs.statSync(full);
  res.writeHead(200, {
    'content-type': mime,
    'content-length': String(stat.size),
    'cache-control': 'public, max-age=300',
  });
  fs.createReadStream(full).pipe(res);
  return true;
}

// World-placeable buckets of the realm asset store. `melee`/`weapons` are held
// items rather than scenery, so they are deliberately NOT here: they reach the
// world through a character's hand (manifest.generated.ts attach[]), and a rifle
// lying on the terrain at prop scale reads as a bug. remotePropRef still accepts
// them so a builder can place one deliberately by key.
const REALM_PROP_BUCKETS = ['buildings', 'props', 'vehicles', 'ships', 'mechs', 'turrets'];

// The bucket a row is filed under, shown as the leading word of its name so one
// realm's few hundred rows stay scannable in a flat alphabetical list.
const REALM_BUCKET_LABEL: Record<string, string> = {
  buildings: 'Building',
  props: 'Prop',
  vehicles: 'Vehicle',
  ships: 'Ship',
  mechs: 'Mech',
  turrets: 'Turret',
};

/** Catalog rows for every world-placeable GLB in the realm asset store.
 *
 *  These files already ship and are already served at /cr-realms/...; before this
 *  the world builder had no way to name one, so ~1,300 buildings/props/vehicles/
 *  ships/mechs/turrets were live on disk and referenced by nothing.
 *
 *  Display names come from the SHIPPED SLUG, never from any stored prompt text:
 *  part of this library is IP-adjacent and was deliberately re-slugged. */
export async function listRealmProps(baseDir = CR_REALMS_DIR): Promise<BuilderCatalogItem[]> {
  const items: BuilderCatalogItem[] = [];
  const pretty = (s: string) =>
    s
      .replace(/_[0-9a-f]{6,}$/i, '')
      .replace(/[_-]+/g, ' ')
      .trim()
      .split(/\s+/)
      .slice(0, 7)
      .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
      .join(' ');
  const realms = await fsp.readdir(baseDir, { withFileTypes: true }).catch(() => []);
  for (const realm of realms) {
    if (!realm.isDirectory() || !/^[a-z0-9][a-z0-9_-]{0,31}$/.test(realm.name)) continue;
    for (const bucket of REALM_PROP_BUCKETS) {
      const files = await fsp.readdir(path.join(baseDir, realm.name, bucket)).catch(() => []);
      for (const f of files) {
        if (!GLB_RE.test(f)) continue;
        const base = f.replace(/\.glb$/, '');
        items.push({
          key: `${realm.name}/${bucket}/${base}`,
          name: `${REALM_BUCKET_LABEL[bucket]} \u00b7 ${pretty(base) || base}`,
          url: `/cr-realms/${realm.name}/${bucket}/${encodeURIComponent(f)}`,
          group: realm.name,
          placeKey: `realm:${realm.name}/${bucket}/${base}`,
        });
      }
    }
  }
  return items.sort((a, b) => a.group.localeCompare(b.group) || a.name.localeCompare(b.name));
}

export async function handleForgedCatalog(
  req: http.IncomingMessage,
  res: http.ServerResponse,
): Promise<boolean> {
  const url = (req.url ?? '').split('?')[0];
  if (url !== '/api/forged-props') return false;
  try {
    const [forged, realm] = await Promise.all([listForgedProps(), listRealmProps()]);
    send(res, 200, { props: [...forged, ...realm] });
  } catch (err) {
    send(res, 500, { error: String(err) });
  }
  return true;
}

export async function handleForgedUpload(
  req: http.IncomingMessage,
  res: http.ServerResponse,
): Promise<boolean> {
  const url = (req.url ?? '').split('?')[0];
  if (url !== '/me/api/arcforge/upload-glb' || req.method !== 'POST') return false;
  const { authorizeBuilder } = await import('./arcforge_proxy');
  if (!(await authorizeBuilder(req))) {
    send(res, 403, { error: 'admin or moderator access required' });
    return true;
  }

  const q = new URLSearchParams((req.url ?? '').split('?')[1] ?? '');
  let name = (q.get('name') ?? '').trim();
  if (!name.toLowerCase().endsWith('.glb')) name += '.glb';
  name = path.basename(name).replace(/[^A-Za-z0-9_.-]/g, '_');
  const full = safeForgedPath(name);
  if (!full) {
    send(res, 400, { error: 'invalid filename' });
    return true;
  }

  try {
    await fsp.mkdir(FORGED_DIR, { recursive: true });
    const chunks: Buffer[] = [];
    let total = 0;
    const maxBytes = 64 * 1024 * 1024;
    await new Promise<void>((resolve, reject) => {
      req.on('data', (c: Buffer) => {
        total += c.length;
        if (total > maxBytes) {
          reject(new Error('file too large (>64MB)'));
          req.destroy();
          return;
        }
        chunks.push(c);
      });
      req.on('end', () => resolve());
      req.on('error', reject);
    });
    const buf = Buffer.concat(chunks);
    if (buf.length < 12 || buf.toString('ascii', 0, 4) !== 'glTF') {
      send(res, 400, { error: 'not a valid GLB (missing glTF magic)' });
      return true;
    }
    await fsp.writeFile(full, buf);
    const base = name.replace(/\.glb$/, '');
    send(res, 200, { ok: true, key: base, url: `/forged/${encodeURIComponent(name)}` });
  } catch (err) {
    send(res, 500, { error: String(err) });
  }
  return true;
}
