// Generated by scripts/i18n_admin_build.mjs. Do not edit by hand.
//
// Part of the generated src/admin/i18n.resolved.generated/ directory: one dense
// ADMIN locale slice per file (each `: AdminTranslations` = typeof en, so tsc
// red-fails a missing or renamed key), a back-compat barrel (index.ts) that
// re-exports every slice and assembles the runtime `translations` map, per-locale
// loaders (loaders.ts, parity scaffolding - admin is NOT lazy), and the pending
// set (pending.ts). The admin SPA consumes ONLY this table (never the game locale
// table); regenerate with `npm run i18n:admin` (also wired into `npm run build`
// and `pretest`). Reproducibility is checked by tests/i18n_admin_catalog.test.ts.

export const pending: Record<string, readonly string[]> = {
  "es": [
    "app.titleRealm",
    "nav.realmBadge",
    "nav.switchRealm"
  ],
  "es_ES": [
    "app.titleRealm",
    "nav.realmBadge",
    "nav.switchRealm"
  ],
  "fr_FR": [
    "app.titleRealm",
    "nav.realmBadge",
    "nav.switchRealm"
  ],
  "fr_CA": [
    "app.titleRealm",
    "nav.realmBadge",
    "nav.switchRealm"
  ],
  "en_CA": [],
  "it_IT": [
    "app.titleRealm",
    "nav.realmBadge",
    "nav.switchRealm"
  ],
  "de_DE": [
    "app.titleRealm",
    "nav.realmBadge",
    "nav.switchRealm"
  ],
  "zh_CN": [
    "app.titleRealm",
    "nav.realmBadge",
    "nav.switchRealm"
  ],
  "zh_TW": [
    "app.titleRealm",
    "nav.realmBadge",
    "nav.switchRealm"
  ],
  "ko_KR": [
    "app.titleRealm",
    "nav.realmBadge",
    "nav.switchRealm"
  ],
  "ja_JP": [
    "app.titleRealm",
    "nav.realmBadge",
    "nav.switchRealm"
  ],
  "pt_BR": [
    "app.titleRealm",
    "nav.realmBadge",
    "nav.switchRealm"
  ],
  "ru_RU": [
    "app.titleRealm",
    "nav.realmBadge",
    "nav.switchRealm"
  ],
  "cs_CZ": [
    "app.titleRealm",
    "nav.realmBadge",
    "nav.switchRealm",
    "usage.metric.githubContributorsFetch",
    "usage.metric.githubContributorsFetchFailure",
    "usage.metric.githubLinkFailure",
    "usage.metric.githubLinkRateLimited",
    "usage.metric.githubLinkRequest"
  ],
  "nl_NL": [
    "app.titleRealm",
    "nav.realmBadge",
    "nav.switchRealm"
  ],
  "pl_PL": [
    "app.titleRealm",
    "nav.realmBadge",
    "nav.switchRealm"
  ],
  "id_ID": [
    "app.titleRealm",
    "nav.realmBadge",
    "nav.switchRealm"
  ],
  "tr_TR": [
    "app.titleRealm",
    "nav.realmBadge",
    "nav.switchRealm"
  ],
  "sv_SE": [
    "app.titleRealm",
    "nav.realmBadge",
    "nav.switchRealm"
  ],
  "vi_VN": [
    "app.titleRealm",
    "nav.realmBadge",
    "nav.switchRealm"
  ],
  "da_DK": [
    "app.titleRealm",
    "nav.realmBadge",
    "nav.switchRealm"
  ]
};
