// Generated by scripts/meshy-cryptic-character-pipeline.mjs.
// This file is safe to commit when generated assets are committed.

export const CR_GENERATED_MESHY_ACTORS = {
  "ember_witch": {
    "runId": "ember_witch_20260525122016_jlpy",
    "label": "Ember Witch",
    "generatedAt": "2026-05-25T12:27:11.877Z",
    "refinedUrl": "/cryptic-assets/3d-assets/Meshy/Characters/ArcForgeGenerated/ember_witch/ember_witch_20260525122016_jlpy/ember_witch_refined.glb",
    "idleUrl": "/cryptic-assets/3d-assets/Meshy/Characters/ArcForgeGenerated/ember_witch/ember_witch_20260525122016_jlpy/ember_witch_idle.glb",
    "walkUrl": "/cryptic-assets/3d-assets/Meshy/Characters/ArcForgeGenerated/ember_witch/ember_witch_20260525122016_jlpy/ember_witch_walk.glb",
    "runUrl": "/cryptic-assets/3d-assets/Meshy/Characters/ArcForgeGenerated/ember_witch/ember_witch_20260525122016_jlpy/ember_witch_run.glb",
    "attackUrl": "/cryptic-assets/3d-assets/Meshy/Characters/ArcForgeGenerated/ember_witch/ember_witch_20260525122016_jlpy/ember_witch_attack.glb",
    "castUrl": "/cryptic-assets/3d-assets/Meshy/Characters/ArcForgeGenerated/ember_witch/ember_witch_20260525122016_jlpy/ember_witch_cast.glb",
    "hurtUrl": "/cryptic-assets/3d-assets/Meshy/Characters/ArcForgeGenerated/ember_witch/ember_witch_20260525122016_jlpy/ember_witch_hurt.glb",
    "deathUrl": "/cryptic-assets/3d-assets/Meshy/Characters/ArcForgeGenerated/ember_witch/ember_witch_20260525122016_jlpy/ember_witch_death.glb"
  },
  "steel_crusader": {
    "runId": "steel_crusader_20260525170859_h96a",
    "label": "Steel Crusader",
    "generatedAt": "2026-05-25T17:14:36.655Z",
    "refinedUrl": "/cryptic-assets/3d-assets/Meshy/Characters/ArcForgeGenerated/steel_crusader/steel_crusader_20260525170859_h96a/steel_crusader_refined.glb",
    "idleUrl": "/cryptic-assets/3d-assets/Meshy/Characters/ArcForgeGenerated/steel_crusader/steel_crusader_20260525170859_h96a/steel_crusader_idle.glb",
    "walkUrl": "/cryptic-assets/3d-assets/Meshy/Characters/ArcForgeGenerated/steel_crusader/steel_crusader_20260525170859_h96a/steel_crusader_walk.glb",
    "runUrl": "/cryptic-assets/3d-assets/Meshy/Characters/ArcForgeGenerated/steel_crusader/steel_crusader_20260525170859_h96a/steel_crusader_run.glb",
    "attackUrl": "/cryptic-assets/3d-assets/Meshy/Characters/ArcForgeGenerated/steel_crusader/steel_crusader_20260525170859_h96a/steel_crusader_attack.glb",
    "castUrl": "/cryptic-assets/3d-assets/Meshy/Characters/ArcForgeGenerated/steel_crusader/steel_crusader_20260525170859_h96a/steel_crusader_cast.glb",
    "hurtUrl": "/cryptic-assets/3d-assets/Meshy/Characters/ArcForgeGenerated/steel_crusader/steel_crusader_20260525170859_h96a/steel_crusader_hurt.glb",
    "deathUrl": "/cryptic-assets/3d-assets/Meshy/Characters/ArcForgeGenerated/steel_crusader/steel_crusader_20260525170859_h96a/steel_crusader_death.glb"
  }
};

export function crGeneratedMeshyActor(id) {
  return CR_GENERATED_MESHY_ACTORS[id] || null;
}
