// crypticLoreData.js - Cryptic Realm v7.0 campaign canon.
// Keep this in sync with CrypticLore.md when expanding the game.

export const CRYPTIC_DIFFICULTIES = [
  {
    id: "normal",
    label: "CRYPTIC",
    icon: "CR",
    color: "#44ff88",
    mult: 1,
    desc: "Base horror. The Veil still hides the worst truths.",
  },
  {
    id: "nightmare",
    label: "VEILED",
    icon: "VL",
    color: "#ffaa00",
    mult: 1.75,
    desc: "Nightmare escalation. Echoes contradict the first telling.",
  },
  {
    id: "hell",
    label: "ABYSSAL",
    icon: "AB",
    color: "#ff3322",
    mult: 3,
    desc: "Full demonic invasion. The Triumvirate's legions breach Cryptara.",
  },
  {
    id: "inferno",
    label: "SYNOD'S WRATH",
    icon: "SW",
    color: "#66ccff",
    mult: 4.5,
    desc: "Celestial tyrants and abyssal lords fight over mortal Veiled Blood.",
  },
  {
    id: "abyss",
    label: "FIRSTBORN ECLIPSE",
    icon: "FE",
    color: "#cc44ff",
    mult: 8,
    desc: "God-like hybrid power, truer events, and alternate apocalyptic endings.",
  },
];

export function crypticDifficulty(id = "normal") {
  return CRYPTIC_DIFFICULTIES.find(diff => diff.id === id) || CRYPTIC_DIFFICULTIES[0];
}

export function crypticDifficultyLabel(id = "normal") {
  return crypticDifficulty(id).label;
}

export const CRYPTIC_CLASSES_LORE = {
  ember_witch: {
    loreName: "EMBER WITCH",
    archetype: "Witch Doctor / Sorceress hybrid",
    short: "Flame-touched pact mage. Hellfire, soul curses, fiery imps, and explosive arcane eruptions.",
    backstory: "Women from burning wastelands survived Malachar's terror by embracing the fire that consumed their homes, becoming living conduits of infernal wrath.",
    role: "Infernal artillery and curse caster",
  },
  iron_warden: {
    loreName: "IRON WARDEN",
    archetype: "Barbarian / Warrior",
    short: "Veilstone highlander. Massive weapons, binding runes, primal fury, and ruin-resistant endurance.",
    backstory: "Survivors of Kragor's ancient rampages tattooed binding runes into their flesh to contain the ruin within.",
    role: "Frontline bruiser and weapon master",
  },
  bone_herald: {
    loreName: "BLOOD HERALD",
    archetype: "Necromancer",
    short: "Death-veiled priest. Bone lances, skeletal legions, corpse rites, and life-draining blood magic.",
    backstory: "Scholars discovered that Veiled Blood persists after death, allowing them to raise armies from the fallen while resisting eternal lichdom.",
    role: "Summoner, corpse engine, and bone caster",
  },
  shadow_blade: {
    loreName: "SHADOW BLADE",
    archetype: "Rogue / Assassin / Demon Hunter",
    short: "Borderland executioner. Shadow steps, traps, venom, dual blades, and abyssal precision.",
    backstory: "Orphans of Vorath's hatred campaigns learned to become the darkness that preys on darkness.",
    role: "Stealth striker and trap specialist",
  },
  forest_sage: {
    loreName: "FOREST SAGE",
    archetype: "Druid / Witch Doctor",
    short: "Corrupted wild mystic. Vines, beasts, poison spirits, and nightmarish shapeshifts.",
    backstory: "Guardians of ancient groves tainted by Vespera's influence learned to wield savage demonic nature rather than deny it.",
    role: "Nature controller and shapeshifter",
  },
  steel_crusader: {
    loreName: "STEEL CRUSADER",
    archetype: "Paladin / Crusader",
    short: "Synod-trained zealot. Shields, auras, judgment, and a crisis of holy tyranny.",
    backstory: "Knights once marched under Elyndor's banner and now question whether faith is salvation or another chain.",
    role: "Shield tank, aura support, and smiter",
  },
  void_archer: {
    loreName: "VOID ARCHER",
    archetype: "Amazon / Demon Hunter",
    short: "Rift scout. Void arrows, celestial piercing light, evasive steps, and shadow marksmanship.",
    backstory: "Descendants of scouts who witnessed the first rifts learned to weaponize the emptiness left behind.",
    role: "Ranged marksman and mobility hunter",
  },
};

export const CRYPTIC_ACT_LORE = [
  {
    id: 1,
    chapter: "Game 1: Shadows of the Spire",
    name: "SHADOWS OF THE SPIRE",
    icon: "I",
    color: "#8844aa",
    town: "THORNVALE",
    region: "Thornvale and Eldrath Spire",
    desc: "Fog-shrouded village and ruined cathedral where Malachar's nightmare fragment leaks into flesh.",
    lore: "Madness descends on Thornvale. Livestock are mutilated, villagers suffer night-terrors, and the mines beneath the cathedral open into fear-soaked crypts.",
    boss: "MALACHAR'S WHISPER",
    waypoints: ["Thornvale", "Haunted Mines", "Eldrath Cathedral", "Blood Pits", "Spire Sanctum"],
    enemies: ["zombie", "skeleton", "werewolf"],
    bossPatch: { name: "MALACHAR'S WHISPER", color: "#cc4488" },
    quests: [
      "Free Eldrin Voss, Last of the Conclave",
      "Clear the Haunted Mines road",
      "Find a hidden Statue of Death",
      "Complete the Spire skill trial",
      "Open three cursed cathedral chests",
      "Recover the resistance scroll",
      "Earn the Thornvale captain's trust",
      "Win the blacksmith's imbue rite",
      "Recover the socket hammer",
      "Bind a custom item name",
      "Defeat Malachar's Whisper",
    ],
    vendors: {
      healer: "SISTER AURELIA",
      merc: "ROGUE CAPTAIN SEREN",
      stash: "CONCLAVE STASH KEEPER",
      merchant: "THORNVALE TRAVELER",
      forge: "GRAVEFORGE SMITH",
      skin: "VEIL WARDROBE",
      identifier: "ELDRIN VOSS",
      waypoint: "WAYPOINT SHRINE",
    },
  },
  {
    id: 2,
    chapter: "Game 2: Chains of the Triumvirate",
    name: "CHAINS OF VALTHUUN",
    icon: "II",
    color: "#cc8833",
    town: "VALTHUUN",
    region: "Valthuun Desert and Tombs",
    desc: "Scorching sands hide arcane vaults, buried Firstborn sarcophagi, and the sealed Burrower.",
    lore: "The Marked wanderer pulls corruption east through the desert. Valthuun's tomb gates open, and old bargains wake beneath the dunes.",
    boss: "VEXOR, BURROWER OF AGONY",
    waypoints: ["Valthuun", "Sewer Mouth", "Dry Hills", "Lost Tombs", "Sealed Burial Vault"],
    enemies: ["sand_golem", "mummy", "scorpion"],
    bossPatch: { name: "VEXOR, BURROWER OF AGONY", color: "#ffcc44" },
    quests: [
      "Free the Identifier of Valthuun",
      "Clear the Dry Hills caravan road",
      "Find a hidden Statue of Death",
      "Complete the tomb skill trial",
      "Open three cursed tomb chests",
      "Recover the desert resistance scroll",
      "Earn the Iron Wolf captain's trust",
      "Win the Sunforge imbue rite",
      "Recover the socket hammer",
      "Bind a custom item name",
      "Defeat Vexor, Burrower of Agony",
    ],
    vendors: {
      healer: "DESERT MENDER SAHIRA",
      merc: "IRON WOLF CAPTAIN",
      stash: "DOCK VAULT KEEPER",
      merchant: "VALTHUUN BAZAAR",
      forge: "SUNFORGE SMITH",
      skin: "VEIL WARDROBE",
      identifier: "ELDRIN VOSS",
      waypoint: "WAYPOINT SHRINE",
    },
  },
  {
    id: 3,
    chapter: "Game 2: Chains of the Triumvirate",
    name: "JUNGLE OF ENDLESS SPITE",
    icon: "III",
    color: "#44aa44",
    town: "VERDANT KEEP",
    region: "Jungle temple city",
    desc: "Blood-drinking vines and corrupted priests guard Vorath's oldest temple district.",
    lore: "The jungle drinks betrayal. Each temple gate opens only after another priest, ally, or memory is sacrificed to Vorath's spite.",
    boss: "VORATH'S COUNCIL",
    waypoints: ["Verdant Keep", "Spider Marsh", "Flayer Hollow", "Temple of Spite", "Durance Root"],
    enemies: ["jungle_demon", "shaman", "plant_horror"],
    bossPatch: { name: "VORATH'S COUNCIL", color: "#44ff44" },
    quests: [
      "Free the Identifier of Verdant Keep",
      "Clear the Spider Marsh causeway",
      "Find a hidden Statue of Death",
      "Complete the spite skill trial",
      "Open three cursed temple chests",
      "Recover the jungle resistance scroll",
      "Earn the docks captain's trust",
      "Win the Jade Smith's imbue rite",
      "Recover the socket hammer",
      "Bind a custom item name",
      "Defeat Vorath's Council",
    ],
    vendors: {
      healer: "JUNGLE ORACLE MAEVA",
      merc: "DOCKSIDE CAPTAIN",
      stash: "RELIC KEEPER",
      merchant: "RIVER TRADER",
      forge: "JADE SMITH",
      skin: "VEIL WARDROBE",
      identifier: "ELDRIN VOSS",
      waypoint: "WAYPOINT SHRINE",
    },
  },
  {
    id: 4,
    chapter: "Game 2: Chains of the Triumvirate",
    name: "THE NULLFORGE",
    icon: "IV",
    color: "#ff4422",
    town: "PANDEMONIUM FORTRESS",
    region: "Outer Hell",
    desc: "A fortress at the edge of the inferno, where Echo Shards can be destroyed or perverted.",
    lore: "Infernal incursions tear through the fortress walls. The Nullforge burns with power enough to break a Veil Crystal or twist it into a weapon.",
    boss: "MALACHAR, THE DREAD SOVEREIGN",
    waypoints: ["Pandemonium Fortress", "Outer Steppes", "Plain of Ash", "River of Flame", "The Nullforge"],
    enemies: ["fire_imp", "blood_knight", "chaos_mage"],
    bossPatch: { name: "MALACHAR, THE DREAD SOVEREIGN", color: "#ff2200" },
    quests: [
      "Free the Identifier of the Fortress",
      "Clear the Outer Steppes",
      "Find a hidden Statue of Death",
      "Complete the Nullforge skill trial",
      "Open three cursed forge chests",
      "Recover the ash resistance scroll",
      "Earn the bastion captain's trust",
      "Win the Hellforge imbue rite",
      "Recover the socket hammer",
      "Bind a custom item name",
      "Defeat Malachar, the Dread Sovereign",
    ],
    vendors: {
      healer: "FORTRESS HEALER ILYRA",
      merc: "BASTION CAPTAIN",
      stash: "BASTION KEEPER",
      merchant: "HELLFORGE QUARTERMASTER",
      forge: "NULLFORGE SMITH",
      skin: "VEIL WARDROBE",
      identifier: "ELDRIN VOSS",
      waypoint: "WAYPOINT SHRINE",
    },
  },
  {
    id: 5,
    chapter: "Game 2: Chains of the Triumvirate",
    name: "VEILSTONE SIEGE",
    icon: "V",
    color: "#88ccff",
    town: "GLACIUS HOLD",
    region: "Fractured Peaks",
    desc: "Frozen northern war camps surround a Veilstone shard site under Kragor's ruin assault.",
    lore: "The old highland oaths fail as Kragor's armies climb the peaks. The Veilstone shard screams beneath ice and siege fire.",
    boss: "KRAGOR'S AVATAR",
    waypoints: ["Glacius Hold", "Frigid Approach", "Crystal Passage", "Ancient Trail", "Veilstone Summit"],
    enemies: ["ice_wraith", "frost_giant", "snow_witch"],
    bossPatch: { name: "KRAGOR'S AVATAR", color: "#88ccff" },
    quests: [
      "Free the Identifier of Glacius Hold",
      "Clear the Frigid Approach",
      "Find a hidden Statue of Death",
      "Complete the Veilstone skill trial",
      "Open three cursed siege chests",
      "Recover the frost resistance scroll",
      "Earn the siege captain's trust",
      "Win the Runeforge imbue rite",
      "Recover the socket hammer",
      "Bind a custom item name",
      "Defeat Kragor's Avatar",
    ],
    vendors: {
      healer: "HIGHLAND HEALER BRYN",
      merc: "SIEGE CAPTAIN",
      stash: "CLAN KEEPER",
      merchant: "MOUNTAIN TRADER",
      forge: "RUNEFORGE SMITH",
      skin: "VEIL WARDROBE",
      identifier: "ELDRIN VOSS",
      waypoint: "WAYPOINT SHRINE",
    },
  },
  {
    id: 6,
    chapter: "Game 5: Shattering of the Veil",
    name: "SHATTERING OF THE VEIL",
    icon: "VI",
    color: "#cc44ff",
    town: "THE NEXUS VOID",
    region: "Between worlds",
    desc: "The final wound between realities where Synod, Dominion, and mortal Veiled Blood collide.",
    lore: "The Veilstone fractures. Echoes of past heroes, Firstborn armies, and the Triumvirate converge at the Eternal Threshold.",
    boss: "THE FIRSTBORN ECLIPSE",
    waypoints: ["The Nexus Void", "Rift Anchorage", "Starless Bridge", "Astral Crucible", "Eternal Threshold"],
    enemies: ["rift_spawn", "dim_horror", "star_eater"],
    bossPatch: { name: "THE FIRSTBORN ECLIPSE", color: "#cc44ff" },
    quests: [
      "Free the Identifier of the Nexus",
      "Clear the Starless Bridge",
      "Find a hidden Statue of Death",
      "Complete the Eclipse skill trial",
      "Open three cursed rift chests",
      "Recover the final resistance scroll",
      "Earn the rift captain's trust",
      "Win the Voidforge imbue rite",
      "Recover the socket hammer",
      "Bind a custom item name",
      "Defeat the Firstborn Eclipse",
    ],
    vendors: {
      healer: "VOID HEALER SERA",
      merc: "RIFT CAPTAIN",
      stash: "NEXUS KEEPER",
      merchant: "ASTRAL MERCHANT",
      forge: "VOIDFORGE SMITH",
      skin: "VEIL WARDROBE",
      identifier: "ELDRIN VOSS",
      waypoint: "WAYPOINT SHRINE",
    },
  },
];

export const CRYPTIC_GAME_ARC = [
  {
    title: "Shadows of the Spire",
    style: "Intimate gothic horror",
    pitch: "Thornvale rots beneath a cathedral that seals Malachar's nightmare fragment.",
    chapters: ["Madness in Thornvale", "The Flayer's chambers", "Echo Shards", "Nightmare labyrinth", "The Marked"],
  },
  {
    title: "Chains of the Triumvirate",
    style: "Epic pursuit across lands",
    pitch: "The Marked wanderer spreads corruption while Vorath and Kragor strain against their bindings.",
    chapters: ["Blighted sisterhood", "Valthuun tombs", "Jungle of spite", "Infernal bridge", "Veilstone siege"],
  },
  {
    title: "Veil of the Firstborn",
    style: "Awakening and celestial invasion",
    pitch: "A falling star awakens true Veiled Blood and drags the Radiant Synod into mortal war.",
    chapters: ["New Thornvale", "Desert deceit", "Mountain siege", "Border realms", "Myrathiel's purge"],
  },
  {
    title: "Reign of Hatred",
    style: "Open-world progenitor return",
    pitch: "Vespera returns to awaken mortals while Elyndor seeks to purify them into obedience.",
    chapters: ["Prologue of blood", "Misty wilds", "Hawezar swamps", "Badlands cults", "Progenitor judgment"],
  },
  {
    title: "Shattering of the Veil",
    style: "Endgame realm war",
    pitch: "The Veilstone fractures, and every ancient power tries to claim the mortal apocalypse.",
    chapters: ["Echo Shards", "Returning heroes", "Hybrid armies", "Synod or Dominion", "Mortal third path"],
  },
];

export const CRYPTIC_BESTIARY_LORE = [
  { id: "fleshflayer", family: "Dread", name: "Fleshflayer", desc: "Hook-armed abomination born from a child's fear of butchers." },
  { id: "nightmare_spawn", family: "Dread", name: "Nightmare Spawn", desc: "Malachar fragments that crawl from victims' eyes and mouths." },
  { id: "spitebound_cultist", family: "Spite", name: "Spitebound Cultist", desc: "Vorath-twisted mortals who betray allies and explode in hatred." },
  { id: "ruin_colossus", family: "Ruin", name: "Ruin Colossus", desc: "Kragor constructs of corrupted stone and flesh that shatter the earth." },
  { id: "veil_wraith", family: "Veil-Torn", name: "Veil Wraith", desc: "Firstborn remnants whose touch unravels Veiled Blood." },
  { id: "fallen_ember_imp", family: "Abyssal", name: "Fallen Ember Imp", desc: "Fiery demons that swarm and self-detonate in hellfire." },
];

export const CRYPTIC_REGION_LORE = [
  "Thornvale and Eldrath Spire",
  "Blighted Moors and Convent of Torment",
  "Valthuun Desert and Tombs",
  "Jungle of Endless Spite",
  "Fractured Peaks",
  "Hawezar Swamps",
  "The Nexus Void",
];
