// Dominion — sci-fi alien war. Hermes/Qwen origin: cryptic/crThemes.js
// "dominion-frontier".

import type { RealmContent } from '../types';

export const DOMINION_REALM: RealmContent = {
  id: 'dominion',
  name: 'Dominion Frontier',
  tagline: 'Sci-fi alien war — squads, tech, and galactic conquest',
  description:
    "Humanity's last fleets clash with alien dominions across hostile star systems. " +
    'Build your squad, research alien tech, and hold the frontier.',
  mood: 'Tactical · Sci-Fi · Intense',
  season: {
    eyebrow: 'Season 1',
    title: 'The Frontier Arsenal',
    body: "Limited weapon finishes requisitioned from the Frontier's forward arsenals. Account-wide, purely cosmetic, and shown to everyone around you.",
  },
  accentHex: '#3ad6c8',
  bgGradient: 'linear-gradient(135deg, #02161a 0%, #020a0d 100%)',
  previewColors: { primary: '#3ad6c8', secondary: '#c9a14a', bg: '#050a0f' },
  branding: {
    logoSrc: '/cryptic-realm-logo-512.webp',
    brandText: 'Cryptic Realm - Dominion',
    loadingScreenSrc: '/cryptic-realm-loading-bg.webp',
    discordUrl: 'https://discord.gg/WnxcamHJdh',
    showDonate: false,
    showAuthentikSso: true,
  },
  classes: [
    {
      id: 'vanguard',
      name: 'Vanguard',
      role: 'Tank',
      baseClass: 'paladin',
      icon: '\u{1F6E1}',
      color: '#3ad6c8',
      lore: 'Vanguards wear powered exoskeletons rated for atmospheric re-entry. They drop from orbit into the thickest fighting and hold the line until reinforcements arrive.',
      baseStats: {
        maxHp: 195,
        maxMp: 70,
        str: 34,
        dex: 8,
        vit: 36,
        nrg: 10,
        dmg: 20,
        def: 38,
        spd: 0.8,
      },
      skills: [
        {
          name: 'Orbital Drop',
          icon: '☄',
          mp: 35,
          type: 'AoE',
          dmg: 250,
          range: 5,
          desc: 'Drop from orbit, stunning and damaging all nearby',
          color: '#3ad6c8',
        },
        {
          name: 'Energy Shield',
          icon: '\u{1F535}',
          mp: 25,
          type: 'Buff',
          dmg: 0,
          range: 0,
          desc: 'Activate shield absorbing 500 damage',
          color: '#2980b9',
        },
        {
          name: 'Shockwave',
          icon: '\u{1F4AB}',
          mp: 20,
          type: 'AoE',
          dmg: 180,
          range: 6,
          desc: 'Slam fist into ground, knockback all enemies',
          color: '#f39c12',
        },
        {
          name: 'Lockdown',
          icon: '⛓',
          mp: 30,
          type: 'CC',
          dmg: 0,
          range: 8,
          desc: 'Deploy gravity anchor, rooting targets for 4s',
          color: '#7f8c8d',
        },
      ],
      skillTrees: ['Exo-Suit', 'Drop Tactics', 'Heavy Ordnance'],
    },
    {
      id: 'ghostsniper',
      name: 'Ghost Sniper',
      role: 'DPS',
      baseClass: 'hunter',
      icon: '\u{1F3AF}',
      color: '#e74c3c',
      lore: 'Ghost Snipers operate alone behind enemy lines for weeks at a time. Their rifles fire antimatter rounds from 2 km away.',
      baseStats: {
        maxHp: 75,
        maxMp: 85,
        str: 10,
        dex: 38,
        vit: 8,
        nrg: 18,
        dmg: 38,
        def: 8,
        spd: 1.6,
      },
      skills: [
        {
          name: 'Antimatter Shot',
          icon: '⚡',
          mp: 30,
          type: 'Projectile',
          dmg: 500,
          range: 25,
          desc: 'Devastating single shot, 3s charge time',
          color: '#e74c3c',
        },
        {
          name: 'Cloak',
          icon: '\u{1F47B}',
          mp: 20,
          type: 'Buff',
          dmg: 0,
          range: 0,
          desc: 'Become invisible for 8s or until firing',
          color: '#6c5ce7',
        },
        {
          name: 'Thermal Mine',
          icon: '\u{1F4A3}',
          mp: 15,
          type: 'Trap',
          dmg: 200,
          range: 4,
          desc: 'Place proximity mine, triggers on enemy approach',
          color: '#f39c12',
        },
        {
          name: 'Execute',
          icon: '\u{1F480}',
          mp: 25,
          type: 'Projectile',
          dmg: 800,
          range: 20,
          desc: 'Instantly kill target below 15% HP',
          color: '#2c3e50',
        },
      ],
      skillTrees: ['Precision', 'Stealth Ops', 'Field Tech'],
    },
    {
      id: 'fieldmedic',
      name: 'Field Medic',
      role: 'Healer',
      baseClass: 'priest',
      icon: '✚',
      color: '#2ecc71',
      lore: 'Field Medics carry enough nano-gel to rebuild a squad from paste. They sprint through gunfire to reach the wounded.',
      baseStats: {
        maxHp: 110,
        maxMp: 150,
        str: 8,
        dex: 16,
        vit: 20,
        nrg: 30,
        dmg: 12,
        def: 14,
        spd: 1.6,
      },
      skills: [
        {
          name: 'Nano-Gel',
          icon: '\u{1F489}',
          mp: 20,
          type: 'Heal',
          dmg: 0,
          range: 8,
          desc: 'Heal target for 45% max HP over 4s',
          color: '#2ecc71',
        },
        {
          name: 'Stim Injector',
          icon: '\u{1F48A}',
          mp: 15,
          type: 'Buff',
          dmg: 0,
          range: 6,
          desc: 'Boost ally damage by 30% for 10s',
          color: '#e67e22',
        },
        {
          name: 'Healing Drone',
          icon: '\u{1F916}',
          mp: 40,
          type: 'Summon',
          dmg: 0,
          range: 0,
          desc: 'Deploy drone that heals nearby allies for 20s',
          color: '#3498db',
        },
        {
          name: 'Defibrillate',
          icon: '⚡',
          mp: 50,
          type: 'Resurrect',
          dmg: 0,
          range: 3,
          desc: 'Revive fallen ally with 60% HP',
          color: '#f1c40f',
        },
      ],
      skillTrees: ['Combat Medicine', 'Nano-Tech', 'Triage'],
    },
    {
      id: 'combatengineer',
      name: 'Combat Engineer',
      role: 'Support',
      baseClass: 'hunter',
      icon: '⚙',
      color: '#f39c12',
      lore: "Combat Engineers build the war as others fight it. Turrets, barricades, repair drones, EMP mines — if it keeps the squad alive, they'll weld it together under fire.",
      baseStats: {
        maxHp: 120,
        maxMp: 130,
        str: 14,
        dex: 18,
        vit: 22,
        nrg: 22,
        dmg: 16,
        def: 22,
        spd: 1.2,
      },
      skills: [
        {
          name: 'Auto-Turret',
          icon: '\u{1F52B}',
          mp: 35,
          type: 'Summon',
          dmg: 80,
          range: 12,
          desc: 'Deploy turret that fires for 20s',
          color: '#f39c12',
        },
        {
          name: 'EMP Mine',
          icon: '⚡',
          mp: 20,
          type: 'Trap',
          dmg: 150,
          range: 5,
          desc: 'Mine disables enemy tech and stuns organics',
          color: '#3498db',
        },
        {
          name: 'Repair Beam',
          icon: '\u{1F527}',
          mp: 15,
          type: 'Heal',
          dmg: 0,
          range: 8,
          desc: 'Channel beam restoring 5% HP/s to ally',
          color: '#2ecc71',
        },
        {
          name: 'Overclock',
          icon: '⚙',
          mp: 40,
          type: 'Buff',
          dmg: 0,
          range: 0,
          desc: 'All deployed tech operates at 150% for 10s',
          color: '#e74c3c',
        },
      ],
      skillTrees: ['Deployables', 'Demolitions', 'Cyber Warfare'],
    },
    {
      id: 'psionicoperative',
      name: 'Psionic Operative',
      role: 'DPS',
      baseClass: 'mage',
      icon: '\u{1F9E0}',
      color: '#9b59b6',
      lore: 'Psionic Operatives are government secrets — gene-edited humans who can crush tanks with thought and read memories like books.',
      baseStats: {
        maxHp: 80,
        maxMp: 175,
        str: 6,
        dex: 12,
        vit: 8,
        nrg: 38,
        dmg: 34,
        def: 8,
        spd: 1.5,
      },
      skills: [
        {
          name: 'Mind Crush',
          icon: '\u{1F9E0}',
          mp: 25,
          type: 'Projectile',
          dmg: 300,
          range: 12,
          desc: 'Telekinetic blast dealing heavy damage',
          color: '#9b59b6',
        },
        {
          name: 'Telekinesis',
          icon: '✋',
          mp: 20,
          type: 'CC',
          dmg: 100,
          range: 10,
          desc: 'Lift and throw target, stunning for 2s',
          color: '#e879f9',
        },
        {
          name: 'Psychic Scream',
          icon: '\u{1F631}',
          mp: 35,
          type: 'AoE',
          dmg: 220,
          range: 7,
          desc: 'Scream that damages and fears all nearby',
          color: '#e74c3c',
        },
        {
          name: 'Mind Control',
          icon: '\u{1F3AD}',
          mp: 60,
          type: 'CC',
          dmg: 0,
          range: 8,
          desc: 'Control enemy for 8s, fighting for your team',
          color: '#6c5ce7',
        },
      ],
      skillTrees: ['Telekinesis', 'Mind Arts', 'Psionic Storm'],
    },
  ],
  combatFeel: { castTimeMult: 0.3, gcdMult: 0.4 },
  maxLevel: 99,
  combatScaling: { fromLevel: 20, hpPerLevel: 1.05, dmgPerLevel: 1.055 },
  // Grander settlement re-skin (see classic.ts note): scale/spread only.
  worldTheme: { buildingScale: 1.6, buildingSpread: 2.2 },
};
