// FPS Realm — first-person-only combat realm, served at fps.moveweight.com.
// The camera is locked to the first-person view (fpsOnly), the reticle is
// always on, and the third-person / Diablo presets are hidden. Classes here
// are framed as precision-combat archetypes rather than ARPG roles.

import type { RealmContent } from '../types';

export const FPS_REALM: RealmContent = {
  id: 'fps',
  name: 'FPS Realm',
  tagline: 'First-person only — reticle up, aim true, no third-person crutch',
  description:
    'A locked first-person realm for players who want the world down the ' +
    'sights. The camera never leaves your eyes, the reticle is always live, ' +
    'and every encounter is won by aim and movement.',
  mood: 'First-Person · Precise · Relentless',
  season: {
    eyebrow: 'Season 1',
    title: "The Marksman's Locker",
    body: "Limited weapon finishes from the marksman's locker. Account-wide, purely cosmetic, and shown to everyone who has you in their sights.",
  },
  accentHex: '#ff5a5f',
  bgGradient: 'linear-gradient(135deg, #1a0d0d 0%, #08060a 100%)',
  previewColors: { primary: '#ff5a5f', secondary: '#7bdff2', bg: '#140a0a' },
  fpsOnly: true,
  branding: {
    logoSrc: '/cryptic-realm-logo-512.webp',
    brandText: 'Cryptic Realm - FPS',
    loadingScreenSrc: '/cryptic-realm-loading-bg.webp',
    loadingArtHasWordmark: true,
    discordUrl: 'https://discord.gg/WnxcamHJdh',
    showDonate: false,
    showAuthentikSso: true,
  },
  classes: [
    {
      id: 'vanguard',
      name: 'Vanguard',
      role: 'Tank',
      baseClass: 'paladin',
      icon: '\u{1F6E1}',
      color: '#ff5a5f',
      lore: 'Front-line breachers who push the reticle into the enemy’s face. Heavy shields, heavier resolve.',
      baseStats: {
        maxHp: 200,
        maxMp: 70,
        str: 30,
        dex: 16,
        vit: 36,
        nrg: 8,
        dmg: 24,
        def: 34,
        spd: 1.1,
      },
      skills: [
        {
          name: 'Breach Charge',
          icon: '\u{1F4A5}',
          mp: 20,
          type: 'Mobility',
          dmg: 180,
          range: 8,
          desc: 'Rush forward, knocking back and dealing 180',
          color: '#ff5a5f',
        },
        {
          name: 'Riot Shield',
          icon: '\u{1F6E1}',
          mp: 30,
          type: 'Buff',
          dmg: 0,
          range: 0,
          desc: 'Raise a frontal shield blocking 70% damage for 6s',
          color: '#f1c40f',
        },
        {
          name: 'Suppressing Fire',
          icon: '\u{1F525}',
          mp: 18,
          type: 'AoE',
          dmg: 140,
          range: 14,
          desc: 'Spray a cone, slowing hit enemies 40%',
          color: '#e67e22',
        },
        {
          name: 'Last Stand',
          icon: '\u{1F396}',
          mp: 40,
          type: 'Buff',
          dmg: 0,
          range: 0,
          desc: 'Below 30% HP, gain +50% damage and immunity to CC for 5s',
          color: '#c0392b',
        },
      ],
      skillTrees: ['Breaching', 'Bulwark', 'Resolve'],
    },
    {
      id: 'marksman',
      name: 'Marksman',
      role: 'DPS',
      baseClass: 'hunter',
      icon: '\u{1F3AF}',
      color: '#7bdff2',
      lore: 'One breath, one shot. Marksmen treat the reticle as a contract: whatever it covers, dies.',
      baseStats: {
        maxHp: 95,
        maxMp: 110,
        str: 14,
        dex: 38,
        vit: 12,
        nrg: 14,
        dmg: 38,
        def: 10,
        spd: 1.6,
      },
      skills: [
        {
          name: 'Headshot',
          icon: '\u{1F52B}',
          mp: 16,
          type: 'Projectile',
          dmg: 360,
          range: 24,
          desc: 'Precise shot down the reticle; 360, crit if scoped',
          color: '#7bdff2',
        },
        {
          name: 'Quick Scope',
          icon: '\u{1F50D}',
          mp: 10,
          type: 'Buff',
          dmg: 0,
          range: 0,
          desc: 'Next shot in 2s is guaranteed crit',
          color: '#3498db',
        },
        {
          name: 'Penetrator',
          icon: '\u{1F3F9}',
          mp: 22,
          type: 'Projectile',
          dmg: 280,
          range: 24,
          desc: 'Round pierces all enemies in a line',
          color: '#2980b9',
        },
        {
          name: 'Steady Aim',
          icon: '\u{1F9D8}',
          mp: 25,
          type: 'Buff',
          dmg: 0,
          range: 0,
          desc: 'Remove sway and +30% range for 8s',
          color: '#1abc9c',
        },
      ],
      skillTrees: ['Precision', 'Ballistics', 'Overwatch'],
    },
    {
      id: 'operator',
      name: 'Operator',
      role: 'Assassin',
      baseClass: 'rogue',
      icon: '\u{1F576}',
      color: '#9b59b6',
      lore: 'Flank, breach, vanish. Operators win fights that end before the enemy’s reticle finds them.',
      baseStats: {
        maxHp: 100,
        maxMp: 110,
        str: 18,
        dex: 34,
        vit: 12,
        nrg: 18,
        dmg: 34,
        def: 12,
        spd: 2.0,
      },
      skills: [
        {
          name: 'Knife Lunge',
          icon: '\u{1F52A}',
          mp: 14,
          type: 'Melee',
          dmg: 300,
          range: 3,
          desc: 'Close instantly and stab for 300',
          color: '#9b59b6',
        },
        {
          name: 'Smoke & Move',
          icon: '\u{1F4A8}',
          mp: 18,
          type: 'Mobility',
          dmg: 0,
          range: 0,
          desc: 'Drop smoke, gain 60% evasion and speed for 3s',
          color: '#95a5a6',
        },
        {
          name: 'Flashbang',
          icon: '\u{1F4A1}',
          mp: 20,
          type: 'CC',
          dmg: 40,
          range: 8,
          desc: 'Blind enemies in a cone for 2.5s',
          color: '#f1c40f',
        },
        {
          name: 'Silent Kill',
          icon: '\u{1F910}',
          mp: 40,
          type: 'Melee',
          dmg: 540,
          range: 3,
          desc: 'Execute from behind: 540, doubled if target unaware',
          color: '#e74c3c',
        },
      ],
      skillTrees: ['Infiltration', 'Evasion', 'Wetwork'],
    },
    {
      id: 'medic',
      name: 'Combat Medic',
      role: 'Healer',
      baseClass: 'priest',
      icon: '✚',
      color: '#2ecc71',
      lore: 'They keep the squad shooting. A medic’s reticle picks targets to revive as readily as ones to drop.',
      baseStats: {
        maxHp: 115,
        maxMp: 160,
        str: 12,
        dex: 20,
        vit: 18,
        nrg: 30,
        dmg: 22,
        def: 16,
        spd: 1.5,
      },
      skills: [
        {
          name: 'Stim Dart',
          icon: '\u{1F489}',
          mp: 20,
          type: 'Heal',
          dmg: 0,
          range: 16,
          desc: 'Fire a healing dart restoring 260 HP',
          color: '#2ecc71',
        },
        {
          name: 'Adrenaline',
          icon: '\u{1F4AA}',
          mp: 28,
          type: 'Buff',
          dmg: 0,
          range: 10,
          desc: 'Ally gains +40% fire rate and move speed for 6s',
          color: '#27ae60',
        },
        {
          name: 'Revive Beacon',
          icon: '\u{1F198}',
          mp: 45,
          type: 'Heal',
          dmg: 0,
          range: 8,
          desc: 'Drop a beacon reviving downed allies over 4s',
          color: '#16a085',
        },
        {
          name: 'Triage Field',
          icon: '\u{1F3E5}',
          mp: 35,
          type: 'Heal',
          dmg: 0,
          range: 0,
          desc: 'Group heal 160 + remove bleeds',
          color: '#1abc9c',
        },
      ],
      skillTrees: ['Field Medicine', 'Stimulants', 'Recovery'],
    },
    {
      id: 'engineer',
      name: 'Engineer',
      role: 'Support',
      baseClass: 'hunter',
      icon: '\u{1F527}',
      color: '#f39c12',
      lore: 'Engineers shape the battlefield — turrets, mines, and deployables that hold the reticle line when the squad can’t.',
      baseStats: {
        maxHp: 120,
        maxMp: 130,
        str: 16,
        dex: 22,
        vit: 20,
        nrg: 24,
        dmg: 24,
        def: 18,
        spd: 1.4,
      },
      skills: [
        {
          name: 'Auto Turret',
          icon: '\u{1F916}',
          mp: 35,
          type: 'Summon',
          dmg: 0,
          range: 0,
          desc: 'Deploy a turret firing at the nearest enemy (110 DPS)',
          color: '#f39c12',
        },
        {
          name: 'Proximity Mine',
          icon: '\u{1F4A3}',
          mp: 22,
          type: 'AoE',
          dmg: 260,
          range: 6,
          desc: 'Place a mine dealing 260 in a radius',
          color: '#e67e22',
        },
        {
          name: 'Ammo Crate',
          icon: '\u{1F4E6}',
          mp: 25,
          type: 'Buff',
          dmg: 0,
          range: 8,
          desc: 'Drop a crate: allies regen MP and +20% damage near it',
          color: '#d35400',
        },
        {
          name: 'Barricade',
          icon: '\u{1F9F1}',
          mp: 30,
          type: 'Buff',
          dmg: 0,
          range: 6,
          desc: 'Raise cover blocking projectiles for 12s',
          color: '#7f8c8d',
        },
      ],
      skillTrees: ['Fabrication', 'Demolition', 'Logistics'],
    },
  ],
};
