// The Cinderveil: the infernal realm's lore overlay (naming-bible PRIMARY
// renames, docs/lore-rebrand/inventory.md surfaces). DISPLAY STRINGS ONLY,
// keyed by canonical ids and resolved in tEntity()/t() before the locale
// tables (src/ui/entity_i18n.ts realmEntityText). Canonical English sim text,
// ids, i18n keys, save data, music-zone keys, dungeon-finder tokens and the
// /api/claudium/* routes are untouched; realms without entityText behave
// byte-identically. Generated by a one-off sweep of the canonical content
// (noun substitution only, prose otherwise preserved); edit by hand from here.
// Style: no em/en dashes, no emoji in player-facing strings.

import type { RealmEntityText } from '../types';

export const INFERNAL_ENTITY_TEXT: RealmEntityText = {
  "zones": {
    "drakelands": {
      "name": "The Cinderscale Barrens"
    },
    "eastbrook_vale": {
      "name": "Candlebrook Vale",
      "welcome": "Find Marshal Ashbrook in town - he has work for you.",
      "pois": {
        "0": "Candlebrook",
        "4": "Shroudspinner",
        "10": "Harrowfield",
        "11": "Candlebrook",
        "15": "Shroudspinner",
        "21": "Harrowfield",
        "25": "The Lastlight Causeway"
      }
    },
    "farshore_isle": {
      "name": "Lastlight Isle",
      "pois": {
        "4": "The Lastlight Breach"
      }
    },
    "galecrest": {
      "name": "The Keening Scar",
      "pois": {
        "7": "The Keening Scar Stables"
      }
    },
    "mirefen_marsh": {
      "name": "The Sorrowfen",
      "pois": {
        "7": "The Drowned Chancel"
      }
    },
    "thornpeak_heights": {
      "name": "Martyrspike Heights"
    },
    "veiled_hollow": {
      "name": "Shroudhollow"
    },
    "wraithwood": {
      "name": "Gallowsroot"
    }
  },
  "npcs": {
    "apothecary_lin": {
      "name": "Apothecary Rue"
    },
    "bursar_fernando": {
      "name": "Bursar Ferrand"
    },
    "card_master": {
      "name": "The Bonedealer"
    },
    "chronicler_saul": {
      "name": "Saul the Cinderscribe"
    },
    "groundskeeper_bram": {
      "title": "Keeper of Harrowfield",
      "greeting": "The truce holds at Harrowfield, $C: boots and shoulders only. Care to play for the Copper Pail?"
    },
    "marshal_redbrook": {
      "name": "Marshal Ashbrook"
    },
    "mercenary_kael": {
      "name": "Kael the Oathless"
    },
    "realtor_maribel": {
      "name": "Steward Maribel"
    },
    "stablemaster_marla": {
      "greeting": "Every rider walks in on two legs, $C. I will not hand you the reins until you can sit the Valorsteed without kissing the dirt, and the Keening Scar wind shows no mercy to a bad seat."
    },
    "the_merchant": {
      "name": "The Pardoner"
    },
    "tinker_gizzel": {
      "name": "Tinker Snuff"
    },
    "town_defense_board": {
      "title": "Keeper of the Candlebrook Watch",
      "greeting": "The road needs a watch. Gather your party and hold Candlebrook against the dead."
    },
    "trader_wilkes": {
      "name": "Trader Wick"
    }
  },
  "quests": {
    "q_archetype_acceptance": {
      "text": "Every artisan of Candlebrook eventually settles on one craft to call their own. Prove yourself with a single deed, $N, and declare your path."
    },
    "q_bandits": {
      "text": "A pack of cutthroats has made camp in the southwest hills. They have robbed three wagons this week. Drive them out, slay 10 Tithe Cutters.",
      "objectives": {
        "0": "Tithe Cutter slain"
      }
    },
    "q_bastion_door": {
      "title": "The Drowned Chancel",
      "text": "The Drowned Chancel, a knight's hold that drowned in the fen a century ago, is where Voss's letters point, and where this Fogbinder sings his drowning hymns. The cult has warded its door with grave-stones. Bring me one of the ward stones, $N, and I will unweave the seal."
    },
    "q_crushers": {
      "objectives": {
        "0": "Martyrspike Crusher slain"
      }
    },
    "q_cult_camp": {
      "title": "Vestments for the Drowned",
      "text": "There, north past the third lake, where the mist never lifts. Grey robes, grey banners: the Gravecaller Choir, camped in the open like they already own the fen. They have stopped hiding, $N, which means they think they have already won. Prove them wrong. Cut down 12 of their cultists."
    },
    "q_cult_orders": {
      "completion": "This script... I last saw its like in Morthen's grimoire, in Candlebrook. The same hand has guided every grave we have fought over, $N."
    },
    "q_deacon": {
      "text": "So a deacon of the Gravecaller Choir stands at the heart of that camp, singing my drowned wardens up out of the lakes to serve him. His hymn ends today. Take the camp road north, $N, and put Deacon Voss in the ground, deep enough that nobody sings HIM back up."
    },
    "q_fen_supplies": {
      "text": "A caravan out of Candlebrook went into the mist three days back and never rang the gate bell. The wreck is strewn the whole length of the causeway, crates, casks, the lot, sinking slow. Salvage 5 loads of goods before the marsh finishes the job."
    },
    "q_fs_hold_the_riftfields": {
      "title": "Hold the Lastlight Breach",
      "text": "East of town the grain rows have gone to wrack, and the wretches that came through the Lastlight Breach break now pick them clean. My people cannot tend a field they cannot stand in, $N. Cull ten of the wretches and give the farmers back their ground."
    },
    "q_fs_moss_and_mending": {
      "objectives": {
        "1": "Lastlight Salt Moss"
      }
    },
    "q_fs_steel_for_the_redoubt": {
      "completion": "Salt-pitted and break-scarred, and it will hold an edge all the same. Here, I lined these grips myself. Steel for steel, $N: it is the only trade Lastlight Isle runs these days."
    },
    "q_fs_the_great_break": {
      "completion": "Ollun sent word ahead: the singing stopped. My whole town heard the quiet, $N, and half of them wept at the sound of nothing at all. Wear this mantle. Lastlight Isle does not forget who held its shore."
    },
    "q_fs_the_three_bells": {
      "text": "Three watchbells stand the coast beyond my own: one on the Landing point, one on the south strand, one out by the Lastlight Breach shore. If a rope has rotted or a clapper has been carried off, the town learns of a break when it is already in the streets. Walk the coast, $N, and ring each bell once, so I know it still has a voice."
    },
    "q_fv_snowline_report": {
      "text": "Every soul who climbs out of the Cinderscale Barrens passes my fire, $N, and fewer climb every week. Warden Kaldra holds Icemantle up the north road. Tell her the pass is still open, and tell her a stranger walked it alone."
    },
    "q_glimmermere_light": {
      "title": "A Wake of Candles"
    },
    "q_gravewyrm": {
      "text": "There is no rite left to stop, $N, only the Wyrm itself, half-woken in its hollow, gorged on the dead of the Vale and the fen. If it rises, the wall, the marsh, Candlebrook, everything we have defended falls in a single night. Take your companions into the Wyrm's Hollow and finish what we began in a chapel yard so long ago. The Light has carried you this far; carry it the rest of the way.",
      "completion": "It is over. The dead of three lands may rest, the mountain sleeps unhaunted, and it is your name, $N, that every bell from here to Candlebrook rings tonight."
    },
    "q_hollow": {
      "text": "Morthen the Gravecaller waits at the bottom of the Hollowmass Ossuary, ringed by the elite dead he has raised. He is far beyond any one hero, take four companions, no fewer. End him, and the Vale's dead will finally sleep.",
      "completion": "The whispering has stopped. You have done what the whole Vale could not, $N, the dead sleep, and Candlebrook owes you everything it has."
    },
    "q_idols": {
      "completion": "Gravecaller work, older than Morthen, older than me. The sect did not begin in Candlebrook, $N. It began here, and the lake has been keeping its secrets."
    },
    "q_mogger": {
      "completion": "Mogger dead at last. Candlebrook's fields are safer, and you leave the Vale with one more tale worth retelling."
    },
    "q_names_of_the_dead": {
      "text": "If the Gravecaller Choir raised our dead, I must know whose graves they robbed. The chapel sexton kept a burial ledger, and the wind has scattered its pages across the chapel yard. Gather 3 of them for me, $N, the dead deserve to be called by their names.",
      "completion": "These poor souls... and look here. Sexton Marrow, the chapel's own living caretaker, his grave the first disturbed. Morthen began with the very man who buried Candlebrook's dead."
    },
    "q_necromancers": {
      "completion": "Light forgive us. These hold the dead of the Vale and the fen, every corpse the Gravecaller Choir ever raised, harvested. They were never building an army, $N. They were gathering a tithe."
    },
    "q_nythraxis_bound_guardian": {
      "completion": "The three relics tell the same story: Aldren fought to defend his king, Malric broke the boundary of death, and Voss tried to stop what followed. The seal is weakening, and this signet is the key to Nythraxis's tomb. You are now attuned to enter The Crypt of Nythraxis. Return to the abandoned crypt, unlock the royal door, and face Nythraxis before the old king's rage spills beyond Martyrspike."
    },
    "q_nythraxis_restless_dead": {
      "text": "Something has changed in Martyrspike Heights, $N. The dead no longer wander aimlessly. They gather and march through the northern bonefields beyond Highwatch, where the old battlefield meets the cliff road. Go there, investigate the unrest among the Boneclad Revenants, and bring back any proof of what is driving them.",
      "completion": "The same mark appears on every shard... a crown. I have seen this before, cut into old graves no Candlebrook record remembers."
    },
    "q_nythraxis_scourges_end": {
      "text": "The signet has opened the way, $N, but an open tomb is not a victory. Nythraxis was a king once, and the ruin beneath Martyrspike is still bound to his will. Enter the crypt with allies you trust. Break the deathless crown before its command reaches the battlefield above.",
      "completion": "Then the crown is silent at last. Martyrspike will still carry its dead, but no king below it will call them to war again. You have ended what Aldren, Malric, and Voss could only contain."
    },
    "q_nythraxis_sealed_crypt": {
      "text": "The visions point to the abandoned crypt in the eastern cliff. There is an old legend that the crypt housed a king. Perhaps Martyrspike sealed him below after Malric's ritual twisted him into something deathless. Enter the crypt and see what remains inside."
    },
    "q_ogre_edges": {
      "text": "The Martyrspike clans never come this far east, yet here they are, camped in the eastern foothills with war paint on. Somebody is paying them, $N, and ogres do not take promises. Cut twelve of them down while I find out who holds the purse.",
      "objectives": {
        "0": "Martyrspike Ogre slain"
      }
    },
    "q_prof_amends_outfitter": {
      "text": "Back at my loom after all. I hold no grudge, $N, but the thread remembers a hand that let it go, and the cost of taking it up again is measured out longer each time. Cull the Shroudspinner Lurkers crowding the eastern woods, and the labor will settle your hands before they touch good silk again.",
      "objectives": {
        "0": "Shroudspinner Lurker culled"
      }
    },
    "q_prof_attune_outfitter": {
      "text": "Measure the cost before you cut, that is the first rule at my loom. Choose me and Leatherworking and Tailoring become your two majors, the pair you may carry beyond rare work; the craft opposite them settles in as your hobby, taken to rare and left there. The trades you set aside are not unravelled, $N, only folded away, dormant until you take them up again. Be certain, though: should you leave this pair and later want it back, the way home is paid in labor that lengthens each time, five culled at first, then eight, then eleven, always a little more. If your mind is made, cull four Shroudspinner Lurkers and bring their silk to the loom, for good thread starts every good garment.",
      "objectives": {
        "0": "Shroudspinner Lurker culled"
      }
    },
    "q_prof_intro": {
      "text": "Every soul in Candlebrook works a trade besides the sword, $N. There are ore veins in the rocks around the Copper Dig, southeast of town. Go swing a pick and work 5 of them yourself, mind; I'll know the difference."
    },
    "q_prowler_pelts": {
      "text": "Every plank of that causeway rests on pilings wrapped in oiled prowler hide, the only thing the rot will not chew through. My stock is gone and the south spans are already sinking. Bring me 8 unspoiled pelts, $N, before we are all wading to Candlebrook."
    },
    "q_ringleader": {
      "completion": "Gorrak is dead? Then the Vale is free of his shadow. You have done Candlebrook a great service."
    },
    "q_sexton": {
      "text": "The ledger named him and the crypt holds him: Sexton Marrow, the chapel's caretaker, the first man Morthen raised, guarding his master's door in death as faithfully as he kept the chapel in life. Take four companions into the Hollowmass Ossuary and grant the old sexton the rest he was robbed of, $N."
    },
    "q_spiders": {
      "title": "Silk for the Dead",
      "text": "The lurkers in the eastern woods spin a silk I need for my poultices, and they have grown far too numerous besides. Cull 6 Shroudspinner Lurkers and cut 4 silk glands from their bellies.",
      "objectives": {
        "0": "Shroudspinner Lurker slain",
        "1": "Shroudspinner Silk Gland"
      }
    },
    "q_supplies": {
      "text": "Those bandits hit my last wagon and made off with four crates of goods: tools, salt, good Candlebrook linen. The crates are stacked around their camp in the southwest hills. Steal them back for me, would you?"
    },
    "q_the_codfather": {
      "text": "The Codfather isn't just a fish, $N, he's a cold-blooded killer. Old-timers swear he eats Mire Prowlers for breakfast, and even the Sorrowfen Widows won't spin their webs near the Deepfen Shallows out of sheer terror. He rules those waters, and marsh water takes an Ironreel Fishing Rod, no less; my counter sells them. Get one in hand, drag that old devil out of his waters, and I will admit you have joined the family."
    },
    "q_troll_fetishes": {
      "objectives": {
        "0": "Sorrowfen Troll Fetish"
      }
    },
    "q_trolls": {
      "title": "Mounds of the Sorrowfen",
      "text": "The Sorrowfen trolls have torn open the old barrow-mounds east of the far lake, burial mounds, $N, older than any kingdom of men. Whatever gold they think is down there, what they are letting OUT is worse. Drive them off the mounds: 12 trolls dead ought to do it.",
      "objectives": {
        "0": "Sorrowfen Troll slain"
      }
    },
    "q_velkhar": {
      "text": "Every thread we have followed, Morthen, Vael, the phylacteries, was spun by one hand: Grand Necromancer Velkhar, first of the Gravecaller Choir, keeper of the waking rite. He stands in the ritual vault below, pouring two lands' worth of stolen souls into the Wyrm. End him, $N, and the tithe ends with him."
    },
    "q_whispers": {
      "completion": "This sigil... it bears the mark of the Gravecaller Choir, a sect I had prayed was extinct. This is worse than I feared, $N."
    },
    "q_widows": {
      "objectives": {
        "0": "Sorrowfen Widow slain"
      }
    },
    "q_wolves": {
      "text": "The forest wolves grow bold, snapping at travelers on the north road. Thin their numbers, $N. Slay 8 Forest Wolves and Candlebrook will breathe easier."
    },
    "q_wyrm_sigils": {
      "text": "It is time you knew the whole of it, $N. The Gravecaller Choir serve Korzul the Gravewyrm, an ancient dragon sealed beneath this mountain, and every soul they have stolen since Candlebrook is a tithe poured into its waking. On the Sanctum Approach the cult has laid sigils to thin the seal. Bring me three; I would read the rite they are working."
    }
  },
  "mobs": {
    "fen_troll": {
      "name": "Sorrowfen Troll"
    },
    "mire_widow": {
      "name": "Sorrowfen Widow"
    },
    "mirefen_widowling": {
      "name": "Sorrowfen Widowling"
    },
    "nythraxis_scourge_of_thornpeak": {
      "name": "Nythraxis, Scourge of Martyrspike"
    },
    "ogre_crusher": {
      "name": "Martyrspike Crusher"
    },
    "sowfield_marauder": {
      "name": "Harrowfield Marauder"
    },
    "thornpeak_ogre": {
      "name": "Martyrspike Ogre"
    },
    "thunzharr_waking_peak": {
      "name": "Vhorzun, the Shackled Ember"
    },
    "vale_bandit": {
      "name": "Tithe Cutter"
    },
    "webwood_spider": {
      "name": "Shroudspinner Lurker"
    }
  },
  "items": {
    "eastbrook_arming_sword": {
      "name": "Candlebrook Arming Sword"
    },
    "eastbrook_buckler": {
      "name": "Candlebrook Buckler"
    },
    "eastbrook_chain_vest": {
      "name": "Candlebrook Chainmail Vest"
    },
    "eastbrook_druids_hide": {
      "name": "Candlebrook Druid's Hide"
    },
    "eastbrook_greatsword": {
      "name": "Candlebrook Greatsword"
    },
    "eastbrook_ritual_vestments": {
      "name": "Candlebrook Ritual Vestments"
    },
    "eastbrook_warded_leggings": {
      "name": "Candlebrook Warded Leggings"
    },
    "eastbrook_wool_trousers": {
      "name": "Candlebrook Wool Trousers"
    },
    "farshore_salt_moss": {
      "name": "Lastlight Salt Moss"
    },
    "kingsbane_last_oath": {
      "name": "Thronebane, Last Oath of Martyrspike"
    },
    "mirefen_skinner": {
      "name": "Sorrowfen Skinner"
    },
    "redbrook_blade": {
      "name": "Ashbrook Militia Blade"
    },
    "sableweb_cord": {
      "name": "Shroudspinner Cord"
    },
    "sableweb_slippers": {
      "name": "Shroudspinner Slippers"
    },
    "smoked_eel": {
      "name": "Smoked Sorrowfen Eel"
    },
    "thornpeak_wildwraps": {
      "name": "Martyrspike Wildwraps"
    },
    "troll_fetish": {
      "name": "Sorrowfen Troll Fetish"
    },
    "webwood_silk": {
      "name": "Shroudspinner Silk Gland"
    }
  },
  "dungeons": {
    "hollow_crypt": {
      "name": "Hollowmass Ossuary",
      "enterText": "You descend into the Hollowmass Ossuary..."
    },
    "nythraxis_boss_arena": {
      "leaveText": "You return to the cold air of Martyrspike."
    },
    "nythraxis_crypt": {
      "leaveText": "You return to the cold air of Martyrspike."
    },
    "sunken_bastion": {
      "name": "The Drowned Chancel",
      "enterText": "You wade down into the Drowned Chancel..."
    },
    "the_last_keep": {
      "leaveText": "You pull the keep door shut and step back into the Cinderscale Barrens wind."
    }
  },
  "letters": {
    "guild_trend_alchemy_cooking": {
      "body": "Artisan,\n\nWord reaches the Guild of your work in Alchemy and Cooking: draughts simmered and dishes seasoned, the two crafts feeding one another. Neighboring crafts worked together mark a hand ready for attunement. Those who bind this pair earn the name of Apothecary in time. Seek out Smith Haldren, the armorer of Candlebrook: he speaks for the masters for now. Prove your craft to him with work of your own hands, and he will see your two majors attuned.\n\nIn good standing,\nThe Crafting Guild"
    },
    "guild_trend_armorcrafting_engineering": {
      "body": "Artisan,\n\nWord reaches the Guild of your work in Armorcrafting and Engineering: plates riveted and gears trued, the two crafts feeding one another. Neighboring crafts worked together mark a hand ready for attunement. Seek out Smith Haldren, the armorer of Candlebrook: he speaks for the masters for now. Prove your craft to him with work of your own hands, and he will see your two majors attuned.\n\nIn good standing,\nThe Crafting Guild"
    },
    "guild_trend_cooking_leatherworking": {
      "body": "Artisan,\n\nWord reaches the Guild of your work in Cooking and Leatherworking: meals plated and hides cured, the two crafts feeding one another. Neighboring crafts worked together mark a hand ready for attunement. Seek out Smith Haldren, the armorer of Candlebrook: he speaks for the masters for now. Prove your craft to him with work of your own hands, and he will see your two majors attuned.\n\nIn good standing,\nThe Crafting Guild"
    },
    "guild_trend_enchanting_jewelcrafting": {
      "body": "Artisan,\n\nWord reaches the Guild of your work in Enchanting and Jewelcrafting: charms bound and stones polished, the two crafts feeding one another. Neighboring crafts worked together mark a hand ready for attunement. Seek out Smith Haldren, the armorer of Candlebrook: he speaks for the masters for now. Prove your craft to him with work of your own hands, and he will see your two majors attuned.\n\nIn good standing,\nThe Crafting Guild"
    },
    "guild_trend_engineering_alchemy": {
      "body": "Artisan,\n\nWord reaches the Guild of your work in Engineering and Alchemy: charges measured and reagents weighed, the two crafts feeding one another. Neighboring crafts worked together mark a hand ready for attunement. Those who bind this pair earn the name of Bombardier in time. Seek out Smith Haldren, the armorer of Candlebrook: he speaks for the masters for now. Prove your craft to him with work of your own hands, and he will see your two majors attuned.\n\nIn good standing,\nThe Crafting Guild"
    },
    "guild_trend_inscription_enchanting": {
      "body": "Artisan,\n\nWord reaches the Guild of your work in Inscription and Enchanting: scrolls lettered and charms woven, the two crafts feeding one another. Neighboring crafts worked together mark a hand ready for attunement. Seek out Smith Haldren, the armorer of Candlebrook: he speaks for the masters for now. Prove your craft to him with work of your own hands, and he will see your two majors attuned.\n\nIn good standing,\nThe Crafting Guild"
    },
    "guild_trend_jewelcrafting_weaponcrafting": {
      "body": "Artisan,\n\nWord reaches the Guild of your work in Jewelcrafting and Weaponcrafting: gems seated and edges ground, the two crafts feeding one another. Neighboring crafts worked together mark a hand ready for attunement. Seek out Smith Haldren, the armorer of Candlebrook: he speaks for the masters for now. Prove your craft to him with work of your own hands, and he will see your two majors attuned.\n\nIn good standing,\nThe Crafting Guild"
    },
    "guild_trend_leatherworking_tailoring": {
      "body": "Artisan,\n\nWord reaches the Guild of your work in Leatherworking and Tailoring: leather cut and cloth hemmed, the two crafts feeding one another. Neighboring crafts worked together mark a hand ready for attunement. Those who bind this pair earn the name of Outfitter in time. Seek out Smith Haldren, the armorer of Candlebrook: he speaks for the masters for now. Prove your craft to him with work of your own hands, and he will see your two majors attuned.\n\nIn good standing,\nThe Crafting Guild"
    },
    "guild_trend_tailoring_inscription": {
      "body": "Artisan,\n\nWord reaches the Guild of your work in Tailoring and Inscription: seams stitched and glyphs inked, the two crafts feeding one another. Neighboring crafts worked together mark a hand ready for attunement. Seek out Smith Haldren, the armorer of Candlebrook: he speaks for the masters for now. Prove your craft to him with work of your own hands, and he will see your two majors attuned.\n\nIn good standing,\nThe Crafting Guild"
    },
    "guild_trend_weaponcrafting_armorcrafting": {
      "body": "Artisan,\n\nWord reaches the Guild of your work in Weaponcrafting and Armorcrafting: blades tempered and plates fitted, the two crafts feeding one another. Neighboring crafts worked together mark a hand ready for attunement. Those who bind this pair earn the name of Smith in time. Seek out Smith Haldren, the armorer of Candlebrook: he speaks for the masters for now. Prove your craft to him with work of your own hands, and he will see your two majors attuned.\n\nIn good standing,\nThe Crafting Guild"
    },
    "letter_q_greyjaw": {
      "sender": "Marshal Ashbrook",
      "body": "Word travels fast in a town this small. The herders drank to your health last night, and Wick swears the wolf was the size of a cart. Let them embellish: you earned it.\n\nShare a meal on the watch.\n- Marshal Ashbrook"
    },
    "letter_q_wolves": {
      "sender": "Marshal Ashbrook",
      "body": "The herders can sleep with both eyes shut for once, and that is your doing. I have told the Ravenpost to carry you a little something from the watch fund.\n\nKeep your blade oiled.\n- Marshal Ashbrook"
    },
    "prof_tier_engineering_alchemy_1": {
      "sender": "Tinker Snuff"
    },
    "prof_tier_engineering_alchemy_2": {
      "sender": "Tinker Snuff"
    },
    "prof_tier_engineering_alchemy_3": {
      "sender": "Tinker Snuff"
    },
    "prof_tier_engineering_alchemy_4": {
      "sender": "Tinker Snuff"
    },
    "prof_tier_engineering_alchemy_5": {
      "sender": "Tinker Snuff"
    },
    "ravenpost_welcome": {
      "body": "Traveler,\n\nThe Ravenpost has opened its perches across the vale. Seek the raven pillars in Candlebrook, Fenbridge and Highwatch: from any of them you may send letters, coin and goods to other adventurers, and collect whatever the ravens bring you.\n\nEnclosed is a small courtesy for your first stamp.\n\nWings up,\nThe Ravenpost"
    }
  },
  "deeds": {
    "chr_farshore_first_cast": {
      "desc": "Catch a fish from the waters of Lastlight Isle."
    },
    "chr_farshore_gatherer": {
      "desc": "Harvest an ore vein, a wood stand, and an herb patch on Lastlight Isle."
    },
    "chr_galecrest_first_cast": {
      "desc": "Catch a fish from the waters of the Keening Scar."
    },
    "chr_galecrest_gatherer": {
      "desc": "Harvest an ore vein, a wood stand, and an herb patch in the Keening Scar."
    },
    "chr_marsh_chapter_iii": {
      "name": "Chronicle of the Sorrowfen",
      "desc": "See the fen's whole story through: the cult camp broken, the Fogbinder silenced in the Drowned Chancel, and every named terror of the mist laid low.",
      "title": "of the Sorrowfen"
    },
    "chr_marsh_first_cast": {
      "desc": "Catch a fish from the waters of Sorrowfen."
    },
    "chr_marsh_gatherer": {
      "desc": "Harvest an ore vein, a wood stand, and an herb patch in Sorrowfen."
    },
    "chr_marsh_rares": {
      "desc": "Slay the three named terrors of Sorrowfen: Mirejaw the Ravenous, Sloomtooth the Drowned, and Sister Nhalia."
    },
    "chr_marsh_rares_ii": {
      "desc": "Slay Grubjaw the Glutton, a fourth named terror of Sorrowfen left off the first reckoning."
    },
    "chr_peaks_chapter_iii": {
      "name": "Chronicle of Martyrspike",
      "title": "of Martyrspike"
    },
    "chr_peaks_gatherer": {
      "desc": "Harvest an ore vein, a wood stand, and an herb patch in Martyrspike Heights."
    },
    "chr_peaks_rares": {
      "desc": "Slay the four named terrors of Martyrspike Heights: the Ironvein Foreman, Brutok Skullsmasher, Voskar the Emberwing, and Marrowlord Varkas."
    },
    "chr_peaks_rares_ii": {
      "desc": "Slay Old Cragmaw and Shardlord Kazzix, two more named terrors of Martyrspike Heights left off the first reckoning."
    },
    "chr_vale_chapter_i": {
      "desc": "Finish the first chapter of Saul's chronicle: Candlebrook's opening errands, the lay of the Vale, and a first taste of its trades."
    },
    "chr_vale_chapter_ii": {
      "desc": "Finish the second chapter of Saul's chronicle: bandits, murlocs, and mine vermin put down, Harrowfield played, and the Reliquary braved."
    },
    "chr_vale_chapter_iii": {
      "desc": "See the Vale's whole story through: the Gravecaller unmasked, the Hollowmass Ossuary cleansed, and every named terror of the Vale laid low."
    },
    "chr_vale_cup_debut": {
      "desc": "Take the field and touch the ball in a Tallow Cup match at Harrowfield."
    },
    "chr_vale_first_cast": {
      "desc": "Catch a fish from the waters of Candlebrook Vale."
    },
    "chr_vale_gatherer": {
      "desc": "Harvest an ore vein, a wood stand, and an herb patch in Candlebrook Vale."
    },
    "chr_vale_rares": {
      "desc": "Slay the five named terrors of Candlebrook Vale: Old Greyjaw, Mogger, Grix the Tunnelking, Captain Verlan, and Wraithbinder Maldrec."
    },
    "chr_wraithwood_first_cast": {
      "desc": "Catch a fish from the waters of Gallowsroot."
    },
    "chr_wraithwood_gatherer": {
      "desc": "Harvest an ore vein, a wood stand, and an herb patch in Gallowsroot."
    },
    "dgn_hollow_crypt": {
      "desc": "Defeat Morthen the Gravecaller in the Hollowmass Ossuary."
    },
    "dgn_hollow_crypt_heroic": {
      "name": "Heroic: The Hollowmass Ossuary",
      "desc": "Defeat Morthen the Gravecaller in the Hollowmass Ossuary on Heroic difficulty."
    },
    "dgn_nythraxis": {
      "desc": "Defeat Nythraxis, Scourge of Martyrspike, beyond the sealed royal door."
    },
    "dgn_nythraxis_deathless": {
      "desc": "Defeat Nythraxis, Scourge of Martyrspike, on Heroic difficulty without a single raider dying."
    },
    "dgn_nythraxis_heroic": {
      "desc": "Defeat Nythraxis, Scourge of Martyrspike, on Heroic difficulty."
    },
    "dgn_sunken_bastion": {
      "desc": "Defeat Vael the Fogbinder in the Drowned Chancel."
    },
    "dgn_sunken_bastion_heroic": {
      "name": "Heroic: The Drowned Chancel",
      "desc": "Defeat Vael the Fogbinder in the Drowned Chancel on Heroic difficulty."
    },
    "dgn_thornpeak_rounds": {
      "desc": "Clear the Hollowmass Ossuary, the Drowned Chancel, the Drowned Temple, and Gravewyrm Sanctum."
    },
    "exp_long_road_north": {
      "desc": "Visit all three hub settlements: Candlebrook, Fenbridge, and Highwatch."
    },
    "exp_marsh_wayfarer": {
      "desc": "Visit all eight named places of Sorrowfen."
    },
    "exp_peaks_wayfarer": {
      "desc": "Visit all ten named places of Martyrspike Heights."
    },
    "exp_vale_wayfarer": {
      "desc": "Visit all eleven named places of Candlebrook Vale."
    },
    "prog_callused_hands": {
      "desc": "Complete A Trade for Every Hand and earn your first callus in Candlebrook's trades."
    },
    "pvp_card_duel_first_win": {
      "desc": "Win a Card Duel at the Bonedealer."
    },
    "pvp_vcup_clean_sheet": {
      "desc": "Win a rated Tallow Cup match as keeper without conceding a goal, in the 3v3 bracket or larger."
    },
    "pvp_vcup_first_goal": {
      "desc": "Score a goal in a rated Tallow Cup match."
    },
    "pvp_vcup_first_match": {
      "desc": "See out a full Tallow Cup match at Harrowfield, win or lose."
    },
    "pvp_vcup_first_save": {
      "desc": "Make a save as keeper in a rated Tallow Cup match, in the 3v3 bracket or larger. Only a shot moving fast enough to test your grip counts: a soft catch does not."
    },
    "pvp_vcup_first_win": {
      "desc": "Win a rated Tallow Cup match."
    },
    "pvp_vcup_golden_goal": {
      "desc": "Score the golden goal that decides a rated Tallow Cup match."
    },
    "pvp_vcup_guild_win": {
      "desc": "Win a rated Tallow Cup match entered under your guild's banner."
    },
    "pvp_vcup_hat_trick": {
      "desc": "Score three goals in a single rated Tallow Cup match, in the 3v3 bracket or larger."
    },
    "pvp_vcup_wins_10": {
      "desc": "Win 10 rated Tallow Cup matches."
    },
    "pvp_vcup_wins_25": {
      "desc": "Win 25 rated Tallow Cup matches."
    },
    "soc_meet_bursar": {
      "desc": "Pay your respects to Bursar Ferrand, keeper of the Gilded Strongbox in Candlebrook."
    }
  },
  "catalog": {
    "hud.core.riftLabelRanked": "{rank}: {name}",
    "hudChrome.bg.blurb": "Two ruined keeps face each other across a walled hollow in the shadow of Martyrspike: Crimson to the south, Azure to the north, and the older Ruin Courtyard between them that neither has ever held. Five a side, one banner each, and the first to carry three of theirs home takes the field.",
    "hudChrome.keybinds.valecup": "Tallow Cup",
    "hudChrome.vcup.bannerDraw": "A draw at Harrowfield.",
    "hudChrome.vcup.bannerFound": "The Tallow Cup calls: {nationA} vs {nationB}!",
    "hudChrome.vcup.bannerLoss": "Defeat at Harrowfield.",
    "hudChrome.vcup.bannerWin": "Victory at Harrowfield!",
    "hudChrome.vcup.bet.aria": "Tallow Cup match betting",
    "hudChrome.vcup.bet.lostLog": "Your Tallow Cup bet lost: {amount}.",
    "hudChrome.vcup.bet.wonLog": "Your Tallow Cup bet won: {amount} returned.",
    "hudChrome.vcup.close": "Close the Tallow Cup window",
    "hudChrome.vcup.gossipOpenAria": "Open the Tallow Cup window",
    "hudChrome.vcup.indicatorLive": "Tallow Cup",
    "hudChrome.vcup.indicatorOpen": "Open the Tallow Cup window",
    "hudChrome.vcup.indicatorQueued": "Tallow Cup queue: {bracket}, position {position} of {count}",
    "hudChrome.vcup.liveAria": "Tallow Cup: {nationA} {scoreA}, {nationB} {scoreB}",
    "hudChrome.vcup.liveHeading": "Now at Harrowfield",
    "hudChrome.vcup.logDraw": "The bout at Harrowfield ends in a draw.",
    "hudChrome.vcup.logFound": "Your Tallow Cup match is ready: {nationA} vs {nationB}.",
    "hudChrome.vcup.logLoss": "You lose the bout at Harrowfield.",
    "hudChrome.vcup.logQueued": "You join the Tallow Cup queue for {bracket} (position {position}).",
    "hudChrome.vcup.logUnqueued": "You leave the Tallow Cup queue.",
    "hudChrome.vcup.logWin": "You win the bout at Harrowfield.",
    "hudChrome.vcup.nation.mirefen": "The Sorrowfen",
    "hudChrome.vcup.nation.thornpeak": "Martyrspike",
    "hudChrome.vcup.nation.vale": "Candlebrook Vale",
    "hudChrome.vcup.offlineNote": "The fixture book is closed. The Tallow Cup is not available right now.",
    "hudChrome.vcup.queueNote": "Queue from anywhere; the whistle calls you to Harrowfield.",
    "hudChrome.vcup.title": "The Tallow Cup",
    "hudChrome.vcup.walkUp": "Walk up to Harrowfield to watch from the stands.",
    "hudChrome.wocStore.skins.brasscrown_staff.lore": "Turned from seasoned hardwood and crowned with a brass finial the Candlebrook smiths cast by the hundred but perfect by the one. It belongs to the sort of traveller who wants to be taken seriously at Fenbridge's gate and Highwatch's wall alike. A walking stick that has never truly needed to walk; the dyed band matches a coat you can guess the price of.",
    "hudChrome.wocStore.skins.cinderlatch_crossbow.lore": "The strangest of the ember-forged: the mountain's fire poured into a machine. Orange seeps from cracks in the prod, and a smouldering coal in the tiller keeps the string from ever stiffening in Martyrspike's cold or Sorrowfen's damp. Its bolts leave the groove already warm and land warmer. A hunter's answer to a wall where the enemy does not feel the cold either.",
    "hudChrome.wocStore.skins.cosmarch_staff.lore": "A shaft of star-metal crowned with a molten-gold core and a ring of golden shards that march around it in slow, endless orbit: a little cosmos, etched with constellations that match no sky over Martyrspike. Aurora winds up its length like smoke that forgot to rise. Those who bore it claimed they could feel the void turning through it, the way Ysolei's mere 'drinks the moonlight': patient, and cold, and looking back.",
    "hudChrome.wocStore.skins.emberwish_wand.lore": "Not the fallen star itself but the last mote of a dying one: a single molten-gold ember of a sun already gone out, wreathed in the sparks that were its final light. Its cosmos-black shaft is etched with the constellations that watched it die. The Sorrowfen crofters say it grants one wish to whoever holds it at true dusk; they also say every soul who held it wished for more time, and that the Drowned Moon granted none of them any.",
    "hudChrome.wocStore.skins.fletcher_s_guild_bow.lore": "The closest thing the realm has to a guild is a fletcher's stamp on the riser, a promise about what's inside, the way a vintner seals a cask. Lacquered walnut, brass at the limb tips, a waxed linen string that won't fray through a Sorrowfen rain. Every joint argues for the price. Draw it once past the Widow Thicket and the argument wins.",
    "hudChrome.wocStore.skins.frostbite_dagger.lore": "Thin as a held breath and twice as cold: a splinter of Martyrspike glacier honed to a single glowing vein, so keen the wound is frozen shut before the blood remembers to run. Its name is borrowed from the grave-chill the dead carry down off the peaks. It never needs sharpening; ice does not dull, Loremaster Caddis notes drily, it only waits.",
    "hudChrome.wocStore.skins.glaciersplit_axe.lore": "Hewn from the blue heart of the Martyrspike glacier, where two centuries of ice have pressed the cold until it glows on its own. It trails vapour even at rest, and the crack of it landing is a crevasse opening under Stalker Ridge. Highwatch gives its fallen to the ice up there; so this is a weapon meant to keep the thaw, and whatever the thaw would wake, at bay.",
    "hudChrome.wocStore.skins.ice_fang_sword.lore": "The flagship of the frozen grade, and the piece every collector reaches for first. Ice Fang was carved, not forged, from a fang of the glacier that caps Martyrspike above Highwatch, its cyan core burning cold as the light off the Glimmermere. It rimes the very air it cuts. The wall-guard swear one soldier carried it the night the high snows held the Wyrmcult back, and 'bought the wall a winter.'",
    "hudChrome.wocStore.skins.meteorlatch_crossbow.lore": "Forged of raw meteoric star-metal while the Sorrowfen crater still glowed, debris 'too hot to handle,' hammered into limbs of cosmos-black etched with constellations, a molten-gold core banked along the tiller. It nocks no bolt but conjures one: a shaft of starfire, loosed like a verdict and landing like the end of one. When Highwatch feared even the deathless crown of Nythraxis might not be the worst thing beneath the peaks, this is the weapon they wanted on the wall. Aim it well.",
    "hudChrome.wocStore.skins.rimecrusher_mace.lore": "Not carved but grown: Martyrspike ice coaxed around a cold cyan core until it set as hard as Hode's best steel. Hoarfrost creeps down the silvered haft toward the hand and never quite arrives. Where it strikes, water freezes; where it rests, the ground whitens. The grave-cold of the peaks, made small enough to swing at the things that climb the wall.",
    "hudChrome.wocStore.skins.skyrender_axe.lore": "Beaten from the crater's rim, where the fallen star tore the sky's own reflection out of Sorrowfen and left a wound that still steams. The head looks like a piece of torn night: molten-gold cracks, constellations no scholar at Highwatch can name, an aurora bleeding off the edge with every swing. Brother Aldric blessed it and would not touch it. To lift it is to hold the hole the heavens left.",
    "hudChrome.wocStore.skins.solheim_sword.lore": "When the star fell out of the western sky and 'burst like a forge' beyond the Widow Thicket, Brother Aldric pulled its still-smouldering heart from the Sorrowfen crater and begged the realm's smiths to work 'a thing that does not belong to this world.' They made one greatsword of it: Solheim. Its molten-gold core splits the cosmos-black blade like dawn cracking a night sky, and shards of star-metal orbit the guard on paths no hand set. Only one was ever forged. There will not be another.",
    "hudChrome.wocStore.skins.starfall_mace.lore": "A star-core caught the instant before it died, ringed with the debris that fell with it, frozen an inch from oblivion. Its cosmos-black flanges run with trapped starlight, and aurora spills from the seams when it is raised. The old Priests of the Light called a falling star a judgment, a verdict handed down from above that no shield was meant to stop, and named this after the one that came down on Sorrowfen.",
    "hudChrome.wocStore.skins.winterbite.lore": "A bow of silvered steel and Martyrspike ice, its riser lit by a cold cyan core that freezes the arrow to the string. It nocks a shaft of solid glacier-ice that reforms each draw; the archer carries no quiver on the wall, only the cold. Highwatch held Stalker Ridge through a siege with one like it: a single bowman, they say, and a winter's worth of arrows that were always already there.",
    "loading.connectingRealm": "Reaching through the Cinderveil...",
    "loading.enteringWorld": "The Cinderveil awaits...",
    "loading.world": "Entering the Cinderveil...",
    "loading.worldProgress": "Entering the Cinderveil... {done}/{total}"
  },
  "riftRanks": {
    "A": "Rend",
    "B": "Tear",
    "C": "Fray",
    "S": "Sundering"
  },
  "waypoints": {
    "wp_eastbrook_vale": "Candlebrook",
    "wp_eastbrook_vale_wild": "Candlebrook Trail"
  },
  "musicZones": {
    "dungeon_hollow_crypt": "Hollowmass Ossuary",
    "dungeon_sunken_bastion": "The Drowned Chancel",
    "marsh": "The Sorrowfen",
    "peaks": "Martyrspike Heights",
    "town_eastbrook": "Candlebrook Vale (Town)",
    "vale": "The Ashen Vale",
    "vale_cup": "The Tallow Cup",
    "vale_legacy": "Candlebrook Vale"
  },
  "vcBotNames": [
    "Old Sallow",
    "Reeve Mourne",
    "Tally Sexton",
    "Bess Harrow",
    "Wick Tallow",
    "Sorrel Ash",
    "Hen Gallows",
    "Pip Cinder",
    "Mott Graves"
  ]
};
